parameters:
  configurationName: ''
  configurationParameters: ''
  runTestsParameters: ''
  timeoutInMinutes: 60

jobs:
  - job: ${{ parameters.configurationName }}
    timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
    pool:
      vmImage: 'ubuntu-22.04'
    steps:
      - script: |
          sudo apt-get update -y | true
          sudo apt install \
            bison \
            re2c \
            autoconf \
            clang \
            locales \
            ldap-utils \
            openssl \
            slapd \
            language-pack-de \
            libgmp-dev \
            libicu-dev \
            libtidy-dev \
            libenchant-2-dev \
            libaspell-dev \
            libpspell-dev \
            libsasl2-dev \
            libxpm-dev \
            libzip-dev \
            libsqlite3-dev \
            libwebp-dev \
            libonig-dev \
            libkrb5-dev \
            libgssapi-krb5-2 \
            libcurl4-openssl-dev \
            libxml2-dev \
            libxslt1-dev \
            libpq-dev \
            libreadline-dev \
            libldap2-dev \
            libsodium-dev \
            libargon2-0-dev \
            libmm-dev \
            libsnmp-dev \
            postgresql \
            postgresql-contrib \
            snmpd \
            snmp-mibs-downloader \
            freetds-dev \
            unixodbc-dev \
            llvm \
            libc-client-dev \
            dovecot-core \
            dovecot-pop3d \
            dovecot-imapd \
            sendmail \
            firebird-dev \
            liblmdb-dev \
            libtokyocabinet-dev \
            libdb-dev \
            libqdbm-dev \
            libjpeg-dev \
            libpng-dev \
            libfreetype6-dev \
            ${{ parameters.packages }}
        displayName: 'APT'
      - script: |
          mkdir /opt/oracle
          wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip
          unzip instantclient-basiclite-linuxx64.zip
          wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-sdk-linuxx64.zip
          unzip instantclient-sdk-linuxx64.zip
          mv instantclient_*_* /opt/oracle/instantclient
          # Interferes with libldap2 headers.
          rm /opt/oracle/instantclient/sdk/include/ldap.h
        displayName: 'Install Oracle Instant Client'
    - script: |
        export CC=clang
        export CXX=clang++
        export CFLAGS="-DZEND_TRACK_ARENA_ALLOC"
        ./buildconf --force
        # msan requires all used libraries to be instrumented,
        # so we should avoiding linking against anything but libc here
        ./configure ${{ parameters.configurationParameters }} \
            --enable-option-checking=fatal \
            --prefix=/usr \
            --without-sqlite3 \
            --without-pdo-sqlite \
            --without-libxml \
            --disable-dom \
            --disable-simplexml \
            --disable-xml \
            --disable-xmlreader \
            --disable-xmlwriter \
            --without-pcre-jit \
            --disable-opcache-jit \
            --enable-phpdbg \
            --enable-fpm \
            --with-pdo-mysql=mysqlnd \
            --with-mysqli=mysqlnd \
            --disable-mysqlnd-compression-support \
            --without-pear \
            --enable-exif \
            --enable-sysvsem \
            --enable-sysvshm \
            --enable-shmop \
            --enable-pcntl \
            --enable-mbstring \
            --disable-mbregex \
            --enable-sockets \
            --enable-bcmath \
            --enable-calendar \
            --enable-ftp \
            --enable-zend-test \
            --enable-dl-test=shared \
            --enable-werror \
            --enable-memory-sanitizer \
            --with-config-file-path=/etc \
            --with-config-file-scan-dir=/etc/php.d
      displayName: 'Configure Build'
    - script: make -j$(/usr/bin/nproc) >/dev/null
      displayName: 'Make Build'
    - script: |
        sudo make install
        sudo mkdir     /etc/php.d
        sudo chmod 777 /etc/php.d
        echo mysqli.default_socket=/var/run/mysqld/mysqld.sock     > /etc/php.d/mysqli.ini
        echo pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock  > /etc/php.d/pdo_mysql.ini
      displayName: 'Install Build'
    - script: |
        sudo service mysql start
        mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS test"
      displayName: 'Setup'
    - template: test.yml
      parameters:
        configurationName: ${{ parameters.configurationName }}
        runTestsParameters: ${{ parameters.runTestsParameters }}
    - template: test.yml
      parameters:
        configurationName: ${{ parameters.configurationName }}
        runTestsName: 'OpCache'
        runTestsParameters: >-
          ${{ parameters.runTestsParameters }}
          -d zend_extension=opcache.so -d opcache.enable_cli=1
