name: Create Oracle container
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        docker run \
          -e "ORACLE_PASSWORD=pass" \
          -p 1521:1521 \
          --name oracle \
          -h oracle \
          -d gvenzl/oracle-xe:slim
