#! /bin/sh
#
# This script removes the Copyright messages and inserts 
# Copyright Abandoned messages.
#


if test -z "$1"; then
	echo "Usage: $0 files"
	echo
	echo 'Usual parameters: *.c *.h'
	exit 1
fi


for i in $@; do
	sed \
		-e '/Copyright Abandoned.*MySQL.*/,/NO WARRANTY of any kind/c\
/* Copyright Abandoned 1996 TCX DataKonsult AB & Monty Program KB & Detron HB \
This file is public domain and comes with NO WARRANTY of any kind */' \
		-e '/Copyright.*MySQL.*/,/MA 02111/c\
/* Copyright Abandoned 1996 TCX DataKonsult AB & Monty Program KB & Detron HB \
This file is public domain and comes with NO WARRANTY of any kind */' \
		-e '/Copyright (C) .*MySQL.*TCX/,/For a more info/c\
/* Copyright Abandoned 1996 TCX DataKonsult AB & Monty Program KB & Detron HB \
This file is public domain and comes with NO WARRANTY of any kind */' \
		-e '/Copyright (C) .*TCX.*Monty/,/For a more info/c\
/* Copyright Abandoned 1996 TCX DataKonsult AB & Monty Program KB & Detron HB \
This file is public domain and comes with NO WARRANTY of any kind */' \
		-e '/Copyright (C) .... Monty.*/,/be preserved on all copies/c\
/* Copyright Abandoned 1996 TCX DataKonsult AB & Monty Program KB & Detron HB \
This file is public domain and comes with NO WARRANTY of any kind */' \
   < $i > tmp
   cp tmp $i
done
