/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: e4eff8d240a61d705a3f7031bec9496217b9fa71 */

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_opcache_reset, 0, 0, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_opcache_get_status, 0, 0, MAY_BE_ARRAY|MAY_BE_FALSE)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, include_scripts, _IS_BOOL, 0, "true")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_opcache_compile_file, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, filename, IS_STRING, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_opcache_invalidate, 0, 1, _IS_BOOL, 0)
	ZEND_ARG_TYPE_INFO(0, filename, IS_STRING, 0)
	ZEND_ARG_TYPE_INFO_WITH_DEFAULT_VALUE(0, force, _IS_BOOL, 0, "false")
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_MASK_EX(arginfo_opcache_get_configuration, 0, 0, MAY_BE_ARRAY|MAY_BE_FALSE)
ZEND_END_ARG_INFO()

#define arginfo_opcache_is_script_cached arginfo_opcache_compile_file

ZEND_FUNCTION(opcache_reset);
ZEND_FUNCTION(opcache_get_status);
ZEND_FUNCTION(opcache_compile_file);
ZEND_FUNCTION(opcache_invalidate);
ZEND_FUNCTION(opcache_get_configuration);
ZEND_FUNCTION(opcache_is_script_cached);

static const zend_function_entry ext_functions[] = {
	ZEND_FE(opcache_reset, arginfo_opcache_reset)
	ZEND_FE(opcache_get_status, arginfo_opcache_get_status)
	ZEND_FE(opcache_compile_file, arginfo_opcache_compile_file)
	ZEND_FE(opcache_invalidate, arginfo_opcache_invalidate)
	ZEND_FE(opcache_get_configuration, arginfo_opcache_get_configuration)
	ZEND_FE(opcache_is_script_cached, arginfo_opcache_is_script_cached)
	ZEND_FE_END
};

static void register_opcache_symbols(int module_number)
{
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_1", ZEND_DUMP_AFTER_PASS_1, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_2", ZEND_DUMP_AFTER_PASS_2, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_3", ZEND_DUMP_AFTER_PASS_3, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_4", ZEND_DUMP_AFTER_PASS_4, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_5", ZEND_DUMP_AFTER_PASS_5, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_6", ZEND_DUMP_AFTER_PASS_6, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_7", ZEND_DUMP_AFTER_PASS_7, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_8", ZEND_DUMP_AFTER_PASS_8, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_9", ZEND_DUMP_AFTER_PASS_9, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_10", ZEND_DUMP_AFTER_PASS_10, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_11", ZEND_DUMP_AFTER_PASS_11, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_12", ZEND_DUMP_AFTER_PASS_12, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_13", ZEND_DUMP_AFTER_PASS_13, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_PASS_14", ZEND_DUMP_AFTER_PASS_14, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_BEFORE_OPTIMIZER", ZEND_DUMP_BEFORE_OPTIMIZER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_OPTIMIZER", ZEND_DUMP_AFTER_OPTIMIZER, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_BEFORE_BLOCK_PASS", ZEND_DUMP_BEFORE_BLOCK_PASS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_BLOCK_PASS", ZEND_DUMP_AFTER_BLOCK_PASS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_BLOCK_PASS_VARS", ZEND_DUMP_BLOCK_PASS_VARS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_BEFORE_DFA_PASS", ZEND_DUMP_BEFORE_DFA_PASS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_AFTER_DFA_PASS", ZEND_DUMP_AFTER_DFA_PASS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_DFA_CFG", ZEND_DUMP_DFA_CFG, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_DFA_DOMINATORS", ZEND_DUMP_DFA_DOMINATORS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_DFA_LIVENESS", ZEND_DUMP_DFA_LIVENESS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_DFA_PHI", ZEND_DUMP_DFA_PHI, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_DFA_SSA", ZEND_DUMP_DFA_SSA, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_DFA_SSA_VARS", ZEND_DUMP_DFA_SSA_VARS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("OPCACHE_DUMP_SCCP", ZEND_DUMP_SCCP, CONST_PERSISTENT);
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_ASM", ZEND_JIT_DEBUG_ASM, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_SSA", ZEND_JIT_DEBUG_SSA, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_REG_ALLOC", ZEND_JIT_DEBUG_REG_ALLOC, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_ASM_STUBS", ZEND_JIT_DEBUG_ASM_STUBS, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_PERF", ZEND_JIT_DEBUG_PERF, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_PERF_DUMP", ZEND_JIT_DEBUG_PERF_DUMP, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_VTUNE", ZEND_JIT_DEBUG_VTUNE, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_GDB", ZEND_JIT_DEBUG_GDB, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_SIZE", ZEND_JIT_DEBUG_SIZE, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_ASM_ADDR", ZEND_JIT_DEBUG_ASM_ADDR, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_TRACE_START", ZEND_JIT_DEBUG_TRACE_START, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_TRACE_STOP", ZEND_JIT_DEBUG_TRACE_STOP, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_TRACE_COMPILED", ZEND_JIT_DEBUG_TRACE_COMPILED, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_TRACE_EXIT", ZEND_JIT_DEBUG_TRACE_EXIT, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_TRACE_ABORT", ZEND_JIT_DEBUG_TRACE_ABORT, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_TRACE_BLACKLIST", ZEND_JIT_DEBUG_TRACE_BLACKLIST, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_TRACE_BYTECODE", ZEND_JIT_DEBUG_TRACE_BYTECODE, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_TRACE_TSSA", ZEND_JIT_DEBUG_TRACE_TSSA, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_TRACE_EXIT_INFO", ZEND_JIT_DEBUG_TRACE_EXIT_INFO, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_IR_SRC", ZEND_JIT_DEBUG_IR_SRC, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_IR_FINAL", ZEND_JIT_DEBUG_IR_FINAL, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_IR_AFTER_SCCP", ZEND_JIT_DEBUG_IR_AFTER_SCCP, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_IR_AFTER_CFG", ZEND_JIT_DEBUG_IR_AFTER_CFG, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_IR_AFTER_GCM", ZEND_JIT_DEBUG_IR_AFTER_GCM, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_IR_AFTER_SCHEDULE", ZEND_JIT_DEBUG_IR_AFTER_SCHEDULE, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_IR_AFTER_REGS", ZEND_JIT_DEBUG_IR_AFTER_REGS, CONST_PERSISTENT);
#endif
#if defined(HAVE_JIT)
	REGISTER_LONG_CONSTANT("OPCACHE_JIT_DEBUG_IR_CODEGEN", ZEND_JIT_DEBUG_IR_CODEGEN, CONST_PERSISTENT);
#endif
}
