VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provision "shell", path: "https://gist.githubusercontent.com/heiglandreas/10e1c7dd80d6e058faae/raw/ext-ldap-test-provisioner.sh"
end
