env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

freebsd_instance:
  image_family: freebsd-13-0

task:
  name: FREEBSD_DEBUG_NTS
  install_script:
    #- sed -i -e 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf
    #- pkg upgrade -y
    - kldload accf_http
    - pkg install -y autoconf bison gmake re2c icu libiconv png freetype2 enchant2 bzip2 krb5 t1lib gmp tidyp libsodium libzip libxml2 libxslt openssl oniguruma pkgconf webp libavif
  script:
    - ./buildconf -f
    - ./configure --prefix=/usr/local --enable-debug --enable-option-checking=fatal --enable-fpm --with-pdo-sqlite --without-pear --with-bz2 --with-avif --with-jpeg --with-webp --with-freetype --enable-gd --enable-exif --with-zip --with-zlib --enable-soap --enable-xmlreader --with-xsl --with-libxml --enable-shmop --enable-pcntl --enable-mbstring --with-curl --enable-sockets --with-openssl --with-iconv=/usr/local --enable-bcmath --enable-calendar --enable-ftp --with-kerberos --with-ffi --enable-zend-test --enable-intl --with-mhash --with-sodium --enable-werror --with-config-file-path=/etc --with-config-file-scan-dir=/etc/php.d
    - gmake -j2
    - mkdir /etc/php.d
    - gmake install
    - echo opcache.enable_cli=1 > /etc/php.d/opcache.ini
    - echo opcache.protect_memory=1 >> /etc/php.d/opcache.ini
    # Specify opcache.preload_user as we're running as root.
    - echo opcache.preload_user=root >> /etc/php.d/opcache.ini
  tests_script:
    - export SKIP_IO_CAPTURE_TESTS=1
    - export CI_NO_IPV6=1
    - sapi/cli/php run-tests.php -P -q -j2 -g FAIL,XFAIL,BORK,WARN,LEAK,XLEAK,SKIP --offline --show-diff --show-slow 1000 --set-timeout 120 -d zend_extension=opcache.so
