#!/bin/sh

./scripts/preconfig

mv aclocal.m4 aclocal.m4.old 2>/dev/null
aclocal
if cmp aclocal.m4.old aclocal.m4 > /dev/null 2>&1; then
    echo keeping aclocal.m4
    mv aclocal.m4.old aclocal.m4
else
    echo created or modified aclocal.m4
fi

autoheader

automake --add-missing --include-deps

mv configure configure.old 2>/dev/null
autoconf
if cmp configure.old configure > /dev/null 2>&1; then
    echo keeping configure
    mv configure.old configure
else
    echo created or modified configure
fi

cd libzend; ./buildconf

