ignore:
  # bundled libraries
  - "ext/lexbor/lexbor/core"
  - "ext/lexbor/lexbor/css"
  - "ext/lexbor/lexbor/dom"
  - "ext/lexbor/lexbor/encoding"
  - "ext/lexbor/lexbor/html"
  - "ext/lexbor/lexbor/ns"
  - "ext/lexbor/lexbor/ports"
  - "ext/lexbor/lexbor/punycode"
  - "ext/lexbor/lexbor/tag"
  - "ext/lexbor/lexbor/unicode"
  - "ext/lexbor/lexbor/url"
  - "ext/pcre/pcre2lib"
  - "ext/uri/uriparser"
