#! /bin/sh

STD='make -f Makefile.am LEX="flex -L" YACC="bison -y -l" srcdir=.'

(cd Zend && eval "$STD zend-parser.c zend-scanner.c zend-scanner-cc.cc")

files="Makefile main/Makefile ext/standard/Makefile"
sh build/fastgen.sh . yes no $files
touch .deps main/.deps ext/standard/libs.mk

cat > config_vars.mk <<EOF
LEX=flex -L
YACC=bison -y -l
EOF

(cd main && make configuration-parser.c configuration-scanner.c)
(cd ext/standard && make parsedate.c)

rm config_vars.mk .deps ext/standard/libs.mk $files

f=ext/standard/url_scanner_ex.c
cp $f $f.orig
grep -v '#line ' $f.orig > $f
