/* automatically generated by configure */
/* edit configure.ac to change version number */
#define PHP_MAJOR_VERSION 8
#define PHP_MINOR_VERSION 2
#define PHP_RELEASE_VERSION 17
#define PHP_EXTRA_VERSION "-dev"
#define PHP_VERSION "8.2.17-dev"
#define PHP_VERSION_ID 80217
