/* automatically generated by configure */
/* edit configure.ac to change version number */
#define PHP_MAJOR_VERSION 7
#define PHP_MINOR_VERSION 3
#define PHP_RELEASE_VERSION 6
#define PHP_EXTRA_VERSION "-dev"
#define PHP_VERSION "7.3.6-dev"
#define PHP_VERSION_ID 70306
