/* automatically generated by configure */
/* edit configure.in to change version number */
#define PHP_MAJOR_VERSION 4
#define PHP_MINOR_VERSION 4
#define PHP_RELEASE_VERSION 9
#define PHP_EXTRA_VERSION ""
#define PHP_VERSION "4.4.9"
