<?php
$pearweb->addXmlrpcConfig("package.info", unserialize("a:3:{i:0;s:4:\"pkg6\";i:1;s:8:\"releases\";i:2;b:1;}"),     array(
    '2.0b1' =>
        array(
        'id' =>
            "9",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:34:03",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    '1.1' =>
        array(
        'id' =>
            "7",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:37",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    ));
$pearweb->addXmlrpcConfig("package.info", unserialize("a:3:{i:0;s:4:\"pkg2\";i:1;s:8:\"releases\";i:2;b:1;}"),     array(
    '1.1' =>
        array(
        'id' =>
            "3",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:02:56",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    ));
$pearweb->addXmlrpcConfig("package.info", unserialize("a:3:{i:0;s:4:\"pkg3\";i:1;s:8:\"releases\";i:2;b:1;}"),     array(
    '1.4' =>
        array(
        'id' =>
            "11",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:51:31",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "alpha",
        ),
    '1.1' =>
        array(
        'id' =>
            "4",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:06",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    ));
$pearweb->addXmlrpcConfig("package.info", unserialize("a:3:{i:0;s:4:\"pkg4\";i:1;s:8:\"releases\";i:2;b:1;}"),     array(
    '1.1' =>
        array(
        'id' =>
            "5",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:17",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    ));
$pearweb->addXmlrpcConfig("package.info", unserialize("a:3:{i:0;s:4:\"pkg5\";i:1;s:8:\"releases\";i:2;b:1;}"),     array(
    '1.1' =>
        array(
        'id' =>
            "6",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:25",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    ));
$pearweb->addXmlrpcConfig("package.info", unserialize("a:3:{i:0;s:4:\"pkg1\";i:1;s:8:\"releases\";i:2;b:1;}"),     array(
    '2.0b1' =>
        array(
        'id' =>
            "8",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:29:15",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    '1.1' =>
        array(
        'id' =>
            "2",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:02:43",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    ));
$pearweb->addXmlrpcConfig("package.info", unserialize("a:3:{i:0;s:12:\"pkg4AndAHalf\";i:1;s:8:\"releases\";i:2;b:1;}"),     array(
    '1.3' =>
        array(
        'id' =>
            "10",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:50:05",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    ));
$pearweb->addXmlrpcConfig("package.info",     array(
    0 =>
        "noreleases",
    1 =>
        "releases",
    2 =>
        true,
    ),     array(
    ));
$pearweb->addXmlrpcConfig("package.info",     array(
    0 =>
        "pkg1",
    1 =>
        "releases",
    2 =>
        true,
    ),     array(
    '2.0b1' =>
        array(
        'id' =>
            "8",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:29:15",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    '1.1' =>
        array(
        'id' =>
            "2",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:02:43",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    ));
$pearweb->addXmlrpcConfig("package.info",     array(
    0 =>
        "stabilitytoolow",
    1 =>
        "releases",
    2 =>
        true,
    ),     array(
    '3.0dev' =>
        array(
        'id' =>
            "23",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 00:27:38",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "devel",
        ),
    '2.0a1' =>
        array(
        'id' =>
            "22",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 00:27:19",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "alpha",
        ),
    '1.0b1' =>
        array(
        'id' =>
            "21",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 00:26:42",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    '0.6beta' =>
        array(
        'id' =>
            "20",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 00:26:36",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    '0.5' =>
        array(
        'id' =>
            "19",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 00:26:28",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "alpha",
        ),
    '0.3' =>
        array(
        'id' =>
            "18",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 00:26:21",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "devel",
        ),
    ));
$pearweb->addXmlrpcConfig("package.info",     array(
    0 =>
        "pkg6",
    1 =>
        "releases",
    2 =>
        true,
    ),     array(
    '2.0b1' =>
        array(
        'id' =>
            "9",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:34:03",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    '1.1' =>
        array(
        'id' =>
            "7",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:37",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    ));
$pearweb->addXmlrpcConfig("package.info",     array(
    0 =>
        "depnoreleases",
    1 =>
        "releases",
    2 =>
        true,
    ),     array(
    '1.0' =>
        array(
        'id' =>
            "24",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 17:10:42",
        'releasenotes' =>
            "dependency has no releases test",
        'state' =>
            "beta",
        ),
    ));
$pearweb->addXmlrpcConfig("package.info",     array(
    0 =>
        "depunstable",
    1 =>
        "releases",
    2 =>
        true,
    ),     array(
    '1.0' =>
        array(
        'id' =>
            "26",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 17:32:38",
        'releasenotes' =>
            "dependency stability is too low",
        'state' =>
            "stable",
        ),
    ));
$pearweb->addXmlrpcConfig("package.info",     array(
    0 =>
        "stabilitytoolow",
    ),     array(
    'packageid' =>
        "9",
    'name' =>
        "stabilitytoolow",
    'type' =>
        "pear",
    'categoryid' =>
        "1",
    'category' =>
        "Test",
    'stable' =>
        "3.0dev",
    'license' =>
        "PHP License",
    'summary' =>
        "required test for PEAR_Installer",
    'homepage' =>
        "",
    'description' =>
        "fake package",
    'cvs_link' =>
        "",
    'doc_link' =>
        "",
    'releases' =>
        array(
        '3.0dev' =>
            array(
            'id' =>
                "23",
            'doneby' =>
                "cellog",
            'license' =>
                "",
            'summary' =>
                "",
            'description' =>
                "",
            'releasedate' =>
                "2003-12-06 00:27:38",
            'releasenotes' =>
                "required dependency test",
            'state' =>
                "devel",
            'deps' =>
                array(
                0 =>
                    array(
                    'type' =>
                        "pkg",
                    'relation' =>
                        "ge",
                    'version' =>
                        "1.0",
                    'name' =>
                        "pkg6",
                    'optional' =>
                        "0",
                    ),
                ),
            ),
        '2.0a1' =>
            array(
            'id' =>
                "22",
            'doneby' =>
                "cellog",
            'license' =>
                "",
            'summary' =>
                "",
            'description' =>
                "",
            'releasedate' =>
                "2003-12-06 00:27:19",
            'releasenotes' =>
                "required dependency test",
            'state' =>
                "alpha",
            'deps' =>
                array(
                0 =>
                    array(
                    'type' =>
                        "pkg",
                    'relation' =>
                        "ge",
                    'version' =>
                        "1.0",
                    'name' =>
                        "pkg6",
                    'optional' =>
                        "0",
                    ),
                ),
            ),
        '1.0b1' =>
            array(
            'id' =>
                "21",
            'doneby' =>
                "cellog",
            'license' =>
                "",
            'summary' =>
                "",
            'description' =>
                "",
            'releasedate' =>
                "2003-12-06 00:26:42",
            'releasenotes' =>
                "required dependency test",
            'state' =>
                "beta",
            'deps' =>
                array(
                0 =>
                    array(
                    'type' =>
                        "pkg",
                    'relation' =>
                        "ge",
                    'version' =>
                        "1.0",
                    'name' =>
                        "pkg6",
                    'optional' =>
                        "0",
                    ),
                ),
            ),
        '0.6beta' =>
            array(
            'id' =>
                "20",
            'doneby' =>
                "cellog",
            'license' =>
                "",
            'summary' =>
                "",
            'description' =>
                "",
            'releasedate' =>
                "2003-12-06 00:26:36",
            'releasenotes' =>
                "required dependency test",
            'state' =>
                "beta",
            'deps' =>
                array(
                0 =>
                    array(
                    'type' =>
                        "pkg",
                    'relation' =>
                        "ge",
                    'version' =>
                        "1.0",
                    'name' =>
                        "pkg6",
                    'optional' =>
                        "0",
                    ),
                ),
            ),
        '0.5' =>
            array(
            'id' =>
                "19",
            'doneby' =>
                "cellog",
            'license' =>
                "",
            'summary' =>
                "",
            'description' =>
                "",
            'releasedate' =>
                "2003-12-06 00:26:28",
            'releasenotes' =>
                "required dependency test",
            'state' =>
                "alpha",
            'deps' =>
                array(
                0 =>
                    array(
                    'type' =>
                        "pkg",
                    'relation' =>
                        "ge",
                    'version' =>
                        "1.0",
                    'name' =>
                        "pkg6",
                    'optional' =>
                        "0",
                    ),
                ),
            ),
        '0.3' =>
            array(
            'id' =>
                "18",
            'doneby' =>
                "cellog",
            'license' =>
                "",
            'summary' =>
                "",
            'description' =>
                "",
            'releasedate' =>
                "2003-12-06 00:26:21",
            'releasenotes' =>
                "required dependency test",
            'state' =>
                "devel",
            'deps' =>
                array(
                0 =>
                    array(
                    'type' =>
                        "pkg",
                    'relation' =>
                        "ge",
                    'version' =>
                        "1.0",
                    'name' =>
                        "pkg6",
                    'optional' =>
                        "0",
                    ),
                ),
            ),
        ),
    'notes' =>
        array(
        ),
    ));
$pearweb->addXmlrpcConfig("package.info",     array(
    0 =>
        "depnoreleases",
    ),     array(
    'packageid' =>
        "10",
    'name' =>
        "depnoreleases",
    'type' =>
        "pear",
    'categoryid' =>
        "1",
    'category' =>
        "Test",
    'stable' =>
        "1.0",
    'license' =>
        "PHP License",
    'summary' =>
        "required test for PEAR_Installer",
    'homepage' =>
        "",
    'description' =>
        "fake package",
    'cvs_link' =>
        "",
    'doc_link' =>
        "",
    'releases' =>
        array(
        '1.0' =>
            array(
            'id' =>
                "24",
            'doneby' =>
                "cellog",
            'license' =>
                "",
            'summary' =>
                "",
            'description' =>
                "",
            'releasedate' =>
                "2003-12-06 17:10:42",
            'releasenotes' =>
                "dependency has no releases test",
            'state' =>
                "beta",
            'deps' =>
                array(
                0 =>
                    array(
                    'type' =>
                        "pkg",
                    'relation' =>
                        "ge",
                    'version' =>
                        "1.0",
                    'name' =>
                        "noreleases",
                    'optional' =>
                        "0",
                    ),
                ),
            ),
        ),
    'notes' =>
        array(
        ),
    ));
$pearweb->addXmlrpcConfig("package.info",     array(
    0 =>
        "depunstable",
    ),     array(
    'packageid' =>
        "11",
    'name' =>
        "depunstable",
    'type' =>
        "pear",
    'categoryid' =>
        "1",
    'category' =>
        "Test",
    'stable' =>
        "1.0",
    'license' =>
        "PHP License",
    'summary' =>
        "required test for PEAR_Installer",
    'homepage' =>
        "",
    'description' =>
        "fake package",
    'cvs_link' =>
        "",
    'doc_link' =>
        "",
    'releases' =>
        array(
        '1.0' =>
            array(
            'id' =>
                "26",
            'doneby' =>
                "cellog",
            'license' =>
                "",
            'summary' =>
                "",
            'description' =>
                "",
            'releasedate' =>
                "2003-12-06 17:32:38",
            'releasenotes' =>
                "dependency stability is too low",
            'state' =>
                "stable",
            'deps' =>
                array(
                0 =>
                    array(
                    'type' =>
                        "pkg",
                    'relation' =>
                        "ge",
                    'version' =>
                        "1.0b1",
                    'name' =>
                        "stabilitytoolow",
                    'optional' =>
                        "0",
                    ),
                ),
            ),
        ),
    'notes' =>
        array(
        ),
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "noreleases",
    2 =>
        array(
        0 =>
            "stable",
        ),
    ),     false);
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg1",
    2 =>
        "1976.9.2",
    ),     array(
    0 =>
        "2.0b1",
    1 =>
        array(
        'id' =>
            "8",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:29:15",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg1",
    2 =>
        "snapshot",
    ),     array(
    0 =>
        "2.0b1",
    1 =>
        array(
        'id' =>
            "8",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:29:15",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg1",
    2 =>
        "burgerking",
    ),     array(
    0 =>
        "2.0b1",
    1 =>
        array(
        'id' =>
            "8",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:29:15",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "stabilitytoolow",
    2 =>
        array(
        0 =>
            "stable",
        ),
    ),     array(
    0 =>
        "3.0dev",
    1 =>
        array(
        'id' =>
            "23",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 00:27:38",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "devel",
        ),
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "stabilitytoolow",
    2 =>
        "3.0dev",
    ),     array(
    0 =>
        "3.0dev",
    1 =>
        array(
        'id' =>
            "23",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 00:27:38",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "devel",
        ),
    2 =>
        "http://pear.Chiara/get/stabilitytoolow-3.0dev",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "stabilitytoolow",
    2 =>
        array(
        0 =>
            "beta",
        1 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.0b1",
    1 =>
        array(
        'id' =>
            "21",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 00:26:42",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    2 =>
        "http://pear.Chiara/get/stabilitytoolow-1.0b1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "stabilitytoolow",
    2 =>
        array(
        0 =>
            "alpha",
        1 =>
            "beta",
        2 =>
            "stable",
        ),
    ),     array(
    0 =>
        "2.0a1",
    1 =>
        array(
        'id' =>
            "22",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 00:27:19",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "alpha",
        ),
    2 =>
        "http://pear.Chiara/get/stabilitytoolow-2.0a1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "stabilitytoolow",
    2 =>
        array(
        0 =>
            "devel",
        1 =>
            "alpha",
        2 =>
            "beta",
        3 =>
            "stable",
        ),
    ),     array(
    0 =>
        "3.0dev",
    1 =>
        array(
        'id' =>
            "23",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 00:27:38",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "devel",
        ),
    2 =>
        "http://pear.Chiara/get/stabilitytoolow-3.0dev",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg6",
    2 =>
        array(
        0 =>
            "devel",
        1 =>
            "alpha",
        2 =>
            "beta",
        3 =>
            "stable",
        ),
    ),     array(
    0 =>
        "2.0b1",
    1 =>
        array(
        'id' =>
            "9",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:34:03",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    2 =>
        "http://pear.Chiara/get/pkg6-2.0b1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg6",
    2 =>
        "1.1",
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "7",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:37",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg6-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "depnoreleases",
    2 =>
        array(
        0 =>
            "devel",
        1 =>
            "alpha",
        2 =>
            "beta",
        3 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.0",
    1 =>
        array(
        'id' =>
            "24",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 17:10:42",
        'releasenotes' =>
            "dependency has no releases test",
        'state' =>
            "beta",
        ),
    2 =>
        "http://pear.Chiara/get/depnoreleases-1.0",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "depunstable",
    2 =>
        array(
        0 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.0",
    1 =>
        array(
        'id' =>
            "26",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-06 17:32:38",
        'releasenotes' =>
            "dependency stability is too low",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/depunstable-1.0",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg6",
    2 =>
        array(
        0 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "7",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:37",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg6-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg6",
    2 =>
        "stable",
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "7",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:37",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg6-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg6",
    2 =>
        "beta",
    ),     array(
    0 =>
        "2.0b1",
    1 =>
        array(
        'id' =>
            "9",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:34:03",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    2 =>
        "http://pear.Chiara/get/pkg6-2.0b1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg6",
    2 =>
        array(
        0 =>
            "beta",
        1 =>
            "stable",
        ),
    ),     array(
    0 =>
        "2.0b1",
    1 =>
        array(
        'id' =>
            "9",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:34:03",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    2 =>
        "http://pear.Chiara/get/pkg6-2.0b1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg2",
    2 =>
        array(
        0 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "3",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:02:56",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg2-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg3",
    2 =>
        array(
        0 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "4",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:06",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg3-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg4",
    2 =>
        array(
        0 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "5",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:17",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg4-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg5",
    2 =>
        array(
        0 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "6",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:25",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg5-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg1",
    2 =>
        array(
        0 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "2",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:02:43",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg1-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg1",
    2 =>
        array(
        0 =>
            "beta",
        1 =>
            "stable",
        ),
    ),     array(
    0 =>
        "2.0b1",
    1 =>
        array(
        'id' =>
            "8",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:29:15",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    2 =>
        "http://pear.Chiara/get/pkg1-2.0b1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg2",
    2 =>
        array(
        0 =>
            "beta",
        1 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "3",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:02:56",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg2-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg3",
    2 =>
        array(
        0 =>
            "beta",
        1 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "4",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:06",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg3-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg4",
    2 =>
        array(
        0 =>
            "beta",
        1 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "5",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:17",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg4-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg5",
    2 =>
        array(
        0 =>
            "beta",
        1 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "6",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:25",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg5-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg1",
    2 =>
        array(
        0 =>
            "alpha",
        1 =>
            "beta",
        2 =>
            "stable",
        ),
    ),     array(
    0 =>
        "2.0b1",
    1 =>
        array(
        'id' =>
            "8",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:29:15",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    2 =>
        "http://pear.Chiara/get/pkg1-2.0b1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg2",
    2 =>
        array(
        0 =>
            "alpha",
        1 =>
            "beta",
        2 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "3",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:02:56",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg2-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg3",
    2 =>
        array(
        0 =>
            "alpha",
        1 =>
            "beta",
        2 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.4",
    1 =>
        array(
        'id' =>
            "11",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:51:31",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "alpha",
        ),
    2 =>
        "http://pear.Chiara/get/pkg3-1.4",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg4AndAHalf",
    2 =>
        array(
        0 =>
            "alpha",
        1 =>
            "beta",
        2 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.3",
    1 =>
        array(
        'id' =>
            "10",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:50:05",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg4AndAHalf-1.3",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg4",
    2 =>
        array(
        0 =>
            "alpha",
        1 =>
            "beta",
        2 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "5",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:17",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg4-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg5",
    2 =>
        array(
        0 =>
            "alpha",
        1 =>
            "beta",
        2 =>
            "stable",
        ),
    ),     array(
    0 =>
        "1.1",
    1 =>
        array(
        'id' =>
            "6",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 17:03:25",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "stable",
        ),
    2 =>
        "http://pear.Chiara/get/pkg5-1.1",
    ));
$pearweb->addXmlrpcConfig("package.getDownloadURL",     array(
    0 =>
        "pear",
    1 =>
        "pkg6",
    2 =>
        array(
        0 =>
            "alpha",
        1 =>
            "beta",
        2 =>
            "stable",
        ),
    ),     array(
    0 =>
        "2.0b1",
    1 =>
        array(
        'id' =>
            "9",
        'doneby' =>
            "cellog",
        'license' =>
            "",
        'summary' =>
            "",
        'description' =>
            "",
        'releasedate' =>
            "2003-12-03 18:34:03",
        'releasenotes' =>
            "required dependency test",
        'state' =>
            "beta",
        ),
    2 =>
        "http://pear.Chiara/get/pkg6-2.0b1",
    ));

$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg6-1.1.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR . 'test-pkg6' . DIRECTORY_SEPARATOR . 'pkg6-1.1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg6-1.1",
    dirname(__FILE__) . DIRECTORY_SEPARATOR . 'test-pkg6' . DIRECTORY_SEPARATOR . 'pkg6-1.1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg6-2.0b1",
    dirname(__FILE__) . DIRECTORY_SEPARATOR . 'test-pkg6' . DIRECTORY_SEPARATOR . 'pkg6-2.0b1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg6-2.0b1.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR . 'test-pkg6' . DIRECTORY_SEPARATOR . 'pkg6-2.0b1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg2-1.1",
    dirname(__FILE__) . DIRECTORY_SEPARATOR . 'pkg2-1.1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg2-1.1.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR . 'pkg2-1.1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg3-1.1",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'pkg3-1.1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg3-1.1.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'pkg3-1.1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg4-1.1",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'pkg4-1.1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg4-1.1.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'pkg4-1.1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg5-1.1",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'pkg5-1.1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg5-1.1.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'pkg5-1.1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg1-1.1",
    dirname(__FILE__) . DIRECTORY_SEPARATOR . 'pkg1-1.1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg1-1.1.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR . 'pkg1-1.1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg1-2.0b1",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'pkg1-2.0b1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg1-2.0b1.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'pkg1-2.0b1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg3-1.4",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'pkg3-1.4.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg3-1.4.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'pkg3-1.4.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg4AndAHalf-1.3",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'pkg4AndAHalf-1.3.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/pkg4AndAHalf-1.3.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'pkg4AndAHalf-1.3.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-0.3",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-0.3.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-0.3.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-0.3.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-0.5",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-0.5.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-0.5.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-0.5.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-0.6beta",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-0.6beta.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-0.6beta.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-0.6beta.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-1.0b1",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-1.0b1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-1.0b1.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-1.0b1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-2.0a1",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-2.0a1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-2.0a1.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-2.0a1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-2.0b1",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-2.0b1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-2.0b1.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-2.0b1.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-2.0dev",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-2.0dev.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-2.0dev.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-2.0dev.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-3.0dev",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-3.0dev.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-3.0dev.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-3.0dev.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/depnoreleases-1.0",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'depnoreleases-1.0.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/depnoreleases-1.0.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'depnoreleases-1.0.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/depunstable-1.0",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'depunstable-1.0.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/depunstable-1.0.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'depunstable-1.0.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-3.0dev.tgz');
$pearweb->addHtmlConfig("http://pear.Chiara/get/stabilitytoolow-3.0dev.tgz",
    dirname(__FILE__) . DIRECTORY_SEPARATOR .  'stabilitytoolow-3.0dev.tgz');
?>