/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: b6056170a5c8f1a9582c5eef9261a0bd02f7a7e1 */

static void register_openssl_pwhash_symbols(int module_number)
{
#if defined(HAVE_OPENSSL_ARGON2)
	REGISTER_STRING_CONSTANT("PASSWORD_ARGON2I", "argon2i", CONST_PERSISTENT);
#endif
#if defined(HAVE_OPENSSL_ARGON2)
	REGISTER_STRING_CONSTANT("PASSWORD_ARGON2ID", "argon2id", CONST_PERSISTENT);
#endif
#if defined(HAVE_OPENSSL_ARGON2)
	REGISTER_LONG_CONSTANT("PASSWORD_ARGON2_DEFAULT_MEMORY_COST", PHP_OPENSSL_PWHASH_MEMLIMIT, CONST_PERSISTENT);
#endif
#if defined(HAVE_OPENSSL_ARGON2)
	REGISTER_LONG_CONSTANT("PASSWORD_ARGON2_DEFAULT_TIME_COST", PHP_OPENSSL_PWHASH_ITERLIMIT, CONST_PERSISTENT);
#endif
#if defined(HAVE_OPENSSL_ARGON2)
	REGISTER_LONG_CONSTANT("PASSWORD_ARGON2_DEFAULT_THREADS", PHP_OPENSSL_PWHASH_THREADS, CONST_PERSISTENT);
#endif
#if defined(HAVE_OPENSSL_ARGON2)
	REGISTER_STRING_CONSTANT("PASSWORD_ARGON2_PROVIDER", "openssl", CONST_PERSISTENT);
#endif
}
