/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 6d501df8b3a9098e1656e5128d39603a38a07eca */

static void register_openssl_pwhash_symbols(int module_number)
{
#if PHP_OPENSSL_API_VERSION >= 0x30200
	REGISTER_STRING_CONSTANT("PASSWORD_ARGON2I", "argon2i", CONST_PERSISTENT);
#endif
#if PHP_OPENSSL_API_VERSION >= 0x30200
	REGISTER_STRING_CONSTANT("PASSWORD_ARGON2ID", "argon2id", CONST_PERSISTENT);
#endif
#if PHP_OPENSSL_API_VERSION >= 0x30200
	REGISTER_LONG_CONSTANT("PASSWORD_ARGON2_DEFAULT_MEMORY_COST", PHP_OPENSSL_PWHASH_MEMLIMIT, CONST_PERSISTENT);
#endif
#if PHP_OPENSSL_API_VERSION >= 0x30200
	REGISTER_LONG_CONSTANT("PASSWORD_ARGON2_DEFAULT_TIME_COST", PHP_OPENSSL_PWHASH_OPSLIMIT, CONST_PERSISTENT);
#endif
#if PHP_OPENSSL_API_VERSION >= 0x30200
	REGISTER_LONG_CONSTANT("PASSWORD_ARGON2_DEFAULT_THREADS", PHP_OPENSSL_PWHASH_THREADS, CONST_PERSISTENT);
#endif
#if PHP_OPENSSL_API_VERSION >= 0x30200
	REGISTER_STRING_CONSTANT("PASSWORD_ARGON2_PROVIDER", "openssl", CONST_PERSISTENT);
#endif
}
