#!/bin/sh

case "$1" in
--copy)
	automake_flags=--copy
	shift
;;
esac

libtoolize --force --automake $automake_flags

mv aclocal.m4 aclocal.m4.old 2>/dev/null
aclocal
if cmp aclocal.m4.old aclocal.m4 > /dev/null 2>&1; then
    echo "buildconf: keeping ${1}aclocal.m4"
    mv aclocal.m4.old aclocal.m4
else
    echo "buildconf: created or modified ${1}aclocal.m4"
fi

autoheader

automake --add-missing --include-deps $automake_flags

mv configure configure.old 2>/dev/null
autoconf
if cmp configure.old configure > /dev/null 2>&1; then
    echo "buildconf: keeping ${1}configure"
    mv configure.old configure
else
    echo "buildconf: created or modified ${1}configure"
fi
