/* Generated by re2c 1.0.3 */
#line 1 "Zend/zend_ini_scanner.l"
/*
   +----------------------------------------------------------------------+
   | Zend Engine                                                          |
   +----------------------------------------------------------------------+
   | Copyright (c) 1998-2018 Zend Technologies Ltd. (http://www.zend.com) |
   +----------------------------------------------------------------------+
   | This source file is subject to version 2.00 of the Zend license,     |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | http://www.zend.com/license/2_00.txt.                                |
   | If you did not receive a copy of the Zend license and are unable to  |
   | obtain it through the world-wide-web, please send a note to          |
   | license@zend.com so we can mail you a copy immediately.              |
   +----------------------------------------------------------------------+
   | Authors: Zeev Suraski <zeev@zend.com>                                |
   |          Jani Taskinen <jani@php.net>                                |
   |          Marcus Boerger <helly@php.net>                              |
   |          Nuno Lopes <nlopess@php.net>                                |
   |          Scott MacVicar <scottmac@php.net>                           |
   +----------------------------------------------------------------------+
*/

#include <errno.h>
#include "zend.h"
#include "zend_API.h"
#include "zend_globals.h"
#include <zend_ini_parser.h>
#include "zend_ini_scanner.h"

#ifdef YYDEBUG
#undef YYDEBUG
#endif

#if 0
# define YYDEBUG(s, c) printf("state: %d char: %c\n", s, c)
#else
# define YYDEBUG(s, c)
#endif

#include "zend_ini_scanner_defs.h"

#define YYCTYPE   unsigned char
/* allow the scanner to read one null byte after the end of the string (from ZEND_MMAP_AHEAD)
 * so that if will be able to terminate to match the current token (e.g. non-enclosed string) */
#define YYFILL(n) { if (YYCURSOR > YYLIMIT) return 0; }
#define YYCURSOR  SCNG(yy_cursor)
#define YYLIMIT   SCNG(yy_limit)
#define YYMARKER  SCNG(yy_marker)

#define YYGETCONDITION()  SCNG(yy_state)
#define YYSETCONDITION(s) SCNG(yy_state) = s

#define STATE(name)  yyc##name

/* emulate flex constructs */
#define BEGIN(state) YYSETCONDITION(STATE(state))
#define YYSTATE      YYGETCONDITION()
#define yytext       ((char*)SCNG(yy_text))
#define yyleng       SCNG(yy_leng)
#define yyless(x)    do {	YYCURSOR = (unsigned char*)yytext + x; \
							yyleng   = (unsigned int)x; } while(0)

/* #define yymore()     goto yymore_restart */

/* perform sanity check. If this message is triggered you should
   increase the ZEND_MMAP_AHEAD value in the zend_streams.h file */
#define YYMAXFILL 6

#if ZEND_MMAP_AHEAD < (YYMAXFILL + 1)
# error ZEND_MMAP_AHEAD should be greater than YYMAXFILL
#endif


/* How it works (for the core ini directives):
 * ===========================================
 *
 * 1. Scanner scans file for tokens and passes them to parser.
 * 2. Parser parses the tokens and passes the name/value pairs to the callback
 *    function which stores them in the configuration hash table.
 * 3. Later REGISTER_INI_ENTRIES() is called which triggers the actual
 *    registering of ini entries and uses zend_get_configuration_directive()
 *    to fetch the previously stored name/value pair from configuration hash table
 *    and registers the static ini entries which match the name to the value
 *    into EG(ini_directives) hash table.
 * 4. PATH section entries are used per-request from down to top, each overriding
 *    previous if one exists. zend_alter_ini_entry() is called for each entry.
 *    Settings in PATH section are ZEND_INI_SYSTEM accessible and thus mimics the
 *    php_admin_* directives used within Apache httpd.conf when PHP is compiled as
 *    module for Apache.
 * 5. User defined ini files (like .htaccess for apache) are parsed for each request and
 *    stored in separate hash defined by SAPI.
 */

/* TODO: (ordered by importance :-)
 * ===============================================================================
 *
 *  - Separate constant lookup totally from plain strings (using CONSTANT pattern)
 *  - Add #if .. #else .. #endif and ==, !=, <, > , <=, >= operators
 *  - Add #include "some.ini"
 *  - Allow variables to refer to options also when using parse_ini_file()
 *
 */

/* Globals Macros */
#define SCNG	INI_SCNG
#ifdef ZTS
ZEND_API ts_rsrc_id ini_scanner_globals_id;
#else
ZEND_API zend_ini_scanner_globals ini_scanner_globals;
#endif

#define ZEND_SYSTEM_INI CG(ini_parser_unbuffered_errors)

/* Eat leading whitespace */
#define EAT_LEADING_WHITESPACE()                     \
	while (yyleng) {                                 \
		if (yytext[0] == ' ' || yytext[0] == '\t') { \
			SCNG(yy_text)++;                         \
			yyleng--;                                \
		} else {                                     \
			break;                                   \
		}                                            \
	}

/* Eat trailing whitespace + extra char */
#define EAT_TRAILING_WHITESPACE_EX(ch)              \
	while (yyleng && (                              \
		(ch != 'X' && yytext[yyleng - 1] ==  ch) || \
		yytext[yyleng - 1] == '\n' ||               \
		yytext[yyleng - 1] == '\r' ||               \
		yytext[yyleng - 1] == '\t' ||               \
		yytext[yyleng - 1] == ' ')                  \
	) {                                             \
		yyleng--;                                   \
	}

/* Eat trailing whitespace */
#define EAT_TRAILING_WHITESPACE()	EAT_TRAILING_WHITESPACE_EX('X')

#define zend_ini_copy_value(retval, str, len)	\
	ZVAL_NEW_STR(retval, zend_string_init(str, len, ZEND_SYSTEM_INI))


#define RETURN_TOKEN(type, str, len) {                       \
	if (SCNG(scanner_mode) == ZEND_INI_SCANNER_TYPED) {      \
		zend_ini_copy_typed_value(ini_lval, type, str, len); \
	} else {                                                 \
		zend_ini_copy_value(ini_lval, str, len);             \
	}                                                        \
	return type;                                             \
}

static inline int convert_to_number(zval *retval, const char *str, const int str_len)
{
	zend_uchar type;
	int overflow;
	zend_long lval;
	double dval;

	if ((type = is_numeric_string_ex(str, str_len, &lval, &dval, 0, &overflow)) != 0) {
		if (type == IS_LONG) {
			ZVAL_LONG(retval, lval);
			return SUCCESS;
		} else if (type == IS_DOUBLE && !overflow) {
			ZVAL_DOUBLE(retval, dval);
			return SUCCESS;
		}
	}

	return FAILURE;
}

static void zend_ini_copy_typed_value(zval *retval, const int type, const char *str, int len)
{
	switch (type) {
		case BOOL_FALSE:
		case BOOL_TRUE:
			ZVAL_BOOL(retval, type == BOOL_TRUE);
			break;

		case NULL_NULL:
			ZVAL_NULL(retval);
			break;

		case TC_NUMBER:
			if (convert_to_number(retval, str, len) == SUCCESS) {
				break;
			}
			/* intentional fall-through */
		default:
			zend_ini_copy_value(retval, str, len);
	}
}

static void _yy_push_state(int new_state)
{
	zend_stack_push(&SCNG(state_stack), (void *) &YYGETCONDITION());
	YYSETCONDITION(new_state);
}

#define yy_push_state(state_and_tsrm) _yy_push_state(yyc##state_and_tsrm)

static void yy_pop_state(void)
{
	int *stack_state = zend_stack_top(&SCNG(state_stack));
	YYSETCONDITION(*stack_state);
	zend_stack_del_top(&SCNG(state_stack));
}

static void yy_scan_buffer(char *str, unsigned int len)
{
	YYCURSOR = (YYCTYPE*)str;
	SCNG(yy_start) = YYCURSOR;
	YYLIMIT  = YYCURSOR + len;
}

#define ini_filename SCNG(filename)

/* {{{ init_ini_scanner()
*/
static int init_ini_scanner(int scanner_mode, zend_file_handle *fh)
{
	/* Sanity check */
	if (scanner_mode != ZEND_INI_SCANNER_NORMAL && scanner_mode != ZEND_INI_SCANNER_RAW && scanner_mode != ZEND_INI_SCANNER_TYPED) {
		zend_error(E_WARNING, "Invalid scanner mode");
		return FAILURE;
	}

	SCNG(lineno) = 1;
	SCNG(scanner_mode) = scanner_mode;
	SCNG(yy_in) = fh;

	if (fh != NULL) {
		ini_filename = zend_strndup(fh->filename, strlen(fh->filename));
	} else {
		ini_filename = NULL;
	}

	zend_stack_init(&SCNG(state_stack), sizeof(int));
	BEGIN(INITIAL);

	return SUCCESS;
}
/* }}} */

/* {{{ shutdown_ini_scanner()
*/
void shutdown_ini_scanner(void)
{
	zend_stack_destroy(&SCNG(state_stack));
	if (ini_filename) {
		free(ini_filename);
	}
}
/* }}} */

/* {{{ zend_ini_scanner_get_lineno()
*/
ZEND_COLD int zend_ini_scanner_get_lineno(void)
{
	return SCNG(lineno);
}
/* }}} */

/* {{{ zend_ini_scanner_get_filename()
*/
ZEND_COLD char *zend_ini_scanner_get_filename(void)
{
	return ini_filename ? ini_filename : "Unknown";
}
/* }}} */

/* {{{ zend_ini_open_file_for_scanning()
*/
int zend_ini_open_file_for_scanning(zend_file_handle *fh, int scanner_mode)
{
	char *buf;
	size_t size;

	if (zend_stream_fixup(fh, &buf, &size) == FAILURE) {
		return FAILURE;
	}

	if (init_ini_scanner(scanner_mode, fh) == FAILURE) {
		zend_file_handle_dtor(fh);
		return FAILURE;
	}

	yy_scan_buffer(buf, (unsigned int)size);

	return SUCCESS;
}
/* }}} */

/* {{{ zend_ini_prepare_string_for_scanning()
*/
int zend_ini_prepare_string_for_scanning(char *str, int scanner_mode)
{
	int len = (int)strlen(str);

	if (init_ini_scanner(scanner_mode, NULL) == FAILURE) {
		return FAILURE;
	}

	yy_scan_buffer(str, len);

	return SUCCESS;
}
/* }}} */

/* {{{ zend_ini_escape_string()
 */
static void zend_ini_escape_string(zval *lval, char *str, int len, char quote_type)
{
	register char *s, *t;
	char *end;

	zend_ini_copy_value(lval, str, len);

	/* convert escape sequences */
	s = t = Z_STRVAL_P(lval);
	end = s + Z_STRLEN_P(lval);

	while (s < end) {
		if (*s == '\\') {
			s++;
			if (s >= end) {
				*t++ = '\\';
				continue;
			}
			switch (*s) {
				case '"':
					if (*s != quote_type) {
						*t++ = '\\';
						*t++ = *s;
						break;
					}
				case '\\':
				case '$':
					*t++ = *s;
					Z_STRLEN_P(lval)--;
					break;
				default:
					*t++ = '\\';
					*t++ = *s;
					break;
			}
		} else {
			*t++ = *s;
		}
		if (*s == '\n' || (*s == '\r' && (*(s+1) != '\n'))) {
			SCNG(lineno)++;
		}
		s++;
	}
	*t = 0;
}
/* }}} */

int ini_lex(zval *ini_lval)
{
restart:
	SCNG(yy_text) = YYCURSOR;

/* yymore_restart: */
	/* detect EOF */
	if (YYCURSOR >= YYLIMIT) {
		if (YYSTATE == STATE(ST_VALUE) || YYSTATE == STATE(ST_RAW)) {
			BEGIN(INITIAL);
			return END_OF_LINE;
		}
		return 0;
	}

	/* Eat any UTF-8 BOM we find in the first 3 bytes */
	if (YYCURSOR == SCNG(yy_start) && YYCURSOR + 3 < YYLIMIT) {
		if (memcmp(YYCURSOR, "\xef\xbb\xbf", 3) == 0) {
			YYCURSOR += 3;
			goto restart;
		}
	}

#line 386 "Zend/zend_ini_scanner.c"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if (YYGETCONDITION() < 4) {
		if (YYGETCONDITION() < 2) {
			if (YYGETCONDITION() < 1) {
				goto yyc_INITIAL;
			} else {
				goto yyc_ST_OFFSET;
			}
		} else {
			if (YYGETCONDITION() < 3) {
				goto yyc_ST_SECTION_VALUE;
			} else {
				goto yyc_ST_VALUE;
			}
		}
	} else {
		if (YYGETCONDITION() < 6) {
			if (YYGETCONDITION() < 5) {
				goto yyc_ST_SECTION_RAW;
			} else {
				goto yyc_ST_DOUBLE_QUOTES;
			}
		} else {
			if (YYGETCONDITION() < 7) {
				goto yyc_ST_VARNAME;
			} else {
				goto yyc_ST_RAW;
			}
		}
	}
/* *********************************** */
yyc_INITIAL:
	{
		static const unsigned char yybm[] = {
			128, 144, 144, 144, 144, 144, 144, 144, 
			144, 160,   0, 144, 144,   0, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			240, 128, 128, 144, 128, 144, 128, 144, 
			128, 128, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 128, 144, 128, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 128, 144, 144, 128, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 128, 128, 128, 128, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
			144, 144, 144, 144, 144, 144, 144, 144, 
		};
		YYDEBUG(1, *YYCURSOR);
		YYFILL(5);
		yych = *YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy14;
		}
		if (yych <= 'M') {
			if (yych <= '$') {
				if (yych <= '\f') {
					if (yych <= 0x08) {
						if (yych >= 0x01) goto yy5;
					} else {
						if (yych <= '\t') goto yy8;
						if (yych <= '\n') goto yy11;
						goto yy5;
					}
				} else {
					if (yych <= 0x1F) {
						if (yych <= '\r') goto yy13;
						goto yy5;
					} else {
						if (yych == '#') goto yy5;
						goto yy16;
					}
				}
			} else {
				if (yych <= ':') {
					if (yych <= '&') {
						if (yych <= '%') goto yy5;
						goto yy16;
					} else {
						if (yych <= '\'') goto yy5;
						if (yych <= ')') goto yy16;
						goto yy5;
					}
				} else {
					if (yych <= '=') {
						if (yych <= ';') goto yy18;
						if (yych <= '<') goto yy5;
						goto yy20;
					} else {
						if (yych == 'F') goto yy23;
						goto yy5;
					}
				}
			}
		} else {
			if (yych <= 'e') {
				if (yych <= 'X') {
					if (yych <= 'O') {
						if (yych <= 'N') goto yy24;
						goto yy25;
					} else {
						if (yych == 'T') goto yy26;
						goto yy5;
					}
				} else {
					if (yych <= '[') {
						if (yych <= 'Y') goto yy27;
						if (yych <= 'Z') goto yy5;
						goto yy28;
					} else {
						if (yych == '^') goto yy16;
						goto yy5;
					}
				}
			} else {
				if (yych <= 's') {
					if (yych <= 'm') {
						if (yych <= 'f') goto yy23;
						goto yy5;
					} else {
						if (yych <= 'n') goto yy24;
						if (yych <= 'o') goto yy25;
						goto yy5;
					}
				} else {
					if (yych <= 'y') {
						if (yych <= 't') goto yy26;
						if (yych <= 'x') goto yy5;
						goto yy27;
					} else {
						if (yych <= 'z') goto yy5;
						if (yych <= '~') goto yy16;
						goto yy5;
					}
				}
			}
		}
		YYDEBUG(3, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(4, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 648 "Zend/zend_ini_scanner.l"
		{
	return 0;
}
#line 553 "Zend/zend_ini_scanner.c"
yy5:
		YYDEBUG(5, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
yy6:
		YYDEBUG(6, *YYCURSOR);
		if (yybm[0+yych] & 16) {
			goto yy5;
		}
		if (yych <= '=') goto yy7;
		if (yych <= '[') goto yy30;
yy7:
		YYDEBUG(7, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 481 "Zend/zend_ini_scanner.l"
		{ /* Get option name */
	/* Eat leading whitespace */
	EAT_LEADING_WHITESPACE();

	/* Eat trailing whitespace */
	EAT_TRAILING_WHITESPACE();

	RETURN_TOKEN(TC_LABEL, yytext, yyleng);
}
#line 579 "Zend/zend_ini_scanner.c"
yy8:
		YYDEBUG(8, *YYCURSOR);
		++YYCURSOR;
		YYFILL(2);
		yych = *YYCURSOR;
		YYDEBUG(9, *YYCURSOR);
		if (yybm[0+yych] & 32) {
			goto yy8;
		}
		if (yych <= '\r') {
			if (yych <= 0x08) goto yy10;
			if (yych <= '\n') goto yy11;
			if (yych >= '\r') goto yy13;
		} else {
			if (yych <= ';') {
				if (yych >= ';') goto yy18;
			} else {
				if (yych == '=') goto yy20;
			}
		}
yy10:
		YYDEBUG(10, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 627 "Zend/zend_ini_scanner.l"
		{
	/* eat whitespace */
	goto restart;
}
#line 608 "Zend/zend_ini_scanner.c"
yy11:
		YYDEBUG(11, *YYCURSOR);
		++YYCURSOR;
yy12:
		YYDEBUG(12, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 632 "Zend/zend_ini_scanner.l"
		{
	SCNG(lineno)++;
	return END_OF_LINE;
}
#line 620 "Zend/zend_ini_scanner.c"
yy13:
		YYDEBUG(13, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy11;
		goto yy12;
yy14:
		YYDEBUG(14, *YYCURSOR);
		++YYCURSOR;
		YYFILL(2);
		yych = *YYCURSOR;
		YYDEBUG(15, *YYCURSOR);
		if (yybm[0+yych] & 64) {
			goto yy14;
		}
		if (yych <= '&') {
			if (yych <= '\r') {
				if (yych <= '\t') {
					if (yych <= 0x00) goto yy7;
					if (yych <= 0x08) goto yy5;
					goto yy8;
				} else {
					if (yych <= '\n') goto yy11;
					if (yych <= '\f') goto yy5;
					goto yy13;
				}
			} else {
				if (yych <= '#') {
					if (yych <= 0x1F) goto yy5;
					if (yych <= '"') goto yy7;
					goto yy5;
				} else {
					if (yych == '%') goto yy5;
					goto yy7;
				}
			}
		} else {
			if (yych <= '=') {
				if (yych <= ':') {
					if (yych <= '\'') goto yy5;
					if (yych <= ')') goto yy7;
					goto yy5;
				} else {
					if (yych <= ';') goto yy18;
					if (yych <= '<') goto yy5;
					goto yy20;
				}
			} else {
				if (yych <= ']') {
					if (yych == '[') goto yy30;
					goto yy5;
				} else {
					if (yych <= '^') goto yy7;
					if (yych <= 'z') goto yy5;
					if (yych <= '~') goto yy7;
					goto yy5;
				}
			}
		}
yy16:
		YYDEBUG(16, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(17, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 555 "Zend/zend_ini_scanner.l"
		{ /* Disallow these chars outside option values */
	return yytext[0];
}
#line 688 "Zend/zend_ini_scanner.c"
yy18:
		YYDEBUG(18, *YYCURSOR);
		++YYCURSOR;
		YYFILL(2);
		yych = *YYCURSOR;
		YYDEBUG(19, *YYCURSOR);
		if (yybm[0+yych] & 128) {
			goto yy18;
		}
		if (yych <= '\n') goto yy33;
		goto yy35;
yy20:
		YYDEBUG(20, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(21, *YYCURSOR);
		if (yych == '\t') goto yy20;
		if (yych == ' ') goto yy20;
		YYDEBUG(22, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 491 "Zend/zend_ini_scanner.l"
		{ /* Start option value */
	if (SCNG(scanner_mode) == ZEND_INI_SCANNER_RAW) {
		BEGIN(ST_RAW);
	} else {
		BEGIN(ST_VALUE);
	}
	return '=';
}
#line 719 "Zend/zend_ini_scanner.c"
yy23:
		YYDEBUG(23, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'A') goto yy36;
		if (yych == 'a') goto yy36;
		goto yy6;
yy24:
		YYDEBUG(24, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych <= 'U') {
			if (yych == 'O') goto yy37;
			if (yych <= 'T') goto yy6;
			goto yy39;
		} else {
			if (yych <= 'o') {
				if (yych <= 'n') goto yy6;
				goto yy37;
			} else {
				if (yych == 'u') goto yy39;
				goto yy6;
			}
		}
yy25:
		YYDEBUG(25, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych <= 'N') {
			if (yych == 'F') goto yy40;
			if (yych <= 'M') goto yy6;
			goto yy41;
		} else {
			if (yych <= 'f') {
				if (yych <= 'e') goto yy6;
				goto yy40;
			} else {
				if (yych == 'n') goto yy41;
				goto yy6;
			}
		}
yy26:
		YYDEBUG(26, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'R') goto yy44;
		if (yych == 'r') goto yy44;
		goto yy6;
yy27:
		YYDEBUG(27, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'E') goto yy45;
		if (yych == 'e') goto yy45;
		goto yy6;
yy28:
		YYDEBUG(28, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(29, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 406 "Zend/zend_ini_scanner.l"
		{ /* Section start */
	/* Enter section data lookup state */
	if (SCNG(scanner_mode) == ZEND_INI_SCANNER_RAW) {
		BEGIN(ST_SECTION_RAW);
	} else {
		BEGIN(ST_SECTION_VALUE);
	}
	return TC_SECTION;
}
#line 785 "Zend/zend_ini_scanner.c"
yy30:
		YYDEBUG(30, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(31, *YYCURSOR);
		if (yych == '\t') goto yy30;
		if (yych == ' ') goto yy30;
		YYDEBUG(32, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 431 "Zend/zend_ini_scanner.l"
		{ /* Start of option with offset */
	/* Eat leading whitespace */
	EAT_LEADING_WHITESPACE();

	/* Eat trailing whitespace and [ */
	EAT_TRAILING_WHITESPACE_EX('[');

	/* Enter offset lookup state */
	BEGIN(ST_OFFSET);

	RETURN_TOKEN(TC_OFFSET, yytext, yyleng);
}
#line 809 "Zend/zend_ini_scanner.c"
yy33:
		YYDEBUG(33, *YYCURSOR);
		++YYCURSOR;
yy34:
		YYDEBUG(34, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 637 "Zend/zend_ini_scanner.l"
		{ /* Comment */
	BEGIN(INITIAL);
	SCNG(lineno)++;
	return END_OF_LINE;
}
#line 822 "Zend/zend_ini_scanner.c"
yy35:
		YYDEBUG(35, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy33;
		goto yy34;
yy36:
		YYDEBUG(36, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'L') goto yy46;
		if (yych == 'l') goto yy46;
		goto yy6;
yy37:
		YYDEBUG(37, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych <= '\'') {
			if (yych <= 0x1F) {
				if (yych <= '\t') {
					if (yych <= 0x00) goto yy38;
					if (yych <= 0x08) goto yy6;
					goto yy47;
				} else {
					if (yych <= '\n') goto yy38;
					if (yych != '\r') goto yy6;
				}
			} else {
				if (yych <= '#') {
					if (yych <= ' ') goto yy49;
					if (yych >= '#') goto yy6;
				} else {
					if (yych == '%') goto yy6;
					if (yych >= '\'') goto yy6;
				}
			}
		} else {
			if (yych <= 'N') {
				if (yych <= ';') {
					if (yych <= ')') goto yy38;
					if (yych <= ':') goto yy6;
				} else {
					if (yych == '=') goto yy38;
					if (yych <= 'M') goto yy6;
					goto yy51;
				}
			} else {
				if (yych <= 'm') {
					if (yych != '^') goto yy6;
				} else {
					if (yych <= 'n') goto yy51;
					if (yych <= 'z') goto yy6;
					if (yych >= 0x7F) goto yy6;
				}
			}
		}
yy38:
		YYDEBUG(38, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 473 "Zend/zend_ini_scanner.l"
		{ /* FALSE value (when used outside option value/offset this causes parse error!)*/
	RETURN_TOKEN(BOOL_FALSE, "", 0);
}
#line 883 "Zend/zend_ini_scanner.c"
yy39:
		YYDEBUG(39, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'L') goto yy52;
		if (yych == 'l') goto yy52;
		goto yy6;
yy40:
		YYDEBUG(40, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'F') goto yy49;
		if (yych == 'f') goto yy49;
		goto yy6;
yy41:
		YYDEBUG(41, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(42, *YYCURSOR);
		if (yych <= '&') {
			if (yych <= '\r') {
				if (yych <= '\t') {
					if (yych <= 0x00) goto yy43;
					if (yych <= 0x08) goto yy5;
					goto yy53;
				} else {
					if (yych <= '\n') goto yy43;
					if (yych <= '\f') goto yy5;
				}
			} else {
				if (yych <= '"') {
					if (yych <= 0x1F) goto yy5;
					if (yych <= ' ') goto yy41;
				} else {
					if (yych == '$') goto yy43;
					if (yych <= '%') goto yy5;
				}
			}
		} else {
			if (yych <= '=') {
				if (yych <= ':') {
					if (yych <= '\'') goto yy5;
					if (yych >= '*') goto yy5;
				} else {
					if (yych == '<') goto yy5;
				}
			} else {
				if (yych <= ']') {
					if (yych == '[') goto yy30;
					goto yy5;
				} else {
					if (yych <= '^') goto yy43;
					if (yych <= 'z') goto yy5;
					if (yych >= 0x7F) goto yy5;
				}
			}
		}
yy43:
		YYDEBUG(43, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 469 "Zend/zend_ini_scanner.l"
		{ /* TRUE value (when used outside option value/offset this causes parse error!) */
	RETURN_TOKEN(BOOL_TRUE, "1", 1);
}
#line 947 "Zend/zend_ini_scanner.c"
yy44:
		YYDEBUG(44, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'U') goto yy55;
		if (yych == 'u') goto yy55;
		goto yy6;
yy45:
		YYDEBUG(45, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'S') goto yy41;
		if (yych == 's') goto yy41;
		goto yy6;
yy46:
		YYDEBUG(46, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'S') goto yy51;
		if (yych == 's') goto yy51;
		goto yy6;
yy47:
		YYDEBUG(47, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(48, *YYCURSOR);
		if (yych == '\t') goto yy47;
		if (yych == ' ') goto yy47;
		goto yy38;
yy49:
		YYDEBUG(49, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(50, *YYCURSOR);
		if (yych <= '&') {
			if (yych <= '\r') {
				if (yych <= '\t') {
					if (yych <= 0x00) goto yy38;
					if (yych <= 0x08) goto yy5;
					goto yy47;
				} else {
					if (yych <= '\n') goto yy38;
					if (yych <= '\f') goto yy5;
					goto yy38;
				}
			} else {
				if (yych <= '"') {
					if (yych <= 0x1F) goto yy5;
					if (yych <= ' ') goto yy49;
					goto yy38;
				} else {
					if (yych == '$') goto yy38;
					if (yych <= '%') goto yy5;
					goto yy38;
				}
			}
		} else {
			if (yych <= '=') {
				if (yych <= ':') {
					if (yych <= '\'') goto yy5;
					if (yych <= ')') goto yy38;
					goto yy5;
				} else {
					if (yych == '<') goto yy5;
					goto yy38;
				}
			} else {
				if (yych <= ']') {
					if (yych == '[') goto yy30;
					goto yy5;
				} else {
					if (yych <= '^') goto yy38;
					if (yych <= 'z') goto yy5;
					if (yych <= '~') goto yy38;
					goto yy5;
				}
			}
		}
yy51:
		YYDEBUG(51, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'E') goto yy49;
		if (yych == 'e') goto yy49;
		goto yy6;
yy52:
		YYDEBUG(52, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'L') goto yy56;
		if (yych == 'l') goto yy56;
		goto yy6;
yy53:
		YYDEBUG(53, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(54, *YYCURSOR);
		if (yych == '\t') goto yy53;
		if (yych == ' ') goto yy53;
		goto yy43;
yy55:
		YYDEBUG(55, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == 'E') goto yy41;
		if (yych == 'e') goto yy41;
		goto yy6;
yy56:
		YYDEBUG(56, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(57, *YYCURSOR);
		if (yych <= '&') {
			if (yych <= '\r') {
				if (yych <= '\t') {
					if (yych <= 0x00) goto yy58;
					if (yych <= 0x08) goto yy5;
					goto yy59;
				} else {
					if (yych <= '\n') goto yy58;
					if (yych <= '\f') goto yy5;
				}
			} else {
				if (yych <= '"') {
					if (yych <= 0x1F) goto yy5;
					if (yych <= ' ') goto yy56;
				} else {
					if (yych == '$') goto yy58;
					if (yych <= '%') goto yy5;
				}
			}
		} else {
			if (yych <= '=') {
				if (yych <= ':') {
					if (yych <= '\'') goto yy5;
					if (yych >= '*') goto yy5;
				} else {
					if (yych == '<') goto yy5;
				}
			} else {
				if (yych <= ']') {
					if (yych == '[') goto yy30;
					goto yy5;
				} else {
					if (yych <= '^') goto yy58;
					if (yych <= 'z') goto yy5;
					if (yych >= 0x7F) goto yy5;
				}
			}
		}
yy58:
		YYDEBUG(58, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 477 "Zend/zend_ini_scanner.l"
		{
	RETURN_TOKEN(NULL_NULL, "", 0);
}
#line 1103 "Zend/zend_ini_scanner.c"
yy59:
		YYDEBUG(59, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(60, *YYCURSOR);
		if (yych == '\t') goto yy59;
		if (yych == ' ') goto yy59;
		goto yy58;
	}
/* *********************************** */
yyc_ST_OFFSET:
	{
		static const unsigned char yybm[] = {
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 140, 128, 132, 132, 128, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			140, 132, 128, 132, 192, 132, 132,   0, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			180, 180, 180, 180, 180, 180, 180, 180, 
			180, 180, 132, 128, 132, 132, 132, 132, 
			132, 164, 164, 164, 164, 164, 164, 164, 
			164, 164, 164, 164, 164, 164, 164, 164, 
			164, 164, 164, 164, 164, 164, 164, 164, 
			164, 164, 164, 132, 192, 128, 132, 164, 
			132, 164, 164, 164, 164, 164, 164, 164, 
			164, 164, 164, 164, 164, 164, 164, 164, 
			164, 164, 164, 164, 164, 164, 164, 164, 
			164, 164, 164, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
		};
		YYDEBUG(61, *YYCURSOR);
		YYFILL(2);
		yych = *YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy66;
		}
		if (yych <= '/') {
			if (yych <= '"') {
				if (yych <= '\f') {
					if (yych <= 0x08) goto yy63;
					if (yych <= '\n') goto yy68;
				} else {
					if (yych <= '\r') goto yy68;
					if (yych >= '"') goto yy70;
				}
			} else {
				if (yych <= '&') {
					if (yych == '$') goto yy72;
				} else {
					if (yych <= '\'') goto yy73;
					if (yych <= ',') goto yy63;
					if (yych <= '.') goto yy74;
				}
			}
		} else {
			if (yych <= '[') {
				if (yych <= ';') {
					if (yych <= '9') goto yy75;
					if (yych >= ';') goto yy68;
				} else {
					if (yych <= '@') goto yy63;
					if (yych <= 'Z') goto yy78;
				}
			} else {
				if (yych <= '^') {
					if (yych <= '\\') goto yy81;
					if (yych <= ']') goto yy82;
				} else {
					if (yych == '`') goto yy63;
					if (yych <= 'z') goto yy78;
				}
			}
		}
yy63:
		YYDEBUG(63, *YYCURSOR);
		yyaccept = 0;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
yy64:
		YYDEBUG(64, *YYCURSOR);
		if (yybm[0+yych] & 4) {
			goto yy63;
		}
		if (yych <= '"') goto yy65;
		if (yych <= '$') goto yy84;
		if (yych <= ';') goto yy65;
		if (yych <= '\\') goto yy81;
yy65:
		YYDEBUG(65, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 573 "Zend/zend_ini_scanner.l"
		{ /* Get rest as section/offset value */
	RETURN_TOKEN(TC_STRING, yytext, yyleng);
}
#line 1216 "Zend/zend_ini_scanner.c"
yy66:
		YYDEBUG(66, *YYCURSOR);
		yyaccept = 0;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(67, *YYCURSOR);
		if (yybm[0+yych] & 8) {
			goto yy66;
		}
		if (yych <= '$') {
			if (yych <= '\r') {
				if (yych <= 0x08) goto yy63;
				if (yych <= '\n') goto yy65;
				if (yych <= '\f') goto yy63;
				goto yy65;
			} else {
				if (yych == '"') goto yy70;
				if (yych <= '#') goto yy63;
				goto yy84;
			}
		} else {
			if (yych <= ';') {
				if (yych == '\'') goto yy65;
				if (yych <= ':') goto yy63;
				goto yy65;
			} else {
				if (yych <= '[') goto yy63;
				if (yych <= '\\') goto yy81;
				if (yych <= ']') goto yy82;
				goto yy63;
			}
		}
yy68:
		YYDEBUG(68, *YYCURSOR);
		++YYCURSOR;
yy69:
		YYDEBUG(69, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 648 "Zend/zend_ini_scanner.l"
		{
	return 0;
}
#line 1260 "Zend/zend_ini_scanner.c"
yy70:
		YYDEBUG(70, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(71, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 577 "Zend/zend_ini_scanner.l"
		{ /* Double quoted '"' string start */
	yy_push_state(ST_DOUBLE_QUOTES);
	return '"';
}
#line 1271 "Zend/zend_ini_scanner.c"
yy72:
		YYDEBUG(72, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych <= '\\') {
			if (yych <= 0x00) goto yy69;
			if (yych <= '[') goto yy63;
			goto yy86;
		} else {
			if (yych == '{') goto yy88;
			goto yy63;
		}
yy73:
		YYDEBUG(73, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy90;
		}
		goto yy69;
yy74:
		YYDEBUG(74, *YYCURSOR);
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '/') goto yy64;
		if (yych <= '9') goto yy92;
		goto yy64;
yy75:
		YYDEBUG(75, *YYCURSOR);
		yyaccept = 1;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(76, *YYCURSOR);
		if (yybm[0+yych] & 16) {
			goto yy75;
		}
		if (yych <= '&') {
			if (yych <= '\r') {
				if (yych == '\n') goto yy77;
				if (yych <= '\f') goto yy63;
			} else {
				if (yych <= '"') {
					if (yych <= '!') goto yy63;
				} else {
					if (yych == '$') goto yy84;
					goto yy63;
				}
			}
		} else {
			if (yych <= ':') {
				if (yych <= '\'') goto yy77;
				if (yych == '.') goto yy92;
				goto yy63;
			} else {
				if (yych <= '[') {
					if (yych >= '<') goto yy63;
				} else {
					if (yych <= '\\') goto yy81;
					if (yych >= '^') goto yy63;
				}
			}
		}
yy77:
		YYDEBUG(77, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 551 "Zend/zend_ini_scanner.l"
		{ /* Get number option value as string */
	RETURN_TOKEN(TC_NUMBER, yytext, yyleng);
}
#line 1340 "Zend/zend_ini_scanner.c"
yy78:
		YYDEBUG(78, *YYCURSOR);
		yyaccept = 2;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(79, *YYCURSOR);
		if (yybm[0+yych] & 32) {
			goto yy78;
		}
		if (yych <= '$') {
			if (yych <= '\r') {
				if (yych == '\n') goto yy80;
				if (yych <= '\f') goto yy63;
			} else {
				if (yych == '"') goto yy80;
				if (yych <= '#') goto yy63;
				goto yy84;
			}
		} else {
			if (yych <= ';') {
				if (yych == '\'') goto yy80;
				if (yych <= ':') goto yy63;
			} else {
				if (yych <= '[') goto yy63;
				if (yych <= '\\') goto yy81;
				if (yych >= '^') goto yy63;
			}
		}
yy80:
		YYDEBUG(80, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 547 "Zend/zend_ini_scanner.l"
		{ /* Get constant option value */
	RETURN_TOKEN(TC_CONSTANT, yytext, yyleng);
}
#line 1377 "Zend/zend_ini_scanner.c"
yy81:
		YYDEBUG(81, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		goto yy63;
yy82:
		YYDEBUG(82, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(83, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 444 "Zend/zend_ini_scanner.l"
		{ /* End of section or an option offset */
	BEGIN(INITIAL);
	return ']';
}
#line 1394 "Zend/zend_ini_scanner.c"
yy84:
		YYDEBUG(84, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		if (yych <= '\\') {
			if (yych <= 0x00) goto yy85;
			if (yych <= '[') goto yy63;
			goto yy86;
		} else {
			if (yych != '{') goto yy63;
		}
yy85:
		YYDEBUG(85, *YYCURSOR);
		YYCURSOR = YYMARKER;
		if (yyaccept <= 1) {
			if (yyaccept == 0) {
				goto yy65;
			} else {
				goto yy77;
			}
		} else {
			goto yy80;
		}
yy86:
		YYDEBUG(86, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(87, *YYCURSOR);
		if (yybm[0+yych] & 64) {
			goto yy86;
		}
		goto yy63;
yy88:
		YYDEBUG(88, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(89, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 449 "Zend/zend_ini_scanner.l"
		{ /* Variable start */
	yy_push_state(ST_VARNAME);
	return TC_DOLLAR_CURLY;
}
#line 1439 "Zend/zend_ini_scanner.c"
yy90:
		YYDEBUG(90, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(91, *YYCURSOR);
		if (yybm[0+yych] & 128) {
			goto yy90;
		}
		goto yy94;
yy92:
		YYDEBUG(92, *YYCURSOR);
		yyaccept = 1;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(93, *YYCURSOR);
		if (yych <= '&') {
			if (yych <= '\r') {
				if (yych == '\n') goto yy77;
				if (yych <= '\f') goto yy63;
				goto yy77;
			} else {
				if (yych <= '"') {
					if (yych <= '!') goto yy63;
					goto yy77;
				} else {
					if (yych == '$') goto yy84;
					goto yy63;
				}
			}
		} else {
			if (yych <= ':') {
				if (yych <= '\'') goto yy77;
				if (yych <= '/') goto yy63;
				if (yych <= '9') goto yy92;
				goto yy63;
			} else {
				if (yych <= '[') {
					if (yych <= ';') goto yy77;
					goto yy63;
				} else {
					if (yych <= '\\') goto yy81;
					if (yych <= ']') goto yy77;
					goto yy63;
				}
			}
		}
yy94:
		YYDEBUG(94, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(95, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 416 "Zend/zend_ini_scanner.l"
		{ /* Raw string */
	/* Eat leading and trailing single quotes */
	if (yytext[0] == '\'' && yytext[yyleng - 1] == '\'') {
		SCNG(yy_text)++;
		yyleng = yyleng - 2;
	}
	RETURN_TOKEN(TC_RAW, yytext, yyleng);
}
#line 1502 "Zend/zend_ini_scanner.c"
	}
/* *********************************** */
yyc_ST_SECTION_VALUE:
	{
		static const unsigned char yybm[] = {
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 140, 128, 132, 132, 128, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			140, 132, 128, 132, 192, 132, 132,   0, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			180, 180, 180, 180, 180, 180, 180, 180, 
			180, 180, 132, 128, 132, 132, 132, 132, 
			132, 164, 164, 164, 164, 164, 164, 164, 
			164, 164, 164, 164, 164, 164, 164, 164, 
			164, 164, 164, 164, 164, 164, 164, 164, 
			164, 164, 164, 132, 192, 128, 132, 164, 
			132, 164, 164, 164, 164, 164, 164, 164, 
			164, 164, 164, 164, 164, 164, 164, 164, 
			164, 164, 164, 164, 164, 164, 164, 164, 
			164, 164, 164, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
			132, 132, 132, 132, 132, 132, 132, 132, 
		};
		YYDEBUG(96, *YYCURSOR);
		YYFILL(2);
		yych = *YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy101;
		}
		if (yych <= '/') {
			if (yych <= '"') {
				if (yych <= '\f') {
					if (yych <= 0x08) goto yy98;
					if (yych <= '\n') goto yy103;
				} else {
					if (yych <= '\r') goto yy103;
					if (yych >= '"') goto yy105;
				}
			} else {
				if (yych <= '&') {
					if (yych == '$') goto yy107;
				} else {
					if (yych <= '\'') goto yy108;
					if (yych <= ',') goto yy98;
					if (yych <= '.') goto yy109;
				}
			}
		} else {
			if (yych <= '[') {
				if (yych <= ';') {
					if (yych <= '9') goto yy110;
					if (yych >= ';') goto yy103;
				} else {
					if (yych <= '@') goto yy98;
					if (yych <= 'Z') goto yy113;
				}
			} else {
				if (yych <= '^') {
					if (yych <= '\\') goto yy116;
					if (yych <= ']') goto yy117;
				} else {
					if (yych == '`') goto yy98;
					if (yych <= 'z') goto yy113;
				}
			}
		}
yy98:
		YYDEBUG(98, *YYCURSOR);
		yyaccept = 0;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
yy99:
		YYDEBUG(99, *YYCURSOR);
		if (yybm[0+yych] & 4) {
			goto yy98;
		}
		if (yych <= '"') goto yy100;
		if (yych <= '$') goto yy120;
		if (yych <= ';') goto yy100;
		if (yych <= '\\') goto yy116;
yy100:
		YYDEBUG(100, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 573 "Zend/zend_ini_scanner.l"
		{ /* Get rest as section/offset value */
	RETURN_TOKEN(TC_STRING, yytext, yyleng);
}
#line 1606 "Zend/zend_ini_scanner.c"
yy101:
		YYDEBUG(101, *YYCURSOR);
		yyaccept = 0;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(102, *YYCURSOR);
		if (yybm[0+yych] & 8) {
			goto yy101;
		}
		if (yych <= '$') {
			if (yych <= '\r') {
				if (yych <= 0x08) goto yy98;
				if (yych <= '\n') goto yy100;
				if (yych <= '\f') goto yy98;
				goto yy100;
			} else {
				if (yych == '"') goto yy105;
				if (yych <= '#') goto yy98;
				goto yy120;
			}
		} else {
			if (yych <= ';') {
				if (yych == '\'') goto yy100;
				if (yych <= ':') goto yy98;
				goto yy100;
			} else {
				if (yych <= '[') goto yy98;
				if (yych <= '\\') goto yy116;
				if (yych <= ']') goto yy100;
				goto yy98;
			}
		}
yy103:
		YYDEBUG(103, *YYCURSOR);
		++YYCURSOR;
yy104:
		YYDEBUG(104, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 648 "Zend/zend_ini_scanner.l"
		{
	return 0;
}
#line 1650 "Zend/zend_ini_scanner.c"
yy105:
		YYDEBUG(105, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(106, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 577 "Zend/zend_ini_scanner.l"
		{ /* Double quoted '"' string start */
	yy_push_state(ST_DOUBLE_QUOTES);
	return '"';
}
#line 1661 "Zend/zend_ini_scanner.c"
yy107:
		YYDEBUG(107, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych <= '\\') {
			if (yych <= 0x00) goto yy104;
			if (yych <= '[') goto yy98;
			goto yy122;
		} else {
			if (yych == '{') goto yy124;
			goto yy98;
		}
yy108:
		YYDEBUG(108, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy126;
		}
		goto yy104;
yy109:
		YYDEBUG(109, *YYCURSOR);
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '/') goto yy99;
		if (yych <= '9') goto yy128;
		goto yy99;
yy110:
		YYDEBUG(110, *YYCURSOR);
		yyaccept = 1;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(111, *YYCURSOR);
		if (yybm[0+yych] & 16) {
			goto yy110;
		}
		if (yych <= '&') {
			if (yych <= '\r') {
				if (yych == '\n') goto yy112;
				if (yych <= '\f') goto yy98;
			} else {
				if (yych <= '"') {
					if (yych <= '!') goto yy98;
				} else {
					if (yych == '$') goto yy120;
					goto yy98;
				}
			}
		} else {
			if (yych <= ':') {
				if (yych <= '\'') goto yy112;
				if (yych == '.') goto yy128;
				goto yy98;
			} else {
				if (yych <= '[') {
					if (yych >= '<') goto yy98;
				} else {
					if (yych <= '\\') goto yy116;
					if (yych >= '^') goto yy98;
				}
			}
		}
yy112:
		YYDEBUG(112, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 551 "Zend/zend_ini_scanner.l"
		{ /* Get number option value as string */
	RETURN_TOKEN(TC_NUMBER, yytext, yyleng);
}
#line 1730 "Zend/zend_ini_scanner.c"
yy113:
		YYDEBUG(113, *YYCURSOR);
		yyaccept = 2;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(114, *YYCURSOR);
		if (yybm[0+yych] & 32) {
			goto yy113;
		}
		if (yych <= '$') {
			if (yych <= '\r') {
				if (yych == '\n') goto yy115;
				if (yych <= '\f') goto yy98;
			} else {
				if (yych == '"') goto yy115;
				if (yych <= '#') goto yy98;
				goto yy120;
			}
		} else {
			if (yych <= ';') {
				if (yych == '\'') goto yy115;
				if (yych <= ':') goto yy98;
			} else {
				if (yych <= '[') goto yy98;
				if (yych <= '\\') goto yy116;
				if (yych >= '^') goto yy98;
			}
		}
yy115:
		YYDEBUG(115, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 547 "Zend/zend_ini_scanner.l"
		{ /* Get constant option value */
	RETURN_TOKEN(TC_CONSTANT, yytext, yyleng);
}
#line 1767 "Zend/zend_ini_scanner.c"
yy116:
		YYDEBUG(116, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		goto yy98;
yy117:
		YYDEBUG(117, *YYCURSOR);
		++YYCURSOR;
		YYFILL(2);
		yych = *YYCURSOR;
		YYDEBUG(118, *YYCURSOR);
		if (yych <= '\f') {
			if (yych <= 0x08) goto yy119;
			if (yych <= '\t') goto yy117;
			if (yych <= '\n') goto yy130;
		} else {
			if (yych <= '\r') goto yy131;
			if (yych == ' ') goto yy117;
		}
yy119:
		YYDEBUG(119, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 425 "Zend/zend_ini_scanner.l"
		{ /* End of section */
	BEGIN(INITIAL);
	SCNG(lineno)++;
	return ']';
}
#line 1797 "Zend/zend_ini_scanner.c"
yy120:
		YYDEBUG(120, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		if (yych <= '\\') {
			if (yych <= 0x00) goto yy121;
			if (yych <= '[') goto yy98;
			goto yy122;
		} else {
			if (yych != '{') goto yy98;
		}
yy121:
		YYDEBUG(121, *YYCURSOR);
		YYCURSOR = YYMARKER;
		if (yyaccept <= 1) {
			if (yyaccept == 0) {
				goto yy100;
			} else {
				goto yy112;
			}
		} else {
			goto yy115;
		}
yy122:
		YYDEBUG(122, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(123, *YYCURSOR);
		if (yybm[0+yych] & 64) {
			goto yy122;
		}
		goto yy98;
yy124:
		YYDEBUG(124, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(125, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 449 "Zend/zend_ini_scanner.l"
		{ /* Variable start */
	yy_push_state(ST_VARNAME);
	return TC_DOLLAR_CURLY;
}
#line 1842 "Zend/zend_ini_scanner.c"
yy126:
		YYDEBUG(126, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(127, *YYCURSOR);
		if (yybm[0+yych] & 128) {
			goto yy126;
		}
		goto yy132;
yy128:
		YYDEBUG(128, *YYCURSOR);
		yyaccept = 1;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(129, *YYCURSOR);
		if (yych <= '&') {
			if (yych <= '\r') {
				if (yych == '\n') goto yy112;
				if (yych <= '\f') goto yy98;
				goto yy112;
			} else {
				if (yych <= '"') {
					if (yych <= '!') goto yy98;
					goto yy112;
				} else {
					if (yych == '$') goto yy120;
					goto yy98;
				}
			}
		} else {
			if (yych <= ':') {
				if (yych <= '\'') goto yy112;
				if (yych <= '/') goto yy98;
				if (yych <= '9') goto yy128;
				goto yy98;
			} else {
				if (yych <= '[') {
					if (yych <= ';') goto yy112;
					goto yy98;
				} else {
					if (yych <= '\\') goto yy116;
					if (yych <= ']') goto yy112;
					goto yy98;
				}
			}
		}
yy130:
		YYDEBUG(130, *YYCURSOR);
		++YYCURSOR;
		goto yy119;
yy131:
		YYDEBUG(131, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy130;
		goto yy119;
yy132:
		YYDEBUG(132, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(133, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 416 "Zend/zend_ini_scanner.l"
		{ /* Raw string */
	/* Eat leading and trailing single quotes */
	if (yytext[0] == '\'' && yytext[yyleng - 1] == '\'') {
		SCNG(yy_text)++;
		yyleng = yyleng - 2;
	}
	RETURN_TOKEN(TC_RAW, yytext, yyleng);
}
#line 1914 "Zend/zend_ini_scanner.c"
	}
/* *********************************** */
yyc_ST_VALUE:
	{
		static const unsigned char yybm[] = {
			 80,  82,  82,  82,  82,  82,  82,  82, 
			 82,  84,  64,  82,  82,  64,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 84,  80,  80,  82, 208,  82,  80,  16, 
			 80,  80,  82,  82,  82,  82,  82,  82, 
			122, 122, 122, 122, 122, 122, 122, 122, 
			122, 122,  82,  80,  82,  80,  82,  82, 
			 82, 114, 114, 114, 114, 114, 114, 114, 
			114, 114, 114, 114, 114, 114, 114, 114, 
			114, 114, 114, 114, 114, 114, 114, 114, 
			114, 114, 114,  82,  82,  82,  80, 114, 
			 82, 114, 114, 114, 114, 114, 114, 114, 
			114, 114, 114, 114, 114, 114, 114, 114, 
			114, 114, 114, 114, 114, 114, 114, 114, 
			114, 114, 114,  82,  80,  82,  80,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
			 82,  82,  82,  82,  82,  82,  82,  82, 
		};
		YYDEBUG(134, *YYCURSOR);
		YYFILL(6);
		yych = *YYCURSOR;
		if (yybm[0+yych] & 4) {
			goto yy141;
		}
		switch (yych) {
		case 0x00:	goto yy136;
		case '\t':
		case '\n':	goto yy144;
		case '\r':	goto yy146;
		case ' ':
		case '!':
		case '&':
		case '(':
		case ')':
		case '^':
		case '|':
		case '~':	goto yy147;
		case '"':	goto yy150;
		case '$':	goto yy152;
		case '\'':	goto yy153;
		case '-':
		case '.':	goto yy154;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':	goto yy155;
		case ';':	goto yy158;
		case '=':	goto yy160;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'z':	goto yy162;
		case 'F':
		case 'f':	goto yy165;
		case 'N':
		case 'n':	goto yy166;
		case 'O':
		case 'o':	goto yy167;
		case 'T':
		case 't':	goto yy168;
		case 'Y':
		case 'y':	goto yy169;
		default:	goto yy138;
		}
yy136:
		YYDEBUG(136, *YYCURSOR);
		++YYCURSOR;
yy137:
		YYDEBUG(137, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 643 "Zend/zend_ini_scanner.l"
		{ /* End of option value (if EOF is reached before EOL */
	BEGIN(INITIAL);
	return END_OF_LINE;
}
#line 2055 "Zend/zend_ini_scanner.c"
yy138:
		YYDEBUG(138, *YYCURSOR);
		yyaccept = 0;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
yy139:
		YYDEBUG(139, *YYCURSOR);
		if (yybm[0+yych] & 2) {
			goto yy138;
		}
		if (yych <= '"') goto yy140;
		if (yych <= '$') goto yy170;
yy140:
		YYDEBUG(140, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 569 "Zend/zend_ini_scanner.l"
		{ /* Get everything else as option/offset value */
	RETURN_TOKEN(TC_STRING, yytext, yyleng);
}
#line 2076 "Zend/zend_ini_scanner.c"
yy141:
		YYDEBUG(141, *YYCURSOR);
		++YYCURSOR;
		YYFILL(2);
		yych = *YYCURSOR;
		YYDEBUG(142, *YYCURSOR);
		if (yybm[0+yych] & 4) {
			goto yy141;
		}
		if (yych <= '\r') {
			if (yych <= 0x08) goto yy143;
			if (yych <= '\n') goto yy144;
			if (yych >= '\r') goto yy146;
		} else {
			if (yych <= '"') {
				if (yych >= '"') goto yy150;
			} else {
				if (yych == ';') goto yy158;
			}
		}
yy143:
		YYDEBUG(143, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 623 "Zend/zend_ini_scanner.l"
		{
	RETURN_TOKEN(TC_WHITESPACE, yytext, yyleng);
}
#line 2104 "Zend/zend_ini_scanner.c"
yy144:
		YYDEBUG(144, *YYCURSOR);
		++YYCURSOR;
yy145:
		YYDEBUG(145, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 541 "Zend/zend_ini_scanner.l"
		{ /* End of option value */
	BEGIN(INITIAL);
	SCNG(lineno)++;
	return END_OF_LINE;
}
#line 2117 "Zend/zend_ini_scanner.c"
yy146:
		YYDEBUG(146, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy144;
		goto yy145;
yy147:
		YYDEBUG(147, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(148, *YYCURSOR);
		if (yych == '\t') goto yy147;
		if (yych == ' ') goto yy147;
		YYDEBUG(149, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 559 "Zend/zend_ini_scanner.l"
		{ /* Boolean operators */
	return yytext[0];
}
#line 2137 "Zend/zend_ini_scanner.c"
yy150:
		YYDEBUG(150, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(151, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 577 "Zend/zend_ini_scanner.l"
		{ /* Double quoted '"' string start */
	yy_push_state(ST_DOUBLE_QUOTES);
	return '"';
}
#line 2148 "Zend/zend_ini_scanner.c"
yy152:
		YYDEBUG(152, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych <= '\\') {
			if (yych <= 0x00) goto yy137;
			if (yych <= '[') goto yy138;
			goto yy172;
		} else {
			if (yych == '{') goto yy173;
			goto yy138;
		}
yy153:
		YYDEBUG(153, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy175;
		}
		goto yy137;
yy154:
		YYDEBUG(154, *YYCURSOR);
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '/') goto yy139;
		if (yych <= '9') goto yy177;
		goto yy139;
yy155:
		YYDEBUG(155, *YYCURSOR);
		yyaccept = 1;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(156, *YYCURSOR);
		if (yybm[0+yych] & 8) {
			goto yy155;
		}
		if (yych <= '-') {
			if (yych <= 0x1F) {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy157;
					if (yych <= 0x08) goto yy138;
				} else {
					if (yych != '\r') goto yy138;
				}
			} else {
				if (yych <= '$') {
					if (yych <= '"') goto yy157;
					if (yych <= '#') goto yy138;
					goto yy170;
				} else {
					if (yych <= '%') goto yy138;
					if (yych >= '*') goto yy138;
				}
			}
		} else {
			if (yych <= ']') {
				if (yych <= ';') {
					if (yych <= '.') goto yy177;
					if (yych <= ':') goto yy138;
				} else {
					if (yych != '=') goto yy138;
				}
			} else {
				if (yych <= '|') {
					if (yych <= '^') goto yy157;
					if (yych <= '{') goto yy138;
				} else {
					if (yych != '~') goto yy138;
				}
			}
		}
yy157:
		YYDEBUG(157, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 551 "Zend/zend_ini_scanner.l"
		{ /* Get number option value as string */
	RETURN_TOKEN(TC_NUMBER, yytext, yyleng);
}
#line 2226 "Zend/zend_ini_scanner.c"
yy158:
		YYDEBUG(158, *YYCURSOR);
		++YYCURSOR;
		YYFILL(2);
		yych = *YYCURSOR;
		YYDEBUG(159, *YYCURSOR);
		if (yybm[0+yych] & 16) {
			goto yy158;
		}
		if (yych <= '\n') goto yy179;
		goto yy181;
yy160:
		YYDEBUG(160, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(161, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 563 "Zend/zend_ini_scanner.l"
		{ /* Make = used in option value to trigger error */
	yyless(0);
	BEGIN(INITIAL);
	return END_OF_LINE;
}
#line 2249 "Zend/zend_ini_scanner.c"
yy162:
		YYDEBUG(162, *YYCURSOR);
		yyaccept = 2;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(163, *YYCURSOR);
		if (yybm[0+yych] & 32) {
			goto yy162;
		}
		if (yych <= ')') {
			if (yych <= '\r') {
				if (yych <= 0x08) {
					if (yych >= 0x01) goto yy138;
				} else {
					if (yych <= '\n') goto yy164;
					if (yych <= '\f') goto yy138;
				}
			} else {
				if (yych <= '#') {
					if (yych <= 0x1F) goto yy138;
					if (yych >= '#') goto yy138;
				} else {
					if (yych <= '$') goto yy170;
					if (yych <= '%') goto yy138;
				}
			}
		} else {
			if (yych <= ']') {
				if (yych <= ';') {
					if (yych <= ':') goto yy138;
				} else {
					if (yych != '=') goto yy138;
				}
			} else {
				if (yych <= '|') {
					if (yych <= '^') goto yy164;
					if (yych <= '{') goto yy138;
				} else {
					if (yych != '~') goto yy138;
				}
			}
		}
yy164:
		YYDEBUG(164, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 547 "Zend/zend_ini_scanner.l"
		{ /* Get constant option value */
	RETURN_TOKEN(TC_CONSTANT, yytext, yyleng);
}
#line 2300 "Zend/zend_ini_scanner.c"
yy165:
		YYDEBUG(165, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '<') {
			if (yych <= '"') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					goto yy164;
				} else {
					if (yych == '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					goto yy164;
				}
			} else {
				if (yych <= '/') {
					if (yych <= '%') goto yy139;
					if (yych <= ')') goto yy164;
					goto yy139;
				} else {
					if (yych <= '9') goto yy162;
					if (yych == ';') goto yy164;
					goto yy139;
				}
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'A') {
					if (yych <= '=') goto yy164;
					if (yych <= '@') goto yy139;
					goto yy182;
				} else {
					if (yych <= 'Z') goto yy162;
					if (yych <= ']') goto yy139;
					if (yych <= '^') goto yy164;
					goto yy162;
				}
			} else {
				if (yych <= '{') {
					if (yych <= '`') goto yy139;
					if (yych <= 'a') goto yy182;
					if (yych <= 'z') goto yy162;
					goto yy139;
				} else {
					if (yych == '}') goto yy139;
					if (yych <= '~') goto yy164;
					goto yy139;
				}
			}
		}
yy166:
		YYDEBUG(166, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 'N') {
			if (yych <= '%') {
				if (yych <= '\f') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					if (yych <= '\n') goto yy164;
					goto yy139;
				} else {
					if (yych <= '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					if (yych <= '"') goto yy164;
					goto yy139;
				}
			} else {
				if (yych <= ':') {
					if (yych <= ')') goto yy164;
					if (yych <= '/') goto yy139;
					if (yych <= '9') goto yy162;
					goto yy139;
				} else {
					if (yych <= '<') {
						if (yych <= ';') goto yy164;
						goto yy139;
					} else {
						if (yych <= '=') goto yy164;
						if (yych <= '@') goto yy139;
						goto yy162;
					}
				}
			}
		} else {
			if (yych <= 'n') {
				if (yych <= 'Z') {
					if (yych <= 'O') goto yy183;
					if (yych == 'U') goto yy185;
					goto yy162;
				} else {
					if (yych <= '^') {
						if (yych <= ']') goto yy139;
						goto yy164;
					} else {
						if (yych == '`') goto yy139;
						goto yy162;
					}
				}
			} else {
				if (yych <= 'z') {
					if (yych <= 'o') goto yy183;
					if (yych == 'u') goto yy185;
					goto yy162;
				} else {
					if (yych <= '|') {
						if (yych <= '{') goto yy139;
						goto yy164;
					} else {
						if (yych == '~') goto yy164;
						goto yy139;
					}
				}
			}
		}
yy167:
		YYDEBUG(167, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= 'E') {
			if (yych <= '%') {
				if (yych <= '\f') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					if (yych <= '\n') goto yy164;
					goto yy139;
				} else {
					if (yych <= '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					if (yych <= '"') goto yy164;
					goto yy139;
				}
			} else {
				if (yych <= ':') {
					if (yych <= ')') goto yy164;
					if (yych <= '/') goto yy139;
					if (yych <= '9') goto yy162;
					goto yy139;
				} else {
					if (yych <= '<') {
						if (yych <= ';') goto yy164;
						goto yy139;
					} else {
						if (yych <= '=') goto yy164;
						if (yych <= '@') goto yy139;
						goto yy162;
					}
				}
			}
		} else {
			if (yych <= 'e') {
				if (yych <= 'Z') {
					if (yych <= 'F') goto yy186;
					if (yych == 'N') goto yy187;
					goto yy162;
				} else {
					if (yych <= '^') {
						if (yych <= ']') goto yy139;
						goto yy164;
					} else {
						if (yych == '`') goto yy139;
						goto yy162;
					}
				}
			} else {
				if (yych <= 'z') {
					if (yych <= 'f') goto yy186;
					if (yych == 'n') goto yy187;
					goto yy162;
				} else {
					if (yych <= '|') {
						if (yych <= '{') goto yy139;
						goto yy164;
					} else {
						if (yych == '~') goto yy164;
						goto yy139;
					}
				}
			}
		}
yy168:
		YYDEBUG(168, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '=') {
			if (yych <= '"') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					goto yy164;
				} else {
					if (yych == '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					goto yy164;
				}
			} else {
				if (yych <= '9') {
					if (yych <= '%') goto yy139;
					if (yych <= ')') goto yy164;
					if (yych <= '/') goto yy139;
					goto yy162;
				} else {
					if (yych == ';') goto yy164;
					if (yych <= '<') goto yy139;
					goto yy164;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych <= '@') goto yy139;
					if (yych == 'R') goto yy189;
					goto yy162;
				} else {
					if (yych <= ']') goto yy139;
					if (yych <= '^') goto yy164;
					if (yych <= '_') goto yy162;
					goto yy139;
				}
			} else {
				if (yych <= '{') {
					if (yych == 'r') goto yy189;
					if (yych <= 'z') goto yy162;
					goto yy139;
				} else {
					if (yych == '}') goto yy139;
					if (yych <= '~') goto yy164;
					goto yy139;
				}
			}
		}
yy169:
		YYDEBUG(169, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '=') {
			if (yych <= '"') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					goto yy164;
				} else {
					if (yych == '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					goto yy164;
				}
			} else {
				if (yych <= '9') {
					if (yych <= '%') goto yy139;
					if (yych <= ')') goto yy164;
					if (yych <= '/') goto yy139;
					goto yy162;
				} else {
					if (yych == ';') goto yy164;
					if (yych <= '<') goto yy139;
					goto yy164;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych <= '@') goto yy139;
					if (yych == 'E') goto yy190;
					goto yy162;
				} else {
					if (yych <= ']') goto yy139;
					if (yych <= '^') goto yy164;
					if (yych <= '_') goto yy162;
					goto yy139;
				}
			} else {
				if (yych <= '{') {
					if (yych == 'e') goto yy190;
					if (yych <= 'z') goto yy162;
					goto yy139;
				} else {
					if (yych == '}') goto yy139;
					if (yych <= '~') goto yy164;
					goto yy139;
				}
			}
		}
yy170:
		YYDEBUG(170, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		if (yych <= '\\') {
			if (yych <= 0x00) goto yy171;
			if (yych <= '[') goto yy138;
			goto yy172;
		} else {
			if (yych != '{') goto yy138;
		}
yy171:
		YYDEBUG(171, *YYCURSOR);
		YYCURSOR = YYMARKER;
		if (yyaccept <= 2) {
			if (yyaccept <= 1) {
				if (yyaccept == 0) {
					goto yy140;
				} else {
					goto yy157;
				}
			} else {
				goto yy164;
			}
		} else {
			if (yyaccept <= 4) {
				if (yyaccept == 3) {
					goto yy184;
				} else {
					goto yy188;
				}
			} else {
				goto yy205;
			}
		}
yy172:
		YYDEBUG(172, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy191;
		}
		goto yy138;
yy173:
		YYDEBUG(173, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(174, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 449 "Zend/zend_ini_scanner.l"
		{ /* Variable start */
	yy_push_state(ST_VARNAME);
	return TC_DOLLAR_CURLY;
}
#line 2639 "Zend/zend_ini_scanner.c"
yy175:
		YYDEBUG(175, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(176, *YYCURSOR);
		if (yybm[0+yych] & 64) {
			goto yy175;
		}
		goto yy193;
yy177:
		YYDEBUG(177, *YYCURSOR);
		yyaccept = 1;
		YYMARKER = ++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(178, *YYCURSOR);
		if (yych <= '/') {
			if (yych <= 0x1F) {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy157;
					if (yych <= 0x08) goto yy138;
					goto yy157;
				} else {
					if (yych == '\r') goto yy157;
					goto yy138;
				}
			} else {
				if (yych <= '$') {
					if (yych <= '"') goto yy157;
					if (yych <= '#') goto yy138;
					goto yy170;
				} else {
					if (yych <= '%') goto yy138;
					if (yych <= ')') goto yy157;
					goto yy138;
				}
			}
		} else {
			if (yych <= ']') {
				if (yych <= ';') {
					if (yych <= '9') goto yy177;
					if (yych <= ':') goto yy138;
					goto yy157;
				} else {
					if (yych == '=') goto yy157;
					goto yy138;
				}
			} else {
				if (yych <= '|') {
					if (yych <= '^') goto yy157;
					if (yych <= '{') goto yy138;
					goto yy157;
				} else {
					if (yych == '~') goto yy157;
					goto yy138;
				}
			}
		}
yy179:
		YYDEBUG(179, *YYCURSOR);
		++YYCURSOR;
yy180:
		YYDEBUG(180, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 637 "Zend/zend_ini_scanner.l"
		{ /* Comment */
	BEGIN(INITIAL);
	SCNG(lineno)++;
	return END_OF_LINE;
}
#line 2711 "Zend/zend_ini_scanner.c"
yy181:
		YYDEBUG(181, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy179;
		goto yy180;
yy182:
		YYDEBUG(182, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '=') {
			if (yych <= '"') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					goto yy164;
				} else {
					if (yych == '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					goto yy164;
				}
			} else {
				if (yych <= '9') {
					if (yych <= '%') goto yy139;
					if (yych <= ')') goto yy164;
					if (yych <= '/') goto yy139;
					goto yy162;
				} else {
					if (yych == ';') goto yy164;
					if (yych <= '<') goto yy139;
					goto yy164;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych <= '@') goto yy139;
					if (yych == 'L') goto yy195;
					goto yy162;
				} else {
					if (yych <= ']') goto yy139;
					if (yych <= '^') goto yy164;
					if (yych <= '_') goto yy162;
					goto yy139;
				}
			} else {
				if (yych <= '{') {
					if (yych == 'l') goto yy195;
					if (yych <= 'z') goto yy162;
					goto yy139;
				} else {
					if (yych == '}') goto yy139;
					if (yych <= '~') goto yy164;
					goto yy139;
				}
			}
		}
yy183:
		YYDEBUG(183, *YYCURSOR);
		yyaccept = 3;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '<') {
			if (yych <= ' ') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy184;
					if (yych <= 0x08) goto yy139;
					if (yych <= '\t') goto yy196;
				} else {
					if (yych == '\r') goto yy184;
					if (yych <= 0x1F) goto yy139;
					goto yy196;
				}
			} else {
				if (yych <= '/') {
					if (yych <= '"') goto yy184;
					if (yych <= '%') goto yy139;
					if (yych >= '*') goto yy139;
				} else {
					if (yych <= '9') goto yy162;
					if (yych != ';') goto yy139;
				}
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'N') {
					if (yych <= '=') goto yy184;
					if (yych <= '@') goto yy139;
					if (yych <= 'M') goto yy162;
					goto yy198;
				} else {
					if (yych <= 'Z') goto yy162;
					if (yych <= ']') goto yy139;
					if (yych >= '_') goto yy162;
				}
			} else {
				if (yych <= 'z') {
					if (yych <= '`') goto yy139;
					if (yych == 'n') goto yy198;
					goto yy162;
				} else {
					if (yych <= '|') {
						if (yych <= '{') goto yy139;
					} else {
						if (yych != '~') goto yy139;
					}
				}
			}
		}
yy184:
		YYDEBUG(184, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 473 "Zend/zend_ini_scanner.l"
		{ /* FALSE value (when used outside option value/offset this causes parse error!)*/
	RETURN_TOKEN(BOOL_FALSE, "", 0);
}
#line 2826 "Zend/zend_ini_scanner.c"
yy185:
		YYDEBUG(185, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '=') {
			if (yych <= '"') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					goto yy164;
				} else {
					if (yych == '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					goto yy164;
				}
			} else {
				if (yych <= '9') {
					if (yych <= '%') goto yy139;
					if (yych <= ')') goto yy164;
					if (yych <= '/') goto yy139;
					goto yy162;
				} else {
					if (yych == ';') goto yy164;
					if (yych <= '<') goto yy139;
					goto yy164;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych <= '@') goto yy139;
					if (yych == 'L') goto yy199;
					goto yy162;
				} else {
					if (yych <= ']') goto yy139;
					if (yych <= '^') goto yy164;
					if (yych <= '_') goto yy162;
					goto yy139;
				}
			} else {
				if (yych <= '{') {
					if (yych == 'l') goto yy199;
					if (yych <= 'z') goto yy162;
					goto yy139;
				} else {
					if (yych == '}') goto yy139;
					if (yych <= '~') goto yy164;
					goto yy139;
				}
			}
		}
yy186:
		YYDEBUG(186, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '=') {
			if (yych <= '"') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					goto yy164;
				} else {
					if (yych == '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					goto yy164;
				}
			} else {
				if (yych <= '9') {
					if (yych <= '%') goto yy139;
					if (yych <= ')') goto yy164;
					if (yych <= '/') goto yy139;
					goto yy162;
				} else {
					if (yych == ';') goto yy164;
					if (yych <= '<') goto yy139;
					goto yy164;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych <= '@') goto yy139;
					if (yych == 'F') goto yy200;
					goto yy162;
				} else {
					if (yych <= ']') goto yy139;
					if (yych <= '^') goto yy164;
					if (yych <= '_') goto yy162;
					goto yy139;
				}
			} else {
				if (yych <= '{') {
					if (yych == 'f') goto yy200;
					if (yych <= 'z') goto yy162;
					goto yy139;
				} else {
					if (yych == '}') goto yy139;
					if (yych <= '~') goto yy164;
					goto yy139;
				}
			}
		}
yy187:
		YYDEBUG(187, *YYCURSOR);
		yyaccept = 4;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yybm[0+yych] & 32) {
			goto yy162;
		}
		if (yych <= ')') {
			if (yych <= '\f') {
				if (yych <= 0x08) {
					if (yych >= 0x01) goto yy139;
				} else {
					if (yych <= '\t') goto yy201;
					if (yych >= '\v') goto yy139;
				}
			} else {
				if (yych <= ' ') {
					if (yych <= '\r') goto yy188;
					if (yych <= 0x1F) goto yy139;
					goto yy201;
				} else {
					if (yych <= '"') goto yy188;
					if (yych <= '%') goto yy139;
				}
			}
		} else {
			if (yych <= ']') {
				if (yych <= ';') {
					if (yych <= ':') goto yy139;
				} else {
					if (yych != '=') goto yy139;
				}
			} else {
				if (yych <= '|') {
					if (yych <= '^') goto yy188;
					if (yych <= '{') goto yy139;
				} else {
					if (yych != '~') goto yy139;
				}
			}
		}
yy188:
		YYDEBUG(188, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 469 "Zend/zend_ini_scanner.l"
		{ /* TRUE value (when used outside option value/offset this causes parse error!) */
	RETURN_TOKEN(BOOL_TRUE, "1", 1);
}
#line 2977 "Zend/zend_ini_scanner.c"
yy189:
		YYDEBUG(189, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '=') {
			if (yych <= '"') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					goto yy164;
				} else {
					if (yych == '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					goto yy164;
				}
			} else {
				if (yych <= '9') {
					if (yych <= '%') goto yy139;
					if (yych <= ')') goto yy164;
					if (yych <= '/') goto yy139;
					goto yy162;
				} else {
					if (yych == ';') goto yy164;
					if (yych <= '<') goto yy139;
					goto yy164;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych <= '@') goto yy139;
					if (yych == 'U') goto yy203;
					goto yy162;
				} else {
					if (yych <= ']') goto yy139;
					if (yych <= '^') goto yy164;
					if (yych <= '_') goto yy162;
					goto yy139;
				}
			} else {
				if (yych <= '{') {
					if (yych == 'u') goto yy203;
					if (yych <= 'z') goto yy162;
					goto yy139;
				} else {
					if (yych == '}') goto yy139;
					if (yych <= '~') goto yy164;
					goto yy139;
				}
			}
		}
yy190:
		YYDEBUG(190, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '=') {
			if (yych <= '"') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					goto yy164;
				} else {
					if (yych == '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					goto yy164;
				}
			} else {
				if (yych <= '9') {
					if (yych <= '%') goto yy139;
					if (yych <= ')') goto yy164;
					if (yych <= '/') goto yy139;
					goto yy162;
				} else {
					if (yych == ';') goto yy164;
					if (yych <= '<') goto yy139;
					goto yy164;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych <= '@') goto yy139;
					if (yych == 'S') goto yy187;
					goto yy162;
				} else {
					if (yych <= ']') goto yy139;
					if (yych <= '^') goto yy164;
					if (yych <= '_') goto yy162;
					goto yy139;
				}
			} else {
				if (yych <= '{') {
					if (yych == 's') goto yy187;
					if (yych <= 'z') goto yy162;
					goto yy139;
				} else {
					if (yych == '}') goto yy139;
					if (yych <= '~') goto yy164;
					goto yy139;
				}
			}
		}
yy191:
		YYDEBUG(191, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(192, *YYCURSOR);
		if (yybm[0+yych] & 128) {
			goto yy191;
		}
		if (yych <= 0x00) goto yy140;
		if (yych == '\\') goto yy172;
		goto yy138;
yy193:
		YYDEBUG(193, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(194, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 416 "Zend/zend_ini_scanner.l"
		{ /* Raw string */
	/* Eat leading and trailing single quotes */
	if (yytext[0] == '\'' && yytext[yyleng - 1] == '\'') {
		SCNG(yy_text)++;
		yyleng = yyleng - 2;
	}
	RETURN_TOKEN(TC_RAW, yytext, yyleng);
}
#line 3106 "Zend/zend_ini_scanner.c"
yy195:
		YYDEBUG(195, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '=') {
			if (yych <= '"') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					goto yy164;
				} else {
					if (yych == '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					goto yy164;
				}
			} else {
				if (yych <= '9') {
					if (yych <= '%') goto yy139;
					if (yych <= ')') goto yy164;
					if (yych <= '/') goto yy139;
					goto yy162;
				} else {
					if (yych == ';') goto yy164;
					if (yych <= '<') goto yy139;
					goto yy164;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych <= '@') goto yy139;
					if (yych == 'S') goto yy198;
					goto yy162;
				} else {
					if (yych <= ']') goto yy139;
					if (yych <= '^') goto yy164;
					if (yych <= '_') goto yy162;
					goto yy139;
				}
			} else {
				if (yych <= '{') {
					if (yych == 's') goto yy198;
					if (yych <= 'z') goto yy162;
					goto yy139;
				} else {
					if (yych == '}') goto yy139;
					if (yych <= '~') goto yy164;
					goto yy139;
				}
			}
		}
yy196:
		YYDEBUG(196, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(197, *YYCURSOR);
		if (yych == '\t') goto yy196;
		if (yych == ' ') goto yy196;
		goto yy184;
yy198:
		YYDEBUG(198, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '=') {
			if (yych <= '"') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					goto yy164;
				} else {
					if (yych == '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					goto yy164;
				}
			} else {
				if (yych <= '9') {
					if (yych <= '%') goto yy139;
					if (yych <= ')') goto yy164;
					if (yych <= '/') goto yy139;
					goto yy162;
				} else {
					if (yych == ';') goto yy164;
					if (yych <= '<') goto yy139;
					goto yy164;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych <= '@') goto yy139;
					if (yych == 'E') goto yy200;
					goto yy162;
				} else {
					if (yych <= ']') goto yy139;
					if (yych <= '^') goto yy164;
					if (yych <= '_') goto yy162;
					goto yy139;
				}
			} else {
				if (yych <= '{') {
					if (yych == 'e') goto yy200;
					if (yych <= 'z') goto yy162;
					goto yy139;
				} else {
					if (yych == '}') goto yy139;
					if (yych <= '~') goto yy164;
					goto yy139;
				}
			}
		}
yy199:
		YYDEBUG(199, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '=') {
			if (yych <= '"') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					goto yy164;
				} else {
					if (yych == '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					goto yy164;
				}
			} else {
				if (yych <= '9') {
					if (yych <= '%') goto yy139;
					if (yych <= ')') goto yy164;
					if (yych <= '/') goto yy139;
					goto yy162;
				} else {
					if (yych == ';') goto yy164;
					if (yych <= '<') goto yy139;
					goto yy164;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych <= '@') goto yy139;
					if (yych == 'L') goto yy204;
					goto yy162;
				} else {
					if (yych <= ']') goto yy139;
					if (yych <= '^') goto yy164;
					if (yych <= '_') goto yy162;
					goto yy139;
				}
			} else {
				if (yych <= '{') {
					if (yych == 'l') goto yy204;
					if (yych <= 'z') goto yy162;
					goto yy139;
				} else {
					if (yych == '}') goto yy139;
					if (yych <= '~') goto yy164;
					goto yy139;
				}
			}
		}
yy200:
		YYDEBUG(200, *YYCURSOR);
		yyaccept = 3;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yybm[0+yych] & 32) {
			goto yy162;
		}
		if (yych <= ')') {
			if (yych <= '\f') {
				if (yych <= 0x08) {
					if (yych <= 0x00) goto yy184;
					goto yy139;
				} else {
					if (yych <= '\t') goto yy196;
					if (yych <= '\n') goto yy184;
					goto yy139;
				}
			} else {
				if (yych <= ' ') {
					if (yych <= '\r') goto yy184;
					if (yych <= 0x1F) goto yy139;
					goto yy196;
				} else {
					if (yych <= '"') goto yy184;
					if (yych <= '%') goto yy139;
					goto yy184;
				}
			}
		} else {
			if (yych <= ']') {
				if (yych <= ';') {
					if (yych <= ':') goto yy139;
					goto yy184;
				} else {
					if (yych == '=') goto yy184;
					goto yy139;
				}
			} else {
				if (yych <= '|') {
					if (yych <= '^') goto yy184;
					if (yych <= '{') goto yy139;
					goto yy184;
				} else {
					if (yych == '~') goto yy184;
					goto yy139;
				}
			}
		}
yy201:
		YYDEBUG(201, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(202, *YYCURSOR);
		if (yych == '\t') goto yy201;
		if (yych == ' ') goto yy201;
		goto yy188;
yy203:
		YYDEBUG(203, *YYCURSOR);
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '=') {
			if (yych <= '"') {
				if (yych <= '\n') {
					if (yych <= 0x00) goto yy164;
					if (yych <= 0x08) goto yy139;
					goto yy164;
				} else {
					if (yych == '\r') goto yy164;
					if (yych <= 0x1F) goto yy139;
					goto yy164;
				}
			} else {
				if (yych <= '9') {
					if (yych <= '%') goto yy139;
					if (yych <= ')') goto yy164;
					if (yych <= '/') goto yy139;
					goto yy162;
				} else {
					if (yych == ';') goto yy164;
					if (yych <= '<') goto yy139;
					goto yy164;
				}
			}
		} else {
			if (yych <= '`') {
				if (yych <= 'Z') {
					if (yych <= '@') goto yy139;
					if (yych == 'E') goto yy187;
					goto yy162;
				} else {
					if (yych <= ']') goto yy139;
					if (yych <= '^') goto yy164;
					if (yych <= '_') goto yy162;
					goto yy139;
				}
			} else {
				if (yych <= '{') {
					if (yych == 'e') goto yy187;
					if (yych <= 'z') goto yy162;
					goto yy139;
				} else {
					if (yych == '}') goto yy139;
					if (yych <= '~') goto yy164;
					goto yy139;
				}
			}
		}
yy204:
		YYDEBUG(204, *YYCURSOR);
		yyaccept = 5;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yybm[0+yych] & 32) {
			goto yy162;
		}
		if (yych <= ')') {
			if (yych <= '\f') {
				if (yych <= 0x08) {
					if (yych >= 0x01) goto yy139;
				} else {
					if (yych <= '\t') goto yy206;
					if (yych >= '\v') goto yy139;
				}
			} else {
				if (yych <= ' ') {
					if (yych <= '\r') goto yy205;
					if (yych <= 0x1F) goto yy139;
					goto yy206;
				} else {
					if (yych <= '"') goto yy205;
					if (yych <= '%') goto yy139;
				}
			}
		} else {
			if (yych <= ']') {
				if (yych <= ';') {
					if (yych <= ':') goto yy139;
				} else {
					if (yych != '=') goto yy139;
				}
			} else {
				if (yych <= '|') {
					if (yych <= '^') goto yy205;
					if (yych <= '{') goto yy139;
				} else {
					if (yych != '~') goto yy139;
				}
			}
		}
yy205:
		YYDEBUG(205, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 477 "Zend/zend_ini_scanner.l"
		{
	RETURN_TOKEN(NULL_NULL, "", 0);
}
#line 3425 "Zend/zend_ini_scanner.c"
yy206:
		YYDEBUG(206, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(207, *YYCURSOR);
		if (yych == '\t') goto yy206;
		if (yych == ' ') goto yy206;
		goto yy205;
	}
/* *********************************** */
yyc_ST_SECTION_RAW:
	{
		static const unsigned char yybm[] = {
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64, 192,   0,  64,  64,   0,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			192,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,   0,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
		};
		YYDEBUG(208, *YYCURSOR);
		YYFILL(1);
		yych = *YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy210;
		}
		if (yych <= '\r') goto yy213;
		goto yy215;
yy210:
		YYDEBUG(210, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(211, *YYCURSOR);
		if (yybm[0+yych] & 64) {
			goto yy210;
		}
		YYDEBUG(212, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 537 "Zend/zend_ini_scanner.l"
		{ /* Raw value, only used when SCNG(scanner_mode) == ZEND_INI_SCANNER_RAW. */
	RETURN_TOKEN(TC_RAW, yytext, yyleng);
}
#line 3496 "Zend/zend_ini_scanner.c"
yy213:
		YYDEBUG(213, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(214, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 648 "Zend/zend_ini_scanner.l"
		{
	return 0;
}
#line 3506 "Zend/zend_ini_scanner.c"
yy215:
		YYDEBUG(215, *YYCURSOR);
		++YYCURSOR;
		YYFILL(2);
		yych = *YYCURSOR;
		YYDEBUG(216, *YYCURSOR);
		if (yybm[0+yych] & 128) {
			goto yy215;
		}
		if (yych <= 0x08) goto yy217;
		if (yych <= '\n') goto yy218;
		if (yych == '\r') goto yy219;
yy217:
		YYDEBUG(217, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 425 "Zend/zend_ini_scanner.l"
		{ /* End of section */
	BEGIN(INITIAL);
	SCNG(lineno)++;
	return ']';
}
#line 3528 "Zend/zend_ini_scanner.c"
yy218:
		YYDEBUG(218, *YYCURSOR);
		++YYCURSOR;
		goto yy217;
yy219:
		YYDEBUG(219, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy218;
		goto yy217;
	}
/* *********************************** */
yyc_ST_DOUBLE_QUOTES:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		YYDEBUG(220, *YYCURSOR);
		YYFILL(2);
		yych = *YYCURSOR;
		if (yych == '"') goto yy224;
		if (yych == '$') goto yy227;
		YYDEBUG(222, *YYCURSOR);
		++YYCURSOR;
yy223:
		YYDEBUG(223, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 587 "Zend/zend_ini_scanner.l"
		{ /* Escape double quoted string contents */
	if (YYCURSOR > YYLIMIT) {
		return 0;
	}

	while (YYCURSOR < YYLIMIT) {
		switch (*YYCURSOR++) {
			case '"':
				if (YYCURSOR < YYLIMIT && YYCURSOR[-2] == '\\' && *YYCURSOR != '\r' && *YYCURSOR != '\n') {
					continue;
				}
				break;
			case '$':
				if (*YYCURSOR == '{') {
					break;
				}
				continue;
			case '\\':
				if (YYCURSOR < YYLIMIT && *YYCURSOR != '"') {
					YYCURSOR++;
				}
				/* fall through */
			default:
				continue;
		}

		YYCURSOR--;
		break;
	}

	yyleng = YYCURSOR - SCNG(yy_text);

	zend_ini_escape_string(ini_lval, yytext, yyleng, '"');
	return TC_QUOTED_STRING;
}
#line 3622 "Zend/zend_ini_scanner.c"
yy224:
		YYDEBUG(224, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(225, *YYCURSOR);
		if (yybm[0+yych] & 128) {
			goto yy224;
		}
		YYDEBUG(226, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 582 "Zend/zend_ini_scanner.l"
		{ /* Double quoted '"' string ends */
	yy_pop_state();
	return '"';
}
#line 3639 "Zend/zend_ini_scanner.c"
yy227:
		YYDEBUG(227, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych != '{') goto yy223;
		YYDEBUG(228, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(229, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 449 "Zend/zend_ini_scanner.l"
		{ /* Variable start */
	yy_push_state(ST_VARNAME);
	return TC_DOLLAR_CURLY;
}
#line 3653 "Zend/zend_ini_scanner.c"
	}
/* *********************************** */
yyc_ST_VARNAME:
	{
		static const unsigned char yybm[] = {
			  0, 128, 128, 128, 128, 128, 128, 128, 
			128,   0,   0, 128, 128,   0, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128,   0,   0, 128,   0, 128,   0, 128, 
			  0,   0, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128,   0, 128,   0, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128,   0, 128, 128,   0, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128,   0,   0,   0,   0, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
		};
		YYDEBUG(230, *YYCURSOR);
		YYFILL(1);
		yych = *YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy234;
		}
		if (yych == '}') goto yy237;
		YYDEBUG(232, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(233, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 648 "Zend/zend_ini_scanner.l"
		{
	return 0;
}
#line 3707 "Zend/zend_ini_scanner.c"
yy234:
		YYDEBUG(234, *YYCURSOR);
		++YYCURSOR;
		YYFILL(1);
		yych = *YYCURSOR;
		YYDEBUG(235, *YYCURSOR);
		if (yybm[0+yych] & 128) {
			goto yy234;
		}
		YYDEBUG(236, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 454 "Zend/zend_ini_scanner.l"
		{ /* Variable name */
	/* Eat leading whitespace */
	EAT_LEADING_WHITESPACE();

	/* Eat trailing whitespace */
	EAT_TRAILING_WHITESPACE();

	RETURN_TOKEN(TC_VARNAME, yytext, yyleng);
}
#line 3729 "Zend/zend_ini_scanner.c"
yy237:
		YYDEBUG(237, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(238, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 464 "Zend/zend_ini_scanner.l"
		{ /* Variable end */
	yy_pop_state();
	return '}';
}
#line 3740 "Zend/zend_ini_scanner.c"
	}
/* *********************************** */
yyc_ST_RAW:
	{
		static const unsigned char yybm[] = {
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64, 192,   0,  64,  64,   0,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			192,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
		};
		YYDEBUG(239, *YYCURSOR);
		YYFILL(3);
		yych = *YYCURSOR;
		if (yych <= '\f') {
			if (yych <= 0x08) {
				if (yych >= 0x01) goto yy243;
			} else {
				if (yych <= '\t') goto yy245;
				if (yych <= '\n') goto yy246;
				goto yy243;
			}
		} else {
			if (yych <= ' ') {
				if (yych <= '\r') goto yy248;
				if (yych <= 0x1F) goto yy243;
				goto yy245;
			} else {
				if (yych == ';') goto yy249;
				goto yy243;
			}
		}
		YYDEBUG(241, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(242, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 643 "Zend/zend_ini_scanner.l"
		{ /* End of option value (if EOF is reached before EOL */
	BEGIN(INITIAL);
	return END_OF_LINE;
}
#line 3809 "Zend/zend_ini_scanner.c"
yy243:
		YYDEBUG(243, *YYCURSOR);
		++YYCURSOR;
yy244:
		YYDEBUG(244, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 500 "Zend/zend_ini_scanner.l"
		{ /* Raw value, only used when SCNG(scanner_mode) == ZEND_INI_SCANNER_RAW. */
	unsigned char *sc = NULL;
	while (YYCURSOR < YYLIMIT) {
		switch (*YYCURSOR) {
			case '\n':
			case '\r':
				goto end_raw_value_chars;
				break;
			case ';':
				if (sc == NULL) {
					sc = YYCURSOR;
				}
				/* no break */
			default:
				YYCURSOR++;
				break;
		}
	}
end_raw_value_chars:
	yyleng = YYCURSOR - SCNG(yy_text);

	/* Eat trailing semicolons */
	while (yytext[yyleng - 1] == ';') {
		yyleng--;
	}

	/* Eat leading and trailing double quotes */
	if (yyleng > 1 && yytext[0] == '"' && yytext[yyleng - 1] == '"') {
		SCNG(yy_text)++;
		yyleng = yyleng - 2;
	} else if (sc) {
		YYCURSOR = sc;
		yyleng = YYCURSOR - SCNG(yy_text);
	}
	RETURN_TOKEN(TC_RAW, yytext, yyleng);
}
#line 3853 "Zend/zend_ini_scanner.c"
yy245:
		YYDEBUG(245, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych <= '\r') {
			if (yych <= 0x08) goto yy244;
			if (yych <= '\n') goto yy252;
			if (yych <= '\f') goto yy244;
			goto yy252;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy244;
				goto yy252;
			} else {
				if (yych == ';') goto yy252;
				goto yy244;
			}
		}
yy246:
		YYDEBUG(246, *YYCURSOR);
		++YYCURSOR;
yy247:
		YYDEBUG(247, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 541 "Zend/zend_ini_scanner.l"
		{ /* End of option value */
	BEGIN(INITIAL);
	SCNG(lineno)++;
	return END_OF_LINE;
}
#line 3883 "Zend/zend_ini_scanner.c"
yy248:
		YYDEBUG(248, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy246;
		goto yy247;
yy249:
		YYDEBUG(249, *YYCURSOR);
		++YYCURSOR;
		YYFILL(2);
		yych = *YYCURSOR;
		YYDEBUG(250, *YYCURSOR);
		if (yybm[0+yych] & 64) {
			goto yy249;
		}
		if (yych <= '\n') goto yy254;
		goto yy256;
yy251:
		YYDEBUG(251, *YYCURSOR);
		++YYCURSOR;
		YYFILL(2);
		yych = *YYCURSOR;
yy252:
		YYDEBUG(252, *YYCURSOR);
		if (yybm[0+yych] & 128) {
			goto yy251;
		}
		if (yych <= '\f') {
			if (yych <= 0x08) goto yy253;
			if (yych <= '\n') goto yy246;
		} else {
			if (yych <= '\r') goto yy248;
			if (yych == ';') goto yy249;
		}
yy253:
		YYDEBUG(253, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 627 "Zend/zend_ini_scanner.l"
		{
	/* eat whitespace */
	goto restart;
}
#line 3925 "Zend/zend_ini_scanner.c"
yy254:
		YYDEBUG(254, *YYCURSOR);
		++YYCURSOR;
yy255:
		YYDEBUG(255, *YYCURSOR);
		yyleng = YYCURSOR - SCNG(yy_text);
#line 637 "Zend/zend_ini_scanner.l"
		{ /* Comment */
	BEGIN(INITIAL);
	SCNG(lineno)++;
	return END_OF_LINE;
}
#line 3938 "Zend/zend_ini_scanner.c"
yy256:
		YYDEBUG(256, *YYCURSOR);
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy254;
		goto yy255;
	}
}
#line 652 "Zend/zend_ini_scanner.l"

}
