name: Install
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        make install
        mkdir -p /etc/php.d
        chmod 777 /etc/php.d
        echo mysqli.default_socket=/var/run/mysqld/mysqld.sock > /etc/php.d/mysqli.ini
        echo pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock > /etc/php.d/pdo_mysql.ini
        echo opcache.enable_cli=1 >> /etc/php.d/opcache.ini
        echo opcache.protect_memory=1 >> /etc/php.d/opcache.ini
        echo opcache.preload_user=root >> /etc/php.d/opcache.ini
