name: Test
inputs:
  runTestsParameters:
    default: ''
    required: false
  enableOpcache:
    default: 'false'
    required: false
  jitType:
    default: 'disable'
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        export SKIP_IO_CAPTURE_TESTS=1
        export CI_NO_IPV6=1
        export STACK_LIMIT_DEFAULTS_CHECK=1
        sapi/cli/php run-tests.php -P -q ${{ inputs.runTestsParameters }} \
          ${{ inputs.enableOpcache == 'true' && '-d zend_extension=opcache.so -d opcache.enable_cli=1' || '' }} \
          -d opcache.jit=${{ inputs.jitType }} \
          -d opcache.jit_buffer_size=16M \
          -j$(($(sysctl -n hw.ncpu) - 1)) \
          -g FAIL,BORK,LEAK,XLEAK \
          --no-progress \
          --offline \
          --show-diff \
          --show-slow 1000 \
          --set-timeout 120
