name: Test
inputs:
  testArtifacts:
    default: null
    required: false
  runTestsParameters:
    default: ''
    required: false
  jitType:
    default: 'disable'
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        export SKIP_IO_CAPTURE_TESTS=1
        export CI_NO_IPV6=1
        export TEST_PHP_JUNIT=junit.out.xml
        export STACK_LIMIT_DEFAULTS_CHECK=1
        sapi/cli/php run-tests.php -P -q ${{ inputs.runTestsParameters }} \
          ${{ inputs.jitType == 'disable' && '' || '--repeat 2' }}
          -d opcache.jit=${{ inputs.jitType }} \
          -d opcache.protect_memory=1 \
          -d opcache.jit_buffer_size=64M \
          -d opcache.jit_max_root_traces=100000 \
          -d opcache.jit_max_side_traces=100000 \
          -d opcache.jit_max_exit_counters=100000 \
          -j$(sysctl -n hw.ncpu) \
          -g FAIL,BORK,LEAK,XLEAK \
          --no-progress \
          --offline \
          --show-diff \
          --show-slow 1000 \
          --set-timeout 120
    - uses: actions/upload-artifact@v3
      if: always() && inputs.testArtifacts != null
      with:
        name: ${{ github.job }}_${{ inputs.testArtifacts }}
        path: ${{ github.workspace }}/junit.out.xml
        retention-days: 5
