name: Test
inputs:
  runTestsParameters:
    default: ''
    required: false
  jitType:
    default: 'disable'
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        export SKIP_IO_CAPTURE_TESTS=1
        export CI_NO_IPV6=1
        sapi/cli/php run-tests.php -P -q ${{ inputs.runTestsParameters }} \
          -d opcache.jit=${{ inputs.jitType }} \
          -d opcache.protect_memory=1 \
          -d opcache.jit_buffer_size=64M \
          -d opcache.jit_max_root_traces=100000 \
          -d opcache.jit_max_side_traces=100000 \
          -d opcache.jit_max_exit_counters=100000 \
          -d opcache.jit_blacklist_root_trace=255 \
          -d opcache.jit_blacklist_side_trace=255 \
          -d opcache.file_update_protection=0 \
          -j$(sysctl -n hw.ncpu) \
          -g FAIL,XFAIL,BORK,WARN,LEAK,XLEAK,SKIP \
          --offline \
          --show-diff \
          --show-slow 1000 \
          --set-timeout 120
