<?php
if (!defined('IMAGETYPE_GIF'))     die('skip images of type GIF not supported');
if (!defined('IMAGETYPE_JPEG'))    die('skip images of type JPEG not supported');
if (!defined('IMAGETYPE_PNG'))     die('skip images of type PNG not supported');
if (!defined('IMAGETYPE_SWF'))     die('skip images of type SWF not supported');
if (!defined('IMAGETYPE_PSD'))     die('skip images of type PSD not supported');
if (!defined('IMAGETYPE_BMP'))     die('skip images of type BMP not supported');
if (!defined('IMAGETYPE_TIFF_II')) die('skip images of type TIFF not supported');
if (!defined('IMAGETYPE_TIFF_MM')) die('skip images of type TIFF not supported');
if (!defined('IMAGETYPE_JPC'))     die('skip images of type JPC not supported');
//if (!defined('IMAGETYPE_JP2'))     die('skip images of type JP2 not supported');
//if (!defined('IMAGETYPE_JPX'))     die('skip images of type JPX not supported');
//if (!defined('IMAGETYPE_JB2'))     die('skip images of type JB2 not supported');
if (!defined('IMAGETYPE_IFF'))     die('skip images of type IFF not supported');
?>
