TkMsgCatalog.new('::tkmsgcat_demo') {
    de 'Application Error', 'Applikationsfehler'
    de 'Blue', 'Blau'
    de 'Color', 'Farbe'
    de 'Delete', 'Löschen', 'iso8859-1'
    de 'Error', 'Fehler'
    de 'Exit', 'Ende'
    de 'Green', 'Grün', 'iso8859-1'
    de 'Red', 'Rot'
    de 'blue', 'blau'
    de 'green', 'grün', 'iso8859-1'
    de 'red', 'rot'
}

TkMsgCatalog.new('::tk') {
    de "&Abort", "&Abbruch"
    de "&About...", "&Über...", 'iso8859-1'
    de "All Files", "Alle Dateien"
    de "Application Error", "Applikationsfehler"
    de "&Blue", "&Blau"
    de "&Cancel", "&Abbruch"
    de "Cannot change to the directory \"%1\$s\".\nPermission denied.", "Kann nicht in das Verzeichnis \"%1\$s\" wechseln.\nKeine Rechte vorhanden."
    de "Choose Directory", "Wähle Verzeichnis", 'iso8859-1'
    de "&Clear", "&Rücksetzen", 'iso8859-1'
    de "&Clear Console", "&Konsole löschen", 'iso8859-1'
    de "Color", "Farbe"
    de "Console", "Konsole"
    de "&Copy", "&Kopieren"
    de "Cu&t", "Aus&schneiden"
    de '&Delete', '&Löschen', 'iso8859-1'
    de "Details >>"
    de "Directory \"%1\$s\" does not exist.", "Das Verzeichnis \"%1\$s\" existiert nicht."
    de "&Directory:", "&Verzeichnis:"
    de "&Edit", "&Bearbieten"
    de "Error: %1\$s", "Fehler: %1\$s"
    de "E&xit", "&Ende"
    de "&File", "&Datei"
    de "File \"%1\$s\" already exists.\nDo you want to overwrite it?", "Die Datei \"%1\$s\" ist bereits vorhanden.\nWollen sie diese Datei überschreiben ?", 'iso8859-1'
    de "File \"%1\$s\" already exists.\n\n", "Die Datei \"%1\$s\" ist bereits vorhanden.\n\n"
    de "File \"%1\$s\" does not exist.", "Die Datei \"%1\$s\" existiert nicht."
    de "File &name:", "Datei&name:"
    de "File &names:", "Datei&namen:"
    de "Files of &type:", "Dateien des &Typs:"
    de "Fi&les:", "Dat&eien:"
    de "&Filter"
    de "Fil&ter:"
    de '&Green', '&Grün', 'iso8859-1'
    de "&Help", "&Hilfe"
    de "Hi", "Hallo"
    de "&Hide Console", "&Konsole unsichtbar machen"
    de "&Ignore", "&Ignorieren"
    de "Invalid file name \"%1\$s\".", "Ungültiger Dateiname \"%1\$s\".", 'iso8859-1'
    de "Log Files", "Protokolldatei"
    de "&No", "&Nein"
    de "OK"
    de "Ok"
    de "Open", "Öffnen", 'iso8859-1'
    de "&Open", "Ö&ffnen", 'iso8859-1'
    de "Open Multiple Files"
    de "P&aste", "E&infügen", 'iso8859-1'
    de "&Quit", "&Beenden"
    de "&Red", "&Rot"
    de "Replace existing file?", "Existierende Datei ersetzen?"
    de "&Retry", "&Wiederholen"
    de "&Save", "&Speichern"
    de "Save As", "Speichern unter"
    de "Save To Log", "In Protokoll speichern"
    de "Select Log File", "Protokolldatei auswählen", 'iso8859-1'
    de "Select a file to source", "Auszuführende Datei auswählen", 'iso8859-1'
    de "&Selection:", "Auswah&l:"
    de "Skip Messages", "Weitere Nachrichten überspringen", 'iso8859-1'
    de "&Source...", "&Ausführen...", 'iso8859-1'
    de "Tcl Scripts", "Tcl-Skripte"
    de "Tcl for Windows", "Tcl für Windows", 'iso8859-1'
    de "Text Files", "Textdateien"
    de "&Yes", "&Ja"
    de "abort", "abbrechen"
    de "blue", "blau"
    de "cancel", "abbrechen"
    de "extension", "Erweiterung"
    de "extensions", "Erweiterungen"
    de 'green', 'grün', 'iso8859-1'
    de "ignore", "ignorieren"
    de "ok"
    de "red", "rot"
    de "retry", "wiederholen"
    de "yes", "ja"
}
