name: Install
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        make install
        mkdir     /etc/php.d
        chmod 777 /etc/php.d
        echo mysqli.default_socket=/var/run/mysqld/mysqld.sock    > /etc/php.d/mysqli.ini
        echo pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock > /etc/php.d/pdo_mysql.ini
        echo extension=oci8.so    > /etc/php.d/oci8.ini
        echo extension=pdo_oci.so > /etc/php.d/pdo_oci.ini
