TkMsgCatalog.new('::tkmsgcat_demo') {
    ja 'Application Error', '\u30A2\u30D7\u30EA\u30B1\u30FC\u30B7\u30E7\u30F3\u30A8\u30E9\u30FC'
    ja 'Blue',   '\u9752'
    ja 'Color',  '\u80CC\u666F\u8272'
    ja 'Delete', '\u6D88\u53BB'
    ja 'Error',  '\u30A8\u30E9\u30FC'
    ja 'Exit',   '\u7D42\u4E86'
    ja 'Green',  '\u7DD1'
    ja 'Red',    '\u8D64'
    ja 'blue',   '\u9752'
    ja 'green',  '\u7DD1'
    ja 'red',    '\u8D64'
}
