#define TK_END_OF_FILE                     1
#define TK_ILLEGAL                         2
#define TK_SPACE                           3
#define TK_UNCLOSED_STRING                 4
#define TK_COMMENT                         5
#define TK_FUNCTION                        6
#define TK_COLUMN                          7
#define TK_AGG_FUNCTION                    8
#define TK_SEMI                            9
#define TK_EXPLAIN                        10
#define TK_BEGIN                          11
#define TK_TRANSACTION                    12
#define TK_COMMIT                         13
#define TK_END                            14
#define TK_ROLLBACK                       15
#define TK_CREATE                         16
#define TK_TABLE                          17
#define TK_TEMP                           18
#define TK_LP                             19
#define TK_RP                             20
#define TK_AS                             21
#define TK_COMMA                          22
#define TK_ID                             23
#define TK_ABORT                          24
#define TK_AFTER                          25
#define TK_ASC                            26
#define TK_ATTACH                         27
#define TK_BEFORE                         28
#define TK_CASCADE                        29
#define TK_CLUSTER                        30
#define TK_CONFLICT                       31
#define TK_COPY                           32
#define TK_DATABASE                       33
#define TK_DEFERRED                       34
#define TK_DELIMITERS                     35
#define TK_DESC                           36
#define TK_DETACH                         37
#define TK_EACH                           38
#define TK_FAIL                           39
#define TK_FOR                            40
#define TK_GLOB                           41
#define TK_IGNORE                         42
#define TK_IMMEDIATE                      43
#define TK_INITIALLY                      44
#define TK_INSTEAD                        45
#define TK_LIKE                           46
#define TK_MATCH                          47
#define TK_KEY                            48
#define TK_OF                             49
#define TK_OFFSET                         50
#define TK_PRAGMA                         51
#define TK_RAISE                          52
#define TK_REPLACE                        53
#define TK_RESTRICT                       54
#define TK_ROW                            55
#define TK_STATEMENT                      56
#define TK_TRIGGER                        57
#define TK_VACUUM                         58
#define TK_VIEW                           59
#define TK_OR                             60
#define TK_AND                            61
#define TK_NOT                            62
#define TK_EQ                             63
#define TK_NE                             64
#define TK_ISNULL                         65
#define TK_NOTNULL                        66
#define TK_IS                             67
#define TK_BETWEEN                        68
#define TK_IN                             69
#define TK_GT                             70
#define TK_GE                             71
#define TK_LT                             72
#define TK_LE                             73
#define TK_BITAND                         74
#define TK_BITOR                          75
#define TK_LSHIFT                         76
#define TK_RSHIFT                         77
#define TK_PLUS                           78
#define TK_MINUS                          79
#define TK_STAR                           80
#define TK_SLASH                          81
#define TK_REM                            82
#define TK_CONCAT                         83
#define TK_UMINUS                         84
#define TK_UPLUS                          85
#define TK_BITNOT                         86
#define TK_STRING                         87
#define TK_JOIN_KW                        88
#define TK_INTEGER                        89
#define TK_CONSTRAINT                     90
#define TK_DEFAULT                        91
#define TK_FLOAT                          92
#define TK_NULL                           93
#define TK_PRIMARY                        94
#define TK_UNIQUE                         95
#define TK_CHECK                          96
#define TK_REFERENCES                     97
#define TK_COLLATE                        98
#define TK_ON                             99
#define TK_DELETE                         100
#define TK_UPDATE                         101
#define TK_INSERT                         102
#define TK_SET                            103
#define TK_DEFERRABLE                     104
#define TK_FOREIGN                        105
#define TK_DROP                           106
#define TK_UNION                          107
#define TK_ALL                            108
#define TK_INTERSECT                      109
#define TK_EXCEPT                         110
#define TK_SELECT                         111
#define TK_DISTINCT                       112
#define TK_DOT                            113
#define TK_FROM                           114
#define TK_JOIN                           115
#define TK_USING                          116
#define TK_ORDER                          117
#define TK_BY                             118
#define TK_GROUP                          119
#define TK_HAVING                         120
#define TK_LIMIT                          121
#define TK_WHERE                          122
#define TK_INTO                           123
#define TK_VALUES                         124
#define TK_VARIABLE                       125
#define TK_CASE                           126
#define TK_WHEN                           127
#define TK_THEN                           128
#define TK_ELSE                           129
#define TK_INDEX                          130
