/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: ae870a71e45d4cd590c24498f7fd88afe213b3b5 */

static void register_password_symbols(int module_number)
{
	REGISTER_STRING_CONSTANT("PASSWORD_DEFAULT", "2y", CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("PASSWORD_BCRYPT", "2y", CONST_PERSISTENT);
	REGISTER_STRING_CONSTANT("PASSWORD_YESCRYPT", "y", CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("PASSWORD_BCRYPT_DEFAULT_COST", PHP_PASSWORD_BCRYPT_COST, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("PASSWORD_YESCRYPT_DEFAULT_BLOCK_COUNT", PHP_PASSWORD_YESCRYPT_DEFAULT_BLOCK_COUNT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("PASSWORD_YESCRYPT_DEFAULT_BLOCK_SIZE", PHP_PASSWORD_YESCRYPT_DEFAULT_BLOCK_SIZE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("PASSWORD_YESCRYPT_DEFAULT_PARALLELISM", PHP_PASSWORD_YESCRYPT_DEFAULT_PARALLELISM, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("PASSWORD_YESCRYPT_DEFAULT_TIME", PHP_PASSWORD_YESCRYPT_DEFAULT_TIME, CONST_PERSISTENT);
#if defined(HAVE_ARGON2LIB)
	REGISTER_STRING_CONSTANT("PASSWORD_ARGON2I", "argon2i", CONST_PERSISTENT);
#endif
#if defined(HAVE_ARGON2LIB)
	REGISTER_STRING_CONSTANT("PASSWORD_ARGON2ID", "argon2id", CONST_PERSISTENT);
#endif
#if defined(HAVE_ARGON2LIB)
	REGISTER_STRING_CONSTANT("PASSWORD_ARGON2_PROVIDER", "standard", CONST_PERSISTENT);
#endif
#if defined(HAVE_ARGON2LIB)
	REGISTER_LONG_CONSTANT("PASSWORD_ARGON2_DEFAULT_MEMORY_COST", PHP_PASSWORD_ARGON2_MEMORY_COST, CONST_PERSISTENT);
#endif
#if defined(HAVE_ARGON2LIB)
	REGISTER_LONG_CONSTANT("PASSWORD_ARGON2_DEFAULT_TIME_COST", PHP_PASSWORD_ARGON2_TIME_COST, CONST_PERSISTENT);
#endif
#if defined(HAVE_ARGON2LIB)
	REGISTER_LONG_CONSTANT("PASSWORD_ARGON2_DEFAULT_THREADS", PHP_PASSWORD_ARGON2_THREADS, CONST_PERSISTENT);
#endif
}
