name: Test
inputs:
  runTestsParameters:
    default: ''
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        # XXX: Set up database tests?
        export SKIP_IO_CAPTURE_TESTS=1
        export STACK_LIMIT_DEFAULTS_CHECK=1
        sapi/cli/php run-tests.php -P -q ${{ inputs.runTestsParameters }} \
          -j$(nproc) \
          -g FAIL,BORK,LEAK,XLEAK \
          --no-progress \
          --show-diff \
          --show-slow 1000 \
          --set-timeout 120
