
/* state of change of a file in zip archive */
#define zip_state php_ziplib__zip_state
#define zip_error php_ziplib__zip_error
#define zip_dirent php_ziplib__zip_dirent
#define zip_cdir php_ziplib__zip_cdir
#define zip_source php_ziplib__zip_source
#define zip_entry php_ziplib__zip_entry

#define _zip_err_str php_ziplib___zip_err_str
#define _zip_nerr_str php_ziplib___zip_nerr_str
#define _zip_err_type php_ziplib___zip_err_type

#define _zip_cdir_free php_ziplib___zip_cdir_free
#define _zip_cdir_new php_ziplib___zip_cdir_new
#define _zip_cdir_write php_ziplib___zip_cdir_write

#define _zip_dirent_finalize php_ziplib___zip_dirent_finalize
#define _zip_dirent_init php_ziplib___zip_dirent_init
#define _zip_dirent_read php_ziplib___zip_dirent_read
#define _zip_dirent_write php_ziplib___zip_dirent_write

#define _zip_entry_free php_ziplib___zip_entry_free
#define _zip_entry_init php_ziplib___zip_entry_init
#define _zip_entry_new php_ziplib___zip_entry_new

#define _zip_error_clear php_ziplib___zip_error_clear
#define _zip_error_copy php_ziplib___zip_error_copy
#define _zip_error_fini php_ziplib___zip_error_fini
#define _zip_error_get php_ziplib___zip_error_get
#define _zip_error_init php_ziplib___zip_error_init
#define _zip_error_set php_ziplib___zip_error_set
#define _zip_error_strerror php_ziplib___zip_error_strerror

#define _zip_file_fillbuf php_ziplib___zip_file_fillbuf
#define _zip_file_get_offset php_ziplib___zip_file_get_offset

#define _zip_free php_ziplib___zip_free
#define _zip_get_name php_ziplib___zip_get_name
#define _zip_local_header_read php_ziplib___zip_local_header_read
#define _zip_memdup php_ziplib___zip_memdup
#define _zip_name_locate php_ziplib___zip_name_locate
#define _zip_new php_ziplib___zip_new
#define _zip_read2 php_ziplib___zip_read2
#define _zip_read4 php_ziplib___zip_read4
#define _zip_replace php_ziplib___zip_replace
#define _zip_set_name php_ziplib___zip_set_name
#define _zip_unchange php_ziplib___zip_unchange
#define _zip_unchange_data php_ziplib___zip_unchange_data
