name: apt
inputs:
  asan:
    default: false
    required: false
  skipSlow:
    default: false
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x

        OPCACHE_TLS_TESTS_DEPS="gcc clang lld"
        SLOW_EXTENSION_DEPS=""
        if [[ "${{ inputs.skipSlow }}" == "false" ]]; then
          SLOW_EXTENSION_DEPS="ldap-utils slapd libtidy-dev libenchant-2-dev libsasl2-dev"
          SLOW_EXTENSION_DEPS+=" libsqlite3-mod-spatialite libpq-dev libldap2-dev libsnmp-dev"
          SLOW_EXTENSION_DEPS+=" postgresql postgresql-contrib snmpd snmp-mibs-downloader"
          SLOW_EXTENSION_DEPS+=" freetds-dev unixodbc-dev libsqliteodbc firebird-dev"
        fi

        export DEBIAN_FRONTEND=noninteractive

        # Install sudo in Docker for consistent actions
        if ! type "sudo" > /dev/null; then
          apt-get update -y | true
          apt-get install -y sudo
        fi

        sudo apt-get update -y | true
        sudo apt-get install -y \
          autoconf \
          gcc \
          make \
          curl \
          unzip \
          bison \
          re2c \
          locales \
          openssl \
          language-pack-de \
          libgmp-dev \
          libicu-dev \
          libbz2-dev \
          libxpm-dev \
          libzip-dev \
          libsqlite3-dev \
          libwebp-dev \
          ${{ inputs.asan == 'false' && 'libavif-dev' || '' }} \
          libonig-dev \
          libcurl4-openssl-dev \
          libxml2-dev \
          libxslt1-dev \
          libedit-dev \
          libsodium-dev \
          libargon2-dev \
          libmm-dev \
          llvm \
          clang \
          dovecot-core \
          dovecot-pop3d \
          dovecot-imapd \
          sendmail \
          liblmdb-dev \
          libtokyocabinet-dev \
          libdb-dev \
          libqdbm-dev \
          libjpeg-dev \
          libpng-dev \
          libfreetype6-dev \
          $OPCACHE_TLS_TESTS_DEPS \
          $SLOW_EXTENSION_DEPS
