name: apt
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x

        if [ -f /etc/alpine-release ]; then
            apk update -q
            apk add \
                build-base \
                autoconf \
                unzip \
                bison \
                re2c \
                pkgconf \
                mysql-client \
                aspell-dev \
                hunspell-dev \
                hunspell-en \
                bzip2-dev \
                curl-dev \
                freetype-dev \
                gettext-dev \
                gnu-libiconv-dev \
                gmp-dev \
                icu-dev \
                jpeg-dev \
                libffi-dev \
                libpng-dev \
                libsodium-dev \
                libwebp-dev \
                libxml2-dev \
                libxpm-dev \
                libxslt-dev \
                libzip-dev \
                oniguruma-dev \
                openssl-dev \
                readline-dev \
                sqlite-dev \
                tidyhtml-dev \
                krb5-dev \
                gdbm-dev \
                lmdb-dev \
                argon2-dev \
                enchant2-dev \
                freetds-dev \
                imap-dev \
                net-snmp-dev \
                openldap-dev \
                unixodbc-dev \
                postgresql14-dev \
                tzdata \
                musl-locales \
                musl-locales-lang
        else
            export ENV DEBIAN_FRONTEND=noninteractive
            apt-get -y -qq update
            apt-get install -y -q \
                build-essential \
                autoconf \
                unzip \
                bison \
                re2c \
                locales \
                ldap-utils \
                openssl \
                slapd \
                mysql-client \
                language-pack-de \
                libgmp-dev \
                libicu-dev \
                libtidy-dev \
                libenchant-2-dev \
                libaspell-dev \
                libpspell-dev \
                libsasl2-dev \
                libxpm-dev \
                libzip-dev \
                libbz2-dev \
                libsqlite3-dev \
                libwebp-dev \
                libonig-dev \
                libkrb5-dev \
                libgssapi-krb5-2 \
                libcurl4-openssl-dev \
                libxml2-dev \
                libxslt1-dev \
                libpq-dev \
                libreadline-dev \
                libldap2-dev \
                libsodium-dev \
                libargon2-0-dev \
                libmm-dev \
                libsnmp-dev \
                postgresql \
                postgresql-contrib \
                snmpd \
                snmp-mibs-downloader \
                freetds-dev \
                unixodbc-dev \
                llvm \
                libc-client-dev \
                dovecot-core \
                dovecot-pop3d \
                dovecot-imapd \
                sendmail \
                firebird-dev \
                liblmdb-dev \
                libtokyocabinet-dev \
                libdb-dev \
                libqdbm-dev \
                libjpeg-dev \
                libpng-dev \
                libfreetype6-dev
        fi

        mkdir /opt/oracle
        wget -nv https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip
        unzip instantclient-basiclite-linuxx64.zip && rm instantclient-basiclite-linuxx64.zip
        wget -nv https://download.oracle.com/otn_software/linux/instantclient/instantclient-sdk-linuxx64.zip
        unzip instantclient-sdk-linuxx64.zip && rm instantclient-sdk-linuxx64.zip
        mv instantclient_*_* /opt/oracle/instantclient
        # interferes with libldap2 headers
        rm /opt/oracle/instantclient/sdk/include/ldap.h
        # fix debug build warning: zend_signal: handler was replaced for signal (2) after startup
        echo DISABLE_INTERRUPT=on > /opt/oracle/instantclient/network/admin/sqlnet.ora
        sudo sh -c 'echo /opt/oracle/instantclient >/etc/ld.so.conf.d/oracle-instantclient.conf && ldconfig'
