name: emerge
runs:
  using: composite
  steps:
    - shell: sh
      # This does nothing, as currently the Gentoo/ppc64 CI system is
      # not running jobs containerized.
      #
      # - libiconv is not used, glibc iconv is instead
      run: |
        for package in \
            sys-apps/util-linux \
            app-shells/bash \
            app-admin/sudo \
            dev-build/autoconf \
            app-arch/unzip \
            app-arch/tar \
            sys-devel/bison \
            dev-util/re2c \
            dev-util/pkgconf \
            app-arch/bzip2 \
            net-misc/curl \
            media-libs/freetype \
            sys-devel/gettext \
            dev-libs/gmp \
            dev-libs/icu \
            media-libs/libjpeg-turbo \
            dev-libs/libffi \
            media-libs/libpng \
            dev-libs/libsodium \
            media-libs/libwebp \
            dev-libs/libxml2 \
            x11-libs/libXpm \
            dev-libs/libxslt \
            dev-libs/libzip \
            dev-libs/oniguruma \
            dev-libs/openssl \
            dev-libs/libedit \
            dev-db/sqlite \
            app-text/htmltidy \
            sys-libs/gdbm \
            dev-db/qdbm \
            dev-db/tokyocabinet \
            dev-db/lmdb \
            app-crypt/argon2 \
            app-text/enchant \
            app-dicts/myspell-en \
            app-dicts/myspell-de \
            dev-db/freetds \
            net-analyzer/net-snmp \
            net-nds/openldap \
            dev-libs/cyrus-sasl \
            dev-db/unixODBC \
            dev-db/postgresql \
            ; do
          echo $package
          if ! portageq has_version / $package; then
            echo "need to install $package"
            exit 1
          fi
        done
