<?xml version="1.0" ?>
<definitions
    xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
    xmlns:si="http://soapinterop.org/xsd"
    xmlns:tns="http://linuxsrv.home/~dmitry/soap/test.wsdl"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    targetNamespace="http://linuxsrv.home/~dmitry/soap/test.wsdl">

  <message name="echoLongRequest">
    <part name="x" type="xsd:long" />
  </message>

  <message name="echoLongResponse">
    <part name="x" type="xsd:long" />
  </message>

  <portType name="TestServicePortType">
    <operation name="echoLong">
      <input message="tns:echoLongRequest" />
      <output message="tns:echoLongResponse" />
    </operation>
  </portType>

  <binding name="TestServiceBinding" type="tns:TestServicePortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="echoLong">
      <soap:operation style="rpc" />
      <input>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </input>
      <output>
        <soap:body use="encoded" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
      </output>
    </operation>
  </binding>

  <service name="TestService">
    <port name="TestServicePort" binding="tns:TestServiceBinding">
      <soap:address location="test://" />
    </port>
  </service>

</definitions>
