<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://sova.pronto.ru/" xmlns:xsd1="http://sova.pronto.ru/schema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="sova" targetNamespace="http://sova.pronto.ru/">
  <wsdl:message name="authToken">
  	<wsdl:part name="authToken" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="message">
  	<wsdl:part name="param" type="xsd:string"/>
  </wsdl:message>
      
  <wsdl:portType name="sova">
    <wsdl:operation name="testHeader">
      <wsdl:input message="tns:message"/>
      <wsdl:output message="tns:message"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="sovaSOAP" type="tns:sova">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    
    <wsdl:operation name="testHeader">
      <soap:operation soapAction="http://sova.pronto.ru/testHeader"/>
      <wsdl:input>
        <soap:body namespace="http://sova.pronto.ru/" use="literal"/>
        <soap:header use="literal" part="authToken" message="tns:authToken" wsdl:required="true"/>
      </wsdl:input>
	  <wsdl:output>
        <soap:body namespace="http://sova.pronto.ru/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    
  </wsdl:binding>
  <wsdl:service name="sova">
    <wsdl:port binding="tns:sovaSOAP" name="sovaSOAP">
      <soap:address location="http://sova.mephius.prontosoft.by/sova/soaptest.php"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
