#!/usr/bin/expect -f
spawn tests/conv_encoding Japanese CP50220raw eucJP-win
set timeout 1

expect_after {
    "\[^\r\n\]*\r\n" { fail $test }
}

set test "81 - 87ku"
send "\xf5\xba\xf6\xec\xf7\xc9\xf8\xb3\xf9\xa1\xfa\xa1\xfb\xa1\r"
expect {
    "%1b%24%42%75%3a%76%6c%77%49%78%33%79%21%7a%21%7b%21%1b%28%42 (20)\r\n" { pass $test }
}


set test "kanji + kana"
send "ÆüËÜ¸ì¥Æ¥¹¥È\r"
expect {
    "%1b%24%42%46%7c%4b%5c%38%6c%25%46%25%39%25%48%1b%28%42 (18)\r\n" { pass $test }
}

set test "full-width numerics"
send "£°£±£²£³£´£µ£¶£·£¸£¹\r"
expect {
    "%1b%24%42%23%30%23%31%23%32%23%33%23%34%23%35%23%36%23%37%23%38%23%39%1b%28%42 (26)\r\n" { pass $test }
}

set test "full-width numerics"
send "­Î"
expect {
    "%1b%24%42%2d%42%1b%28%42 (8)\r\n" { pass $test }
}

