#!/usr/bin/expect -f
spawn tests/conv_encoding Japanese Shift_JIS UTF-8
set timeout 1

expect_after {
    "\[^\r\n\]*\r\n" { fail $test }
}

set test "basic test"
send "testtest\r"
expect {
    "%74%65%73%74%74%65%73%74 (8)\r\n" { pass $test }
}


set test "kanji + kana"
send "日本語テスト\r"
expect {
    "%93%fa%96%7b%8c%ea%83%65%83%58%83%67 (12)\r\n" { pass $test }
}

set test "full-width numerics"
send "０１２３４５６７８９\r"
expect {
    "%82%4f%82%50%82%51%82%52%82%53%82%54%82%55%82%56%82%57%82%58 (20)\r\n" { pass $test }
}

set test "full-width numerics"
send "㍊"
expect {
    "%3f (1)\r\n" { pass $test }
}

close
# vim: sts=4 ts=4 sw=4 et encoding=EUC-JP
