#!/bin/sh
export SCRIPT_NAME=/frontcontroller9.php
export PATH_INFO=/hi
export SCRIPT_FILENAME=/home/cellog/workspace/php5/ext/phar/tests/cache_list/frontcontroller9.php
export PATH_TRANSLATED=/home/cellog/workspace/php5/ext/phar/tests/cache_list/frontcontroller9.php
export REDIRECT_STATUS=1
export REQUEST_METHOD=GET
export REQUEST_URI=/frontcontroller9.php/hi
cd /home/cellog/workspace/php5/ext/phar/tests/cache_list
ddd ../../../../sapi/cgi/php-cgi &
cd /home/cellog/workspace/php5/ext/phar
