#!/bin/sh
export SCRIPT_NAME=/frontcontroller21.php
export PATH_INFO=/index.php
export SCRIPT_FILENAME=/home/user/workspace/phpsvn/php/php-src/trunk/ext/phar/tests/frontcontroller21.php
export PATH_TRANSLATED=/home/user/workspace/phpsvn/php/php-src/trunk/ext/phar/tests/frontcontroller21.php
export REDIRECT_STATUS=1
export REQUEST_METHOD=GET
export REQUEST_URI=/frontcontroller21.php/index.php?test=hi
cd /home/user/workspace/phpsvn/php/php-src/trunk/
ddd sapi/cgi/php-cgi &
cd /home/user/workspace/phpsvn/php/php-src/trunk/ext/phar
