name: apt
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x

        sudo apt-get update
        sudo apt-get install \
          bison \
          re2c \
          locales \
          ldap-utils \
          openssl \
          slapd \
          language-pack-de \
          libgmp-dev \
          libicu-dev \
          libtidy-dev \
          libenchant-2-dev \
          libaspell-dev \
          libpspell-dev \
          libsasl2-dev \
          libxpm-dev \
          libzip-dev \
          libsqlite3-dev \
          libwebp-dev \
          libonig-dev \
          libkrb5-dev \
          libgssapi-krb5-2 \
          libcurl4-openssl-dev \
          libxml2-dev \
          libxslt1-dev \
          libpq-dev \
          libreadline-dev \
          libldap2-dev \
          libsodium-dev \
          libargon2-0-dev \
          libmm-dev \
          libsnmp-dev \
          postgresql \
          postgresql-contrib \
          snmpd \
          snmp-mibs-downloader \
          freetds-dev \
          unixodbc-dev \
          llvm \
          libc-client-dev \
          dovecot-core \
          dovecot-pop3d \
          dovecot-imapd \
          sendmail \
          firebird-dev \
          liblmdb-dev \
          libtokyocabinet-dev \
          libdb-dev \
          libqdbm-dev \
          libjpeg-dev \
          libpng-dev \
          libfreetype6-dev

        mkdir /opt/oracle
        wget -nv https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip
        unzip instantclient-basiclite-linuxx64.zip && rm instantclient-basiclite-linuxx64.zip
        wget -nv https://download.oracle.com/otn_software/linux/instantclient/instantclient-sdk-linuxx64.zip
        unzip instantclient-sdk-linuxx64.zip && rm instantclient-sdk-linuxx64.zip
        mv instantclient_*_* /opt/oracle/instantclient
        # interferes with libldap2 headers
        rm /opt/oracle/instantclient/sdk/include/ldap.h
        # fix debug build warning: zend_signal: handler was replaced for signal (2) after startup
        echo DISABLE_INTERRUPT=on > /opt/oracle/instantclient/network/admin/sqlnet.ora
        sudo sh -c 'echo /opt/oracle/instantclient >/etc/ld.so.conf.d/oracle-instantclient.conf && ldconfig'
