name: Setup
runs:
  using: composite
  steps:
    - name: Setup MySQL
      shell: cmd
      run: |
        mysqld --initialize-insecure
        mysqld --install
        net start MySQL
        mysql --port=3306 --user=root --password="" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Password12!'; FLUSH PRIVILEGES;"
    - name: Setup MSSQL
      shell: cmd
      run: |
        curl -Ls -o SQL2022-SSEI-Expr.exe https://download.microsoft.com/download/5/1/4/5145fe04-4d30-4b85-b0d1-39533663a2f1/SQL2022-SSEI-Expr.exe
        SQL2022-SSEI-Expr.exe /Action=Download /MediaPath="%TEMP%" /MediaType=Core /ENU /Quiet
        %TEMP%\SQLEXPR_x64_ENU.exe /X:%TEMP%\Media /QS
        %TEMP%\Media\setup.exe /Q /IACCEPTSQLSERVERLICENSETERMS /ACTION="install" /FEATURES=SQLEngine /INSTANCENAME=SQLEXPRESS /SQLSVCACCOUNT="NT AUTHORITY\SYSTEM" /SQLSYSADMINACCOUNTS="BUILTIN\ADMINISTRATORS" /SAPWD="Password12!" /SECURITYMODE=SQL /ERRORREPORTING=0
    - name: Setup PostgreSQL
      shell: pwsh
      run: |
        Set-Service -Name "postgresql-x64-14" -StartupType manual -Status Running
        pwsh -Command { $env:PGPASSWORD="root"; & "$env:PGBIN\psql" -U postgres -c "ALTER USER postgres WITH PASSWORD 'Password12!';" }
