/* This is a generated file, edit the .stub.php file instead. */

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_Reflection_getModifierNames, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, modifiers, IS_LONG, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_Reflection_export, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, reflector, Reflector, 0)
	ZEND_ARG_TYPE_INFO(0, return, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_Reflector___toString, 0, 0, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionFunctionAbstract___clone arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_inNamespace arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_isClosure arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_isDeprecated arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_isInternal arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_isUserDefined arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_isGenerator arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_isVariadic arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getClosureThis arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getClosureScopeClass arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getDocComment arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getEndLine arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getExtension arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getExtensionName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getFileName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getNamespaceName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getNumberOfParameters arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getNumberOfRequiredParameters arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getParameters arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getShortName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getStartLine arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getStaticVariables arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_returnsReference arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_hasReturnType arginfo_class_Reflector___toString

#define arginfo_class_ReflectionFunctionAbstract_getReturnType arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionFunction___construct, 0, 0, 1)
	ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionFunction___toString arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionFunction_export, 0, 0, 1)
	ZEND_ARG_INFO(0, name)
	ZEND_ARG_TYPE_INFO(0, return, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionFunction_isDisabled arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionFunction_invoke, 0, 0, 0)
	ZEND_ARG_VARIADIC_INFO(0, args)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionFunction_invokeArgs, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, args, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionFunction_getClosure arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionGenerator___construct, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, generator, Generator, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionGenerator_getExecutingLine arginfo_class_Reflector___toString

#define arginfo_class_ReflectionGenerator_getExecutingFile arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionGenerator_getTrace, 0, 0, 0)
	ZEND_ARG_TYPE_INFO(0, options, IS_LONG, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionGenerator_getFunction arginfo_class_Reflector___toString

#define arginfo_class_ReflectionGenerator_getThis arginfo_class_Reflector___toString

#define arginfo_class_ReflectionGenerator_getExecutingGenerator arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionMethod___construct, 0, 0, 1)
	ZEND_ARG_INFO(0, class_or_method)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionMethod___toString arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionMethod_export, 0, 0, 2)
	ZEND_ARG_INFO(0, class)
	ZEND_ARG_INFO(0, name)
	ZEND_ARG_TYPE_INFO(0, return, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionMethod_isPublic arginfo_class_Reflector___toString

#define arginfo_class_ReflectionMethod_isPrivate arginfo_class_Reflector___toString

#define arginfo_class_ReflectionMethod_isProtected arginfo_class_Reflector___toString

#define arginfo_class_ReflectionMethod_isAbstract arginfo_class_Reflector___toString

#define arginfo_class_ReflectionMethod_isFinal arginfo_class_Reflector___toString

#define arginfo_class_ReflectionMethod_isStatic arginfo_class_Reflector___toString

#define arginfo_class_ReflectionMethod_isConstructor arginfo_class_Reflector___toString

#define arginfo_class_ReflectionMethod_isDestructor arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionMethod_getClosure, 0, 0, 0)
	ZEND_ARG_INFO(0, object)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionMethod_getModifiers arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionMethod_invoke, 0, 0, 0)
	ZEND_ARG_TYPE_INFO(0, object, IS_OBJECT, 1)
	ZEND_ARG_VARIADIC_INFO(0, args)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionMethod_invokeArgs, 0, 0, 2)
	ZEND_ARG_TYPE_INFO(0, object, IS_OBJECT, 1)
	ZEND_ARG_TYPE_INFO(0, args, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionMethod_getDeclaringClass arginfo_class_Reflector___toString

#define arginfo_class_ReflectionMethod_getPrototype arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionMethod_setAccessible, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, visible, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionClass___clone arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionClass_export, 0, 0, 1)
	ZEND_ARG_INFO(0, argument)
	ZEND_ARG_TYPE_INFO(0, return, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionClass___construct, 0, 0, 1)
	ZEND_ARG_INFO(0, argument)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionClass___toString arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_isInternal arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_isUserDefined arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_isAnonymous arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_isInstantiable arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_isCloneable arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getFileName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getStartLine arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getEndLine arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getDocComment arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getConstructor arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionClass_hasMethod, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionClass_getMethod arginfo_class_ReflectionClass_hasMethod

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionClass_getMethods, 0, 0, 0)
	ZEND_ARG_TYPE_INFO(0, filter, IS_LONG, 1)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionClass_hasProperty arginfo_class_ReflectionClass_hasMethod

#define arginfo_class_ReflectionClass_getProperty arginfo_class_ReflectionClass_hasMethod

#define arginfo_class_ReflectionClass_getProperties arginfo_class_ReflectionClass_getMethods

#define arginfo_class_ReflectionClass_hasConstant arginfo_class_ReflectionClass_hasMethod

#define arginfo_class_ReflectionClass_getConstants arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getReflectionConstants arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getConstant arginfo_class_ReflectionClass_hasMethod

#define arginfo_class_ReflectionClass_getReflectionConstant arginfo_class_ReflectionClass_hasMethod

#define arginfo_class_ReflectionClass_getInterfaces arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getInterfaceNames arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_isInterface arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getTraits arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getTraitNames arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getTraitAliases arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_isTrait arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_isAbstract arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_isFinal arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getModifiers arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionClass_isIntance, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, object, IS_OBJECT, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionClass_newInstance arginfo_class_ReflectionFunction_invoke

#define arginfo_class_ReflectionClass_newInstanceWithoutConstructor arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionClass_newInstanceArgs, 0, 0, 0)
	ZEND_ARG_TYPE_INFO(0, args, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionClass_getParentClass arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionClass_isSubclassOf, 0, 0, 1)
	ZEND_ARG_INFO(0, class)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionClass_getStaticProperties arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionClass_getStaticPropertyValue, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
	ZEND_ARG_INFO(0, default)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionClass_setStaticPropertyValue, 0, 0, 2)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionClass_getDefaultProperties arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_isIterable arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_isIterateable arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionClass_implementsInterface, 0, 0, 1)
	ZEND_ARG_INFO(0, interface)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionClass_getExtension arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getExtensionName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_inNamespace arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getNamespaceName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClass_getShortName arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionObject___construct, 0, 0, 1)
	ZEND_ARG_TYPE_INFO(0, argument, IS_OBJECT, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionObject_export arginfo_class_ReflectionClass_export

#define arginfo_class_ReflectionProperty___clone arginfo_class_Reflector___toString

#define arginfo_class_ReflectionProperty_export arginfo_class_ReflectionMethod_export

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionProperty___construct, 0, 0, 2)
	ZEND_ARG_INFO(0, class)
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionProperty___toString arginfo_class_Reflector___toString

#define arginfo_class_ReflectionProperty_getName arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionProperty_getValue, 0, 0, 0)
	ZEND_ARG_TYPE_INFO(0, object, IS_OBJECT, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionProperty_setValue, 0, 0, 1)
	ZEND_ARG_INFO(0, object_or_value)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionProperty_isInitialized, 0, 0, 0)
	ZEND_ARG_TYPE_INFO(0, object, IS_OBJECT, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionProperty_isPublic arginfo_class_Reflector___toString

#define arginfo_class_ReflectionProperty_isPrivate arginfo_class_Reflector___toString

#define arginfo_class_ReflectionProperty_isProtected arginfo_class_Reflector___toString

#define arginfo_class_ReflectionProperty_isStatic arginfo_class_Reflector___toString

#define arginfo_class_ReflectionProperty_isDefault arginfo_class_Reflector___toString

#define arginfo_class_ReflectionProperty_getModifiers arginfo_class_Reflector___toString

#define arginfo_class_ReflectionProperty_getDeclaringClass arginfo_class_Reflector___toString

#define arginfo_class_ReflectionProperty_getDocComment arginfo_class_Reflector___toString

#define arginfo_class_ReflectionProperty_setAccessible arginfo_class_ReflectionMethod_setAccessible

#define arginfo_class_ReflectionProperty_getType arginfo_class_Reflector___toString

#define arginfo_class_ReflectionProperty_hasType arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClassConstant___clone arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClassConstant_export arginfo_class_ReflectionMethod_export

#define arginfo_class_ReflectionClassConstant___construct arginfo_class_ReflectionProperty___construct

#define arginfo_class_ReflectionClassConstant___toString arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClassConstant_getName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClassConstant_getValue arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClassConstant_isPublic arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClassConstant_isPrivate arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClassConstant_isProtected arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClassConstant_getModifiers arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClassConstant_getDeclaringClass arginfo_class_Reflector___toString

#define arginfo_class_ReflectionClassConstant_getDocComment arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter___clone arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionParameter_export, 0, 0, 2)
	ZEND_ARG_INFO(0, function)
	ZEND_ARG_INFO(0, parameter)
	ZEND_ARG_TYPE_INFO(0, return, _IS_BOOL, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_ReflectionParameter___construct, 0, 0, 2)
	ZEND_ARG_INFO(0, function)
	ZEND_ARG_INFO(0, parameter)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionParameter___toString arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_getName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_isPassedByReference arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_canBePassedByValue arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_getDeclaringFunction arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_getDeclaringClass arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_getClass arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_hasType arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_getType arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_isArray arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_isCallable arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_allowsNull arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_getPosition arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_isOptional arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_isDefaultValueAvailable arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_getDefaultValue arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_isDefaultValueConstant arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_getDefaultValueConstantName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionParameter_isVariadic arginfo_class_Reflector___toString

#define arginfo_class_ReflectionType___clone arginfo_class_Reflector___toString

#define arginfo_class_ReflectionType_allowsNull arginfo_class_Reflector___toString

#define arginfo_class_ReflectionType___toString arginfo_class_Reflector___toString

#define arginfo_class_ReflectionNamedType_getName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionNamedType_isBuiltin arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_ReflectionUnionType_getTypes, 0, 0, IS_ARRAY, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionExtension___clone arginfo_class_Reflector___toString

#define arginfo_class_ReflectionExtension_export arginfo_class_ReflectionFunction_export

#define arginfo_class_ReflectionExtension___construct arginfo_class_ReflectionClass_hasMethod

#define arginfo_class_ReflectionExtension___toString arginfo_class_Reflector___toString

#define arginfo_class_ReflectionExtension_getName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionExtension_getVersion arginfo_class_Reflector___toString

#define arginfo_class_ReflectionExtension_getFunctions arginfo_class_Reflector___toString

#define arginfo_class_ReflectionExtension_getConstants arginfo_class_Reflector___toString

#define arginfo_class_ReflectionExtension_getINIEntries arginfo_class_Reflector___toString

#define arginfo_class_ReflectionExtension_getClasses arginfo_class_Reflector___toString

#define arginfo_class_ReflectionExtension_getClassNames arginfo_class_Reflector___toString

#define arginfo_class_ReflectionExtension_getDependencies arginfo_class_Reflector___toString

#define arginfo_class_ReflectionExtension_info arginfo_class_Reflector___toString

#define arginfo_class_ReflectionExtension_isPersistent arginfo_class_Reflector___toString

#define arginfo_class_ReflectionExtension_isTemporary arginfo_class_Reflector___toString

#define arginfo_class_ReflectionZendExtension___clone arginfo_class_Reflector___toString

#define arginfo_class_ReflectionZendExtension_export arginfo_class_ReflectionFunction_export

#define arginfo_class_ReflectionZendExtension___construct arginfo_class_ReflectionClass_hasMethod

#define arginfo_class_ReflectionZendExtension___toString arginfo_class_Reflector___toString

#define arginfo_class_ReflectionZendExtension_getName arginfo_class_Reflector___toString

#define arginfo_class_ReflectionZendExtension_getVersion arginfo_class_Reflector___toString

#define arginfo_class_ReflectionZendExtension_getAuthor arginfo_class_Reflector___toString

#define arginfo_class_ReflectionZendExtension_getURL arginfo_class_Reflector___toString

#define arginfo_class_ReflectionZendExtension_getCopyright arginfo_class_Reflector___toString

ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_ReflectionReference_fromArrayElement, 0, 2, ReflectionReference, 1)
	ZEND_ARG_TYPE_INFO(0, array, IS_ARRAY, 0)
	ZEND_ARG_INFO(0, key)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_ReflectionReference_getId, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_ReflectionReference___clone arginfo_class_Reflector___toString

#define arginfo_class_ReflectionReference___construct arginfo_class_Reflector___toString
