--TEST--
Test parsing of INI "size" values (e.g. "16M")
--FILE--
<?php

// This test checks valid formats do not throw any warnings.
foreach (['', ' '] as $leadingWS) {
  foreach (['', '+', '-'] as $sign) {
    foreach (['', ' '] as $midWS) {
      foreach (['', 'K', 'k', 'M', 'm', 'G', 'g'] as $exp) {
        foreach (['', ' '] as $trailingWS) {
          $setting = sprintf('%s%s1%s%s%s',
                             $leadingWS, $sign, $midWS, $exp, $trailingWS);
          var_dump($setting);

          // Technically, negative values don't make sense for socket timeout,
          // but it doesn't validate that so use it anyway.
          ini_set('default_socket_timeout', $setting);
        }
      }
    }
  }
}

--EXPECT--
string(1) "1"
string(2) "1 "
string(2) "1K"
string(3) "1K "
string(2) "1k"
string(3) "1k "
string(2) "1M"
string(3) "1M "
string(2) "1m"
string(3) "1m "
string(2) "1G"
string(3) "1G "
string(2) "1g"
string(3) "1g "
string(2) "1 "
string(3) "1  "
string(3) "1 K"
string(4) "1 K "
string(3) "1 k"
string(4) "1 k "
string(3) "1 M"
string(4) "1 M "
string(3) "1 m"
string(4) "1 m "
string(3) "1 G"
string(4) "1 G "
string(3) "1 g"
string(4) "1 g "
string(2) "+1"
string(3) "+1 "
string(3) "+1K"
string(4) "+1K "
string(3) "+1k"
string(4) "+1k "
string(3) "+1M"
string(4) "+1M "
string(3) "+1m"
string(4) "+1m "
string(3) "+1G"
string(4) "+1G "
string(3) "+1g"
string(4) "+1g "
string(3) "+1 "
string(4) "+1  "
string(4) "+1 K"
string(5) "+1 K "
string(4) "+1 k"
string(5) "+1 k "
string(4) "+1 M"
string(5) "+1 M "
string(4) "+1 m"
string(5) "+1 m "
string(4) "+1 G"
string(5) "+1 G "
string(4) "+1 g"
string(5) "+1 g "
string(2) "-1"
string(3) "-1 "
string(3) "-1K"
string(4) "-1K "
string(3) "-1k"
string(4) "-1k "
string(3) "-1M"
string(4) "-1M "
string(3) "-1m"
string(4) "-1m "
string(3) "-1G"
string(4) "-1G "
string(3) "-1g"
string(4) "-1g "
string(3) "-1 "
string(4) "-1  "
string(4) "-1 K"
string(5) "-1 K "
string(4) "-1 k"
string(5) "-1 k "
string(4) "-1 M"
string(5) "-1 M "
string(4) "-1 m"
string(5) "-1 m "
string(4) "-1 G"
string(5) "-1 G "
string(4) "-1 g"
string(5) "-1 g "
string(2) " 1"
string(3) " 1 "
string(3) " 1K"
string(4) " 1K "
string(3) " 1k"
string(4) " 1k "
string(3) " 1M"
string(4) " 1M "
string(3) " 1m"
string(4) " 1m "
string(3) " 1G"
string(4) " 1G "
string(3) " 1g"
string(4) " 1g "
string(3) " 1 "
string(4) " 1  "
string(4) " 1 K"
string(5) " 1 K "
string(4) " 1 k"
string(5) " 1 k "
string(4) " 1 M"
string(5) " 1 M "
string(4) " 1 m"
string(5) " 1 m "
string(4) " 1 G"
string(5) " 1 G "
string(4) " 1 g"
string(5) " 1 g "
string(3) " +1"
string(4) " +1 "
string(4) " +1K"
string(5) " +1K "
string(4) " +1k"
string(5) " +1k "
string(4) " +1M"
string(5) " +1M "
string(4) " +1m"
string(5) " +1m "
string(4) " +1G"
string(5) " +1G "
string(4) " +1g"
string(5) " +1g "
string(4) " +1 "
string(5) " +1  "
string(5) " +1 K"
string(6) " +1 K "
string(5) " +1 k"
string(6) " +1 k "
string(5) " +1 M"
string(6) " +1 M "
string(5) " +1 m"
string(6) " +1 m "
string(5) " +1 G"
string(6) " +1 G "
string(5) " +1 g"
string(6) " +1 g "
string(3) " -1"
string(4) " -1 "
string(4) " -1K"
string(5) " -1K "
string(4) " -1k"
string(5) " -1k "
string(4) " -1M"
string(5) " -1M "
string(4) " -1m"
string(5) " -1m "
string(4) " -1G"
string(5) " -1G "
string(4) " -1g"
string(5) " -1g "
string(4) " -1 "
string(5) " -1  "
string(5) " -1 K"
string(6) " -1 K "
string(5) " -1 k"
string(6) " -1 k "
string(5) " -1 M"
string(6) " -1 M "
string(5) " -1 m"
string(6) " -1 m "
string(5) " -1 G"
string(6) " -1 G "
string(5) " -1 g"
string(6) " -1 g "
