/* This is a generated file, edit the .stub.php file instead.
 * Stub hash: 33e2f6f12083668388d80dbd77d97fd3f1efbe39 */

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_StreamException_getParam, 0, 0, IS_STRING, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_class_StreamException_getWrapperName, 0, 0, IS_STRING, 0)
ZEND_END_ARG_INFO()

static ZEND_METHOD(StreamException, getParam);
static ZEND_METHOD(StreamException, getWrapperName);

static const zend_function_entry class_StreamException_methods[] = {
	ZEND_ME(StreamException, getParam, arginfo_class_StreamException_getParam, ZEND_ACC_PUBLIC)
	ZEND_ME(StreamException, getWrapperName, arginfo_class_StreamException_getWrapperName, ZEND_ACC_PUBLIC)
	ZEND_FE_END
};

static void register_stream_errors_symbols(int module_number)
{
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_NONE", STREAM_ERROR_CODE_NONE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_GENERIC", STREAM_ERROR_CODE_GENERIC, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_READ_FAILED", STREAM_ERROR_CODE_READ_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_WRITE_FAILED", STREAM_ERROR_CODE_WRITE_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_SEEK_FAILED", STREAM_ERROR_CODE_SEEK_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_SEEK_NOT_SUPPORTED", STREAM_ERROR_CODE_SEEK_NOT_SUPPORTED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_FLUSH_FAILED", STREAM_ERROR_CODE_FLUSH_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_TRUNCATE_FAILED", STREAM_ERROR_CODE_TRUNCATE_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_NOT_WRITABLE", STREAM_ERROR_CODE_NOT_WRITABLE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_NOT_READABLE", STREAM_ERROR_CODE_NOT_READABLE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_NOT_FOUND", STREAM_ERROR_CODE_NOT_FOUND, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_PERMISSION_DENIED", STREAM_ERROR_CODE_PERMISSION_DENIED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_ALREADY_EXISTS", STREAM_ERROR_CODE_ALREADY_EXISTS, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_INVALID_PATH", STREAM_ERROR_CODE_INVALID_PATH, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_PATH_TOO_LONG", STREAM_ERROR_CODE_PATH_TOO_LONG, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_UNLINK_FAILED", STREAM_ERROR_CODE_UNLINK_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_RENAME_FAILED", STREAM_ERROR_CODE_RENAME_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_MKDIR_FAILED", STREAM_ERROR_CODE_MKDIR_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_RMDIR_FAILED", STREAM_ERROR_CODE_RMDIR_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_STAT_FAILED", STREAM_ERROR_CODE_STAT_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_CHMOD_FAILED", STREAM_ERROR_CODE_CHMOD_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_CHOWN_FAILED", STREAM_ERROR_CODE_CHOWN_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_TOUCH_FAILED", STREAM_ERROR_CODE_TOUCH_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_INVALID_MODE", STREAM_ERROR_CODE_INVALID_MODE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_MODE_NOT_SUPPORTED", STREAM_ERROR_CODE_MODE_NOT_SUPPORTED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_READONLY", STREAM_ERROR_CODE_READONLY, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_RECURSION_DETECTED", STREAM_ERROR_CODE_RECURSION_DETECTED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_WRAPPER_NOT_FOUND", STREAM_ERROR_CODE_WRAPPER_NOT_FOUND, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_WRAPPER_DISABLED", STREAM_ERROR_CODE_WRAPPER_DISABLED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_PROTOCOL_UNSUPPORTED", STREAM_ERROR_CODE_PROTOCOL_UNSUPPORTED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_WRAPPER_REGISTRATION_FAILED", STREAM_ERROR_CODE_WRAPPER_REGISTRATION_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_WRAPPER_UNREGISTRATION_FAILED", STREAM_ERROR_CODE_WRAPPER_UNREGISTRATION_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_WRAPPER_RESTORATION_FAILED", STREAM_ERROR_CODE_WRAPPER_RESTORATION_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_FILTER_NOT_FOUND", STREAM_ERROR_CODE_FILTER_NOT_FOUND, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_FILTER_FAILED", STREAM_ERROR_CODE_FILTER_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_CAST_FAILED", STREAM_ERROR_CODE_CAST_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_CAST_NOT_SUPPORTED", STREAM_ERROR_CODE_CAST_NOT_SUPPORTED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_MAKE_SEEKABLE_FAILED", STREAM_ERROR_CODE_MAKE_SEEKABLE_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_BUFFERED_DATA_LOST", STREAM_ERROR_CODE_BUFFERED_DATA_LOST, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_NETWORK_SEND_FAILED", STREAM_ERROR_CODE_NETWORK_SEND_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_NETWORK_RECV_FAILED", STREAM_ERROR_CODE_NETWORK_RECV_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_SSL_NOT_SUPPORTED", STREAM_ERROR_CODE_SSL_NOT_SUPPORTED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_SOCKET_PATH_TOO_LONG", STREAM_ERROR_CODE_SOCKET_PATH_TOO_LONG, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_OOB_NOT_SUPPORTED", STREAM_ERROR_CODE_OOB_NOT_SUPPORTED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_PROTOCOL_ERROR", STREAM_ERROR_CODE_PROTOCOL_ERROR, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_INVALID_URL", STREAM_ERROR_CODE_INVALID_URL, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_INVALID_RESPONSE", STREAM_ERROR_CODE_INVALID_RESPONSE, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_REDIRECT_LIMIT", STREAM_ERROR_CODE_REDIRECT_LIMIT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_AUTH_FAILED", STREAM_ERROR_CODE_AUTH_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_ENCODING_FAILED", STREAM_ERROR_CODE_ENCODING_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_INVALID_FORMAT", STREAM_ERROR_CODE_INVALID_FORMAT, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_ALLOCATION_FAILED", STREAM_ERROR_CODE_ALLOCATION_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_TEMPORARY_FILE_FAILED", STREAM_ERROR_CODE_TEMPORARY_FILE_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_LOCK_FAILED", STREAM_ERROR_CODE_LOCK_FAILED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_LOCK_NOT_SUPPORTED", STREAM_ERROR_CODE_LOCK_NOT_SUPPORTED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_USERSPACE_NOT_IMPLEMENTED", STREAM_ERROR_CODE_USERSPACE_NOT_IMPLEMENTED, CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("STREAM_ERROR_CODE_USERSPACE_INVALID_RETURN", STREAM_ERROR_CODE_USERSPACE_INVALID_RETURN, CONST_PERSISTENT);
}

static zend_class_entry *register_class_StreamException(zend_class_entry *class_entry_Exception)
{
	zend_class_entry ce, *class_entry;

	INIT_CLASS_ENTRY(ce, "StreamException", class_StreamException_methods);
	class_entry = zend_register_internal_class_with_flags(&ce, class_entry_Exception, 0);

	zval property_wrapperName_default_value;
	ZVAL_UNDEF(&property_wrapperName_default_value);
	zend_string *property_wrapperName_name = zend_string_init("wrapperName", sizeof("wrapperName") - 1, true);
	zend_declare_typed_property(class_entry, property_wrapperName_name, &property_wrapperName_default_value, ZEND_ACC_PROTECTED, NULL, (zend_type) ZEND_TYPE_INIT_MASK(MAY_BE_STRING));
	zend_string_release_ex(property_wrapperName_name, true);

	zval property_param_default_value;
	ZVAL_NULL(&property_param_default_value);
	zend_string *property_param_name = zend_string_init("param", sizeof("param") - 1, true);
	zend_declare_typed_property(class_entry, property_param_name, &property_param_default_value, ZEND_ACC_PROTECTED, NULL, (zend_type) ZEND_TYPE_INIT_MASK(MAY_BE_STRING|MAY_BE_NULL));
	zend_string_release_ex(property_param_name, true);

	return class_entry;
}
