/* This is a generated file, edit stream_errors.stub.php instead.
 * Stub hash: 4cddf758cc9f2041802d8cbbaaa45593022a5db1 */

#ifndef ZEND_STREAM_ERRORS_DECL_4cddf758cc9f2041802d8cbbaaa45593022a5db1_H
#define ZEND_STREAM_ERRORS_DECL_4cddf758cc9f2041802d8cbbaaa45593022a5db1_H

typedef enum zend_enum_StreamErrorCode {
	ZEND_ENUM_StreamErrorCode_None = 1,
	ZEND_ENUM_StreamErrorCode_Generic = 2,
	ZEND_ENUM_StreamErrorCode_ReadFailed = 3,
	ZEND_ENUM_StreamErrorCode_WriteFailed = 4,
	ZEND_ENUM_StreamErrorCode_SeekFailed = 5,
	ZEND_ENUM_StreamErrorCode_SeekNotSupported = 6,
	ZEND_ENUM_StreamErrorCode_FlushFailed = 7,
	ZEND_ENUM_StreamErrorCode_TruncateFailed = 8,
	ZEND_ENUM_StreamErrorCode_ConnectFailed = 9,
	ZEND_ENUM_StreamErrorCode_BindFailed = 10,
	ZEND_ENUM_StreamErrorCode_ListenFailed = 11,
	ZEND_ENUM_StreamErrorCode_AcceptFailed = 12,
	ZEND_ENUM_StreamErrorCode_NotWritable = 13,
	ZEND_ENUM_StreamErrorCode_NotReadable = 14,
	ZEND_ENUM_StreamErrorCode_Disabled = 15,
	ZEND_ENUM_StreamErrorCode_NotFound = 16,
	ZEND_ENUM_StreamErrorCode_PermissionDenied = 17,
	ZEND_ENUM_StreamErrorCode_AlreadyExists = 18,
	ZEND_ENUM_StreamErrorCode_InvalidPath = 19,
	ZEND_ENUM_StreamErrorCode_PathTooLong = 20,
	ZEND_ENUM_StreamErrorCode_OpenFailed = 21,
	ZEND_ENUM_StreamErrorCode_CreateFailed = 22,
	ZEND_ENUM_StreamErrorCode_DupFailed = 23,
	ZEND_ENUM_StreamErrorCode_UnlinkFailed = 24,
	ZEND_ENUM_StreamErrorCode_RenameFailed = 25,
	ZEND_ENUM_StreamErrorCode_MkdirFailed = 26,
	ZEND_ENUM_StreamErrorCode_RmdirFailed = 27,
	ZEND_ENUM_StreamErrorCode_StatFailed = 28,
	ZEND_ENUM_StreamErrorCode_MetaFailed = 29,
	ZEND_ENUM_StreamErrorCode_ChmodFailed = 30,
	ZEND_ENUM_StreamErrorCode_ChownFailed = 31,
	ZEND_ENUM_StreamErrorCode_CopyFailed = 32,
	ZEND_ENUM_StreamErrorCode_TouchFailed = 33,
	ZEND_ENUM_StreamErrorCode_InvalidMode = 34,
	ZEND_ENUM_StreamErrorCode_InvalidMeta = 35,
	ZEND_ENUM_StreamErrorCode_ModeNotSupported = 36,
	ZEND_ENUM_StreamErrorCode_Readonly = 37,
	ZEND_ENUM_StreamErrorCode_RecursionDetected = 38,
	ZEND_ENUM_StreamErrorCode_NotImplemented = 39,
	ZEND_ENUM_StreamErrorCode_NoOpener = 40,
	ZEND_ENUM_StreamErrorCode_PersistentNotSupported = 41,
	ZEND_ENUM_StreamErrorCode_WrapperNotFound = 42,
	ZEND_ENUM_StreamErrorCode_WrapperDisabled = 43,
	ZEND_ENUM_StreamErrorCode_ProtocolUnsupported = 44,
	ZEND_ENUM_StreamErrorCode_WrapperRegistrationFailed = 45,
	ZEND_ENUM_StreamErrorCode_WrapperUnregistrationFailed = 46,
	ZEND_ENUM_StreamErrorCode_WrapperRestorationFailed = 47,
	ZEND_ENUM_StreamErrorCode_FilterNotFound = 48,
	ZEND_ENUM_StreamErrorCode_FilterFailed = 49,
	ZEND_ENUM_StreamErrorCode_CastFailed = 50,
	ZEND_ENUM_StreamErrorCode_CastNotSupported = 51,
	ZEND_ENUM_StreamErrorCode_MakeSeekableFailed = 52,
	ZEND_ENUM_StreamErrorCode_BufferedDataLost = 53,
	ZEND_ENUM_StreamErrorCode_NetworkSendFailed = 54,
	ZEND_ENUM_StreamErrorCode_NetworkRecvFailed = 55,
	ZEND_ENUM_StreamErrorCode_SslNotSupported = 56,
	ZEND_ENUM_StreamErrorCode_ResumptionFailed = 57,
	ZEND_ENUM_StreamErrorCode_SocketPathTooLong = 58,
	ZEND_ENUM_StreamErrorCode_OobNotSupported = 59,
	ZEND_ENUM_StreamErrorCode_ProtocolError = 60,
	ZEND_ENUM_StreamErrorCode_InvalidUrl = 61,
	ZEND_ENUM_StreamErrorCode_InvalidResponse = 62,
	ZEND_ENUM_StreamErrorCode_InvalidHeader = 63,
	ZEND_ENUM_StreamErrorCode_InvalidParam = 64,
	ZEND_ENUM_StreamErrorCode_RedirectLimit = 65,
	ZEND_ENUM_StreamErrorCode_AuthFailed = 66,
	ZEND_ENUM_StreamErrorCode_TimeOut = 67,
	ZEND_ENUM_StreamErrorCode_ArchivingFailed = 68,
	ZEND_ENUM_StreamErrorCode_EncodingFailed = 69,
	ZEND_ENUM_StreamErrorCode_DecodingFailed = 70,
	ZEND_ENUM_StreamErrorCode_InvalidFormat = 71,
	ZEND_ENUM_StreamErrorCode_AllocationFailed = 72,
	ZEND_ENUM_StreamErrorCode_TemporaryFileFailed = 73,
	ZEND_ENUM_StreamErrorCode_LockFailed = 74,
	ZEND_ENUM_StreamErrorCode_LockNotSupported = 75,
	ZEND_ENUM_StreamErrorCode_UserspaceNotImplemented = 76,
	ZEND_ENUM_StreamErrorCode_UserspaceInvalidReturn = 77,
	ZEND_ENUM_StreamErrorCode_UserspaceCallFailed = 78,
} zend_enum_StreamErrorCode;

#define ZEND_ENUM_StreamErrorCode_CASE_COUNT 78

#ifdef ZEND_ENUM_StreamErrorCode_USE_NAME_TABLE
static const char *zend_enum_StreamErrorCode_case_names[ZEND_ENUM_StreamErrorCode_CASE_COUNT + 1] = {
	[ZEND_ENUM_StreamErrorCode_None] = "None",
	[ZEND_ENUM_StreamErrorCode_Generic] = "Generic",
	[ZEND_ENUM_StreamErrorCode_ReadFailed] = "ReadFailed",
	[ZEND_ENUM_StreamErrorCode_WriteFailed] = "WriteFailed",
	[ZEND_ENUM_StreamErrorCode_SeekFailed] = "SeekFailed",
	[ZEND_ENUM_StreamErrorCode_SeekNotSupported] = "SeekNotSupported",
	[ZEND_ENUM_StreamErrorCode_FlushFailed] = "FlushFailed",
	[ZEND_ENUM_StreamErrorCode_TruncateFailed] = "TruncateFailed",
	[ZEND_ENUM_StreamErrorCode_ConnectFailed] = "ConnectFailed",
	[ZEND_ENUM_StreamErrorCode_BindFailed] = "BindFailed",
	[ZEND_ENUM_StreamErrorCode_ListenFailed] = "ListenFailed",
	[ZEND_ENUM_StreamErrorCode_AcceptFailed] = "AcceptFailed",
	[ZEND_ENUM_StreamErrorCode_NotWritable] = "NotWritable",
	[ZEND_ENUM_StreamErrorCode_NotReadable] = "NotReadable",
	[ZEND_ENUM_StreamErrorCode_Disabled] = "Disabled",
	[ZEND_ENUM_StreamErrorCode_NotFound] = "NotFound",
	[ZEND_ENUM_StreamErrorCode_PermissionDenied] = "PermissionDenied",
	[ZEND_ENUM_StreamErrorCode_AlreadyExists] = "AlreadyExists",
	[ZEND_ENUM_StreamErrorCode_InvalidPath] = "InvalidPath",
	[ZEND_ENUM_StreamErrorCode_PathTooLong] = "PathTooLong",
	[ZEND_ENUM_StreamErrorCode_OpenFailed] = "OpenFailed",
	[ZEND_ENUM_StreamErrorCode_CreateFailed] = "CreateFailed",
	[ZEND_ENUM_StreamErrorCode_DupFailed] = "DupFailed",
	[ZEND_ENUM_StreamErrorCode_UnlinkFailed] = "UnlinkFailed",
	[ZEND_ENUM_StreamErrorCode_RenameFailed] = "RenameFailed",
	[ZEND_ENUM_StreamErrorCode_MkdirFailed] = "MkdirFailed",
	[ZEND_ENUM_StreamErrorCode_RmdirFailed] = "RmdirFailed",
	[ZEND_ENUM_StreamErrorCode_StatFailed] = "StatFailed",
	[ZEND_ENUM_StreamErrorCode_MetaFailed] = "MetaFailed",
	[ZEND_ENUM_StreamErrorCode_ChmodFailed] = "ChmodFailed",
	[ZEND_ENUM_StreamErrorCode_ChownFailed] = "ChownFailed",
	[ZEND_ENUM_StreamErrorCode_CopyFailed] = "CopyFailed",
	[ZEND_ENUM_StreamErrorCode_TouchFailed] = "TouchFailed",
	[ZEND_ENUM_StreamErrorCode_InvalidMode] = "InvalidMode",
	[ZEND_ENUM_StreamErrorCode_InvalidMeta] = "InvalidMeta",
	[ZEND_ENUM_StreamErrorCode_ModeNotSupported] = "ModeNotSupported",
	[ZEND_ENUM_StreamErrorCode_Readonly] = "Readonly",
	[ZEND_ENUM_StreamErrorCode_RecursionDetected] = "RecursionDetected",
	[ZEND_ENUM_StreamErrorCode_NotImplemented] = "NotImplemented",
	[ZEND_ENUM_StreamErrorCode_NoOpener] = "NoOpener",
	[ZEND_ENUM_StreamErrorCode_PersistentNotSupported] = "PersistentNotSupported",
	[ZEND_ENUM_StreamErrorCode_WrapperNotFound] = "WrapperNotFound",
	[ZEND_ENUM_StreamErrorCode_WrapperDisabled] = "WrapperDisabled",
	[ZEND_ENUM_StreamErrorCode_ProtocolUnsupported] = "ProtocolUnsupported",
	[ZEND_ENUM_StreamErrorCode_WrapperRegistrationFailed] = "WrapperRegistrationFailed",
	[ZEND_ENUM_StreamErrorCode_WrapperUnregistrationFailed] = "WrapperUnregistrationFailed",
	[ZEND_ENUM_StreamErrorCode_WrapperRestorationFailed] = "WrapperRestorationFailed",
	[ZEND_ENUM_StreamErrorCode_FilterNotFound] = "FilterNotFound",
	[ZEND_ENUM_StreamErrorCode_FilterFailed] = "FilterFailed",
	[ZEND_ENUM_StreamErrorCode_CastFailed] = "CastFailed",
	[ZEND_ENUM_StreamErrorCode_CastNotSupported] = "CastNotSupported",
	[ZEND_ENUM_StreamErrorCode_MakeSeekableFailed] = "MakeSeekableFailed",
	[ZEND_ENUM_StreamErrorCode_BufferedDataLost] = "BufferedDataLost",
	[ZEND_ENUM_StreamErrorCode_NetworkSendFailed] = "NetworkSendFailed",
	[ZEND_ENUM_StreamErrorCode_NetworkRecvFailed] = "NetworkRecvFailed",
	[ZEND_ENUM_StreamErrorCode_SslNotSupported] = "SslNotSupported",
	[ZEND_ENUM_StreamErrorCode_ResumptionFailed] = "ResumptionFailed",
	[ZEND_ENUM_StreamErrorCode_SocketPathTooLong] = "SocketPathTooLong",
	[ZEND_ENUM_StreamErrorCode_OobNotSupported] = "OobNotSupported",
	[ZEND_ENUM_StreamErrorCode_ProtocolError] = "ProtocolError",
	[ZEND_ENUM_StreamErrorCode_InvalidUrl] = "InvalidUrl",
	[ZEND_ENUM_StreamErrorCode_InvalidResponse] = "InvalidResponse",
	[ZEND_ENUM_StreamErrorCode_InvalidHeader] = "InvalidHeader",
	[ZEND_ENUM_StreamErrorCode_InvalidParam] = "InvalidParam",
	[ZEND_ENUM_StreamErrorCode_RedirectLimit] = "RedirectLimit",
	[ZEND_ENUM_StreamErrorCode_AuthFailed] = "AuthFailed",
	[ZEND_ENUM_StreamErrorCode_TimeOut] = "TimeOut",
	[ZEND_ENUM_StreamErrorCode_ArchivingFailed] = "ArchivingFailed",
	[ZEND_ENUM_StreamErrorCode_EncodingFailed] = "EncodingFailed",
	[ZEND_ENUM_StreamErrorCode_DecodingFailed] = "DecodingFailed",
	[ZEND_ENUM_StreamErrorCode_InvalidFormat] = "InvalidFormat",
	[ZEND_ENUM_StreamErrorCode_AllocationFailed] = "AllocationFailed",
	[ZEND_ENUM_StreamErrorCode_TemporaryFileFailed] = "TemporaryFileFailed",
	[ZEND_ENUM_StreamErrorCode_LockFailed] = "LockFailed",
	[ZEND_ENUM_StreamErrorCode_LockNotSupported] = "LockNotSupported",
	[ZEND_ENUM_StreamErrorCode_UserspaceNotImplemented] = "UserspaceNotImplemented",
	[ZEND_ENUM_StreamErrorCode_UserspaceInvalidReturn] = "UserspaceInvalidReturn",
	[ZEND_ENUM_StreamErrorCode_UserspaceCallFailed] = "UserspaceCallFailed",
};
#endif

typedef enum zend_enum_StreamErrorMode {
	ZEND_ENUM_StreamErrorMode_Error = 1,
	ZEND_ENUM_StreamErrorMode_Exception = 2,
	ZEND_ENUM_StreamErrorMode_Silent = 3,
} zend_enum_StreamErrorMode;

typedef enum zend_enum_StreamErrorStore {
	ZEND_ENUM_StreamErrorStore_Auto = 1,
	ZEND_ENUM_StreamErrorStore_None = 2,
	ZEND_ENUM_StreamErrorStore_NonTerminating = 3,
	ZEND_ENUM_StreamErrorStore_Terminating = 4,
	ZEND_ENUM_StreamErrorStore_All = 5,
} zend_enum_StreamErrorStore;

#endif /* ZEND_STREAM_ERRORS_DECL_4cddf758cc9f2041802d8cbbaaa45593022a5db1_H */
