/* This is a generated file, edit the .stub.php file instead. */

ZEND_BEGIN_ARG_INFO_EX(arginfo_class_SimpleXMLIterator_rewind, 0, 0, 0)
ZEND_END_ARG_INFO()

#define arginfo_class_SimpleXMLIterator_valid arginfo_class_SimpleXMLIterator_rewind

#define arginfo_class_SimpleXMLIterator_current arginfo_class_SimpleXMLIterator_rewind

#define arginfo_class_SimpleXMLIterator_key arginfo_class_SimpleXMLIterator_rewind

#define arginfo_class_SimpleXMLIterator_next arginfo_class_SimpleXMLIterator_rewind

#define arginfo_class_SimpleXMLIterator_hasChildren arginfo_class_SimpleXMLIterator_rewind

#define arginfo_class_SimpleXMLIterator_getChildren arginfo_class_SimpleXMLIterator_rewind
