name: ccache
inputs:
  name:
    required: true
runs:
  using: composite
  steps:
    - name: Get cache key
      shell: bash
      id: cache_key
      run: |
        major=$(cat main/php_version.h | sed -En 's/^#define PHP_MAJOR_VERSION ([0-9]+)/\1/p')
        minor=$(cat main/php_version.h | sed -En 's/^#define PHP_MINOR_VERSION ([0-9]+)/\1/p')
        release=$(cat main/php_version.h | sed -En 's/^#define PHP_RELEASE_VERSION ([0-9]+)/\1/p')
        week=$(date +"%Y-%W")
        prefix="${{ inputs.name }}-$major.$minor.$release"
        echo "key=$prefix-$week" >> $GITHUB_OUTPUT
        echo "prefix=$prefix-" >> $GITHUB_OUTPUT
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: "${{ steps.cache_key.outputs.key }}"
        append-timestamp: false
        restore-keys: "${{ steps.cache_key.outputs.prefix }}"
        #save: ${{ github.event_name != 'pull_request' }}
    - name: Export CC/CXX
      shell: bash
      run: |
        export CC=ccache gcc
        export CXX=ccache g++
