name: ccache
inputs:
  name:
    required: true
runs:
  using: composite
  steps:
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: "${{ inputs.name }}-${{ hashFiles('main/php_version.h') }}"
        append-timestamp: false
        save: ${{ github.event_name != 'pull_request' }}
