name: ccache
inputs:
  name:
    required: true
runs:
  using: composite
  steps:
    - name: Get PHP version
      shell: bash
      id: php_version
      run: |
        echo "major=$(cat main/php_version.h | sed -n 's/^#define PHP_MAJOR_VERSION \([0-9]\+\)/\1/p')" >> $GITHUB_OUTPUT
        echo "minor=$(cat main/php_version.h | sed -n 's/^#define PHP_MINOR_VERSION \([0-9]\+\)/\1/p')" >> $GITHUB_OUTPUT
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: "${{ inputs.name }}-${{ steps.php_version.outputs.major }}.${{ steps.php_version.outputs.minor }}"
        append-timestamp: false
        save: ${{ github.event_name != 'pull_request' }}
