name: brew
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x

        # Patch brew to overwrite always
        formula_installer="$(brew --repo)"/Library/Homebrew/formula_installer.rb
        code=" keg.link\(verbose: verbose\?"
        sudo sed -Ei '' "s/$code.*/$code, overwrite: true\)/" "$formula_installer"

        brew install \
          pkg-config \
          autoconf \
          bison \
          re2c
        brew install \
          openssl@1.1 \
          curl \
          krb5 \
          bzip2 \
          enchant \
          libffi \
          libpng \
          webp \
          freetype \
          intltool \
          icu4c \
          libiconv \
          zlib \
          t1lib \
          gd \
          libzip \
          gmp \
          tidy-html5 \
          libxml2 \
          libjpeg \
          libsodium \
          libxslt \
          postgresql
        brew link icu4c gettext --force
