/* Automatically generated.  Do not edit */
/* See the mkopcodeh.awk script for details */
#define OP_ContextPop                  1
#define OP_IntegrityCk                 2
#define OP_DropTrigger                 3
#define OP_DropIndex                   4
#define OP_Recno                       5
#define OP_KeyAsData                   6
#define OP_Delete                      7
#define OP_MoveGt                      8
#define OP_VerifyCookie                9
#define OP_Push                        10
#define OP_Dup                         11
#define OP_Blob                        12
#define OP_IdxGT                       13
#define OP_IdxRecno                    14
#define OP_RowKey                      15
#define OP_PutStrKey                   16
#define OP_IsUnique                    17
#define OP_SetNumColumns               18
#define OP_Eq                          67
#define OP_IdxIsNull                   19
#define OP_NullRow                     20
#define OP_OpenPseudo                  21
#define OP_OpenWrite                   22
#define OP_OpenRead                    23
#define OP_Transaction                 24
#define OP_AutoCommit                  25
#define OP_Negative                    82
#define OP_Pop                         26
#define OP_Halt                        27
#define OP_Vacuum                      28
#define OP_ListRead                    29
#define OP_RowData                     30
#define OP_NotExists                   31
#define OP_MoveLe                      32
#define OP_SetCookie                   33
#define OP_Variable                    34
#define OP_AggNext                     35
#define OP_AggReset                    36
#define OP_Sort                        37
#define OP_IdxDelete                   38
#define OP_ResetCount                  39
#define OP_OpenTemp                    40
#define OP_IdxColumn                   41
#define OP_NotNull                     65
#define OP_Ge                          71
#define OP_Remainder                   80
#define OP_Divide                      79
#define OP_Integer                     42
#define OP_AggSet                      43
#define OP_CreateIndex                 44
#define OP_IdxPut                      45
#define OP_MoveLt                      46
#define OP_And                         59
#define OP_ShiftLeft                   74
#define OP_Real                        122
#define OP_Return                      47
#define OP_MemLoad                     48
#define OP_SortNext                    49
#define OP_IdxLT                       50
#define OP_Rewind                      51
#define OP_Gt                          68
#define OP_AddImm                      52
#define OP_Subtract                    77
#define OP_AggFunc                     53
#define OP_AggInit                     54
#define OP_MemIncr                     55
#define OP_ListReset                   56
#define OP_Clear                       57
#define OP_PutIntKey                   61
#define OP_IsNull                      64
#define OP_If                          62
#define OP_Callback                    63
#define OP_SortReset                   83
#define OP_SortPut                     86
#define OP_Last                        87
#define OP_NotFound                    88
#define OP_MakeRecord                  89
#define OP_BitAnd                      72
#define OP_Add                         76
#define OP_HexBlob                     123
#define OP_String                      90
#define OP_Goto                        91
#define OP_AggFocus                    92
#define OP_DropTable                   93
#define OP_Column                      94
#define OP_Noop                        95
#define OP_Not                         60
#define OP_Le                          69
#define OP_BitOr                       73
#define OP_Multiply                    78
#define OP_String8                     85
#define OP_AggGet                      96
#define OP_CreateTable                 97
#define OP_NewRecno                    98
#define OP_Found                       99
#define OP_Distinct                    100
#define OP_Close                       101
#define OP_Statement                   102
#define OP_IfNot                       103
#define OP_Pull                        104
#define OP_MemStore                    105
#define OP_Next                        106
#define OP_Prev                        107
#define OP_MoveGe                      108
#define OP_Lt                          70
#define OP_Ne                          66
#define OP_MustBeInt                   109
#define OP_ForceInt                    110
#define OP_ShiftRight                  75
#define OP_CollSeq                     111
#define OP_Gosub                       112
#define OP_ContextPush                 113
#define OP_ListRewind                  114
#define OP_ListWrite                   115
#define OP_ParseSchema                 116
#define OP_Destroy                     117
#define OP_IdxGE                       118
#define OP_FullKey                     119
#define OP_ReadCookie                  120
#define OP_BitNot                      84
#define OP_AbsValue                    121
#define OP_Or                          58
#define OP_Function                    124
#define OP_Concat                      81
