#define TK_END_OF_FILE                     1
#define TK_ILLEGAL                         2
#define TK_SPACE                           3
#define TK_UNCLOSED_STRING                 4
#define TK_COMMENT                         5
#define TK_FUNCTION                        6
#define TK_COLUMN                          7
#define TK_AGG_FUNCTION                    8
#define TK_SEMI                            9
#define TK_EXPLAIN                        10
#define TK_BEGIN                          11
#define TK_TRANSACTION                    12
#define TK_DEFERRED                       13
#define TK_IMMEDIATE                      14
#define TK_EXCLUSIVE                      15
#define TK_COMMIT                         16
#define TK_END                            17
#define TK_ROLLBACK                       18
#define TK_CREATE                         19
#define TK_TABLE                          20
#define TK_TEMP                           21
#define TK_LP                             22
#define TK_RP                             23
#define TK_AS                             24
#define TK_COMMA                          25
#define TK_ID                             26
#define TK_ABORT                          27
#define TK_AFTER                          28
#define TK_ASC                            29
#define TK_ATTACH                         30
#define TK_BEFORE                         31
#define TK_CASCADE                        32
#define TK_CONFLICT                       33
#define TK_DATABASE                       34
#define TK_DESC                           35
#define TK_DETACH                         36
#define TK_EACH                           37
#define TK_FAIL                           38
#define TK_FOR                            39
#define TK_GLOB                           40
#define TK_IGNORE                         41
#define TK_INITIALLY                      42
#define TK_INSTEAD                        43
#define TK_LIKE                           44
#define TK_MATCH                          45
#define TK_KEY                            46
#define TK_OF                             47
#define TK_OFFSET                         48
#define TK_PRAGMA                         49
#define TK_RAISE                          50
#define TK_REPLACE                        51
#define TK_RESTRICT                       52
#define TK_ROW                            53
#define TK_STATEMENT                      54
#define TK_TRIGGER                        55
#define TK_VACUUM                         56
#define TK_VIEW                           57
#define TK_OR                             58
#define TK_AND                            59
#define TK_NOT                            60
#define TK_IS                             61
#define TK_BETWEEN                        62
#define TK_IN                             63
#define TK_ISNULL                         64
#define TK_NOTNULL                        65
#define TK_NE                             66
#define TK_EQ                             67
#define TK_GT                             68
#define TK_LE                             69
#define TK_LT                             70
#define TK_GE                             71
#define TK_BITAND                         72
#define TK_BITOR                          73
#define TK_LSHIFT                         74
#define TK_RSHIFT                         75
#define TK_PLUS                           76
#define TK_MINUS                          77
#define TK_STAR                           78
#define TK_SLASH                          79
#define TK_REM                            80
#define TK_CONCAT                         81
#define TK_UMINUS                         82
#define TK_UPLUS                          83
#define TK_BITNOT                         84
#define TK_STRING                         85
#define TK_JOIN_KW                        86
#define TK_CONSTRAINT                     87
#define TK_DEFAULT                        88
#define TK_NULL                           89
#define TK_PRIMARY                        90
#define TK_UNIQUE                         91
#define TK_CHECK                          92
#define TK_REFERENCES                     93
#define TK_COLLATE                        94
#define TK_ON                             95
#define TK_DELETE                         96
#define TK_UPDATE                         97
#define TK_INSERT                         98
#define TK_SET                            99
#define TK_DEFERRABLE                     100
#define TK_FOREIGN                        101
#define TK_DROP                           102
#define TK_UNION                          103
#define TK_ALL                            104
#define TK_INTERSECT                      105
#define TK_EXCEPT                         106
#define TK_SELECT                         107
#define TK_DISTINCT                       108
#define TK_DOT                            109
#define TK_FROM                           110
#define TK_JOIN                           111
#define TK_USING                          112
#define TK_ORDER                          113
#define TK_BY                             114
#define TK_GROUP                          115
#define TK_HAVING                         116
#define TK_LIMIT                          117
#define TK_WHERE                          118
#define TK_INTO                           119
#define TK_VALUES                         120
#define TK_INTEGER                        121
#define TK_FLOAT                          122
#define TK_BLOB                           123
#define TK_VARIABLE                       124
#define TK_CASE                           125
#define TK_WHEN                           126
#define TK_THEN                           127
#define TK_ELSE                           128
#define TK_INDEX                          129
