#!/bin/sh
#
# $Id$

makefiles=`echo ext/*/Makefile.am | sed -e 's/\.am//g'`
sed -e "s#@@EXT_MAKEFILES@@#$makefiles#" configure.in.in > configure.in.new
if ! cmp configure.in configure.in.new > /dev/null 2>&1; then
    mv configure.in.new configure.in
else
    rm -f configure.in.new
fi

cat acconfig.h.in > acconfig.h.new
confighfiles=`echo ext/*/config.h.stub`
if test "$confighfiles" != "ext/*/config.h.stub"; then
    for file in $confighfiles; do
	cat $file >> acconfig.h.new
    done
fi
if ! cmp acconfig.h acconfig.h.new > /dev/null 2>&1; then
    mv acconfig.h.new acconfig.h
else
    rm -f acconfig.h.new
fi
