/* This is a generated file, edit user_cache.stub.php instead.
 * Stub hash: 542aa0a48af905b8e70306dac42d8b6eca5b9b87 */

#ifndef ZEND_USER_CACHE_DECL_542aa0a48af905b8e70306dac42d8b6eca5b9b87_H
#define ZEND_USER_CACHE_DECL_542aa0a48af905b8e70306dac42d8b6eca5b9b87_H

typedef enum zend_enum_UserCache_CacheAvailability {
	ZEND_ENUM_UserCache_CacheAvailability_Available = 1,
	ZEND_ENUM_UserCache_CacheAvailability_DisabledByIni = 2,
	ZEND_ENUM_UserCache_CacheAvailability_DisabledBySapi = 3,
	ZEND_ENUM_UserCache_CacheAvailability_UnavailableBySharedMemoryInitializationFailed = 4,
	ZEND_ENUM_UserCache_CacheAvailability_UnavailableByBackendNotInitializedBeforeWorkerStartup = 5,
	ZEND_ENUM_UserCache_CacheAvailability_UnavailableByBackendInitializedAfterWorkerStartup = 6,
	ZEND_ENUM_UserCache_CacheAvailability_UnavailableByCgiFastCgiBoundary = 7,
	ZEND_ENUM_UserCache_CacheAvailability_UnavailableByApacheBoundary = 8,
	ZEND_ENUM_UserCache_CacheAvailability_UnavailableByLsapiBoundary = 9,
	ZEND_ENUM_UserCache_CacheAvailability_UnavailableByUnknownReason = 10,
} zend_enum_UserCache_CacheAvailability;

#endif /* ZEND_USER_CACHE_DECL_542aa0a48af905b8e70306dac42d8b6eca5b9b87_H */
