namespace eval ::tkmsgcat_demo {
    ::msgcat::mcset ja "Application Error"  "\u30A2\u30D7\u30EA\u30B1\u30FC\u30B7\u30E7\u30F3\u30A8\u30E9\u30FC"
    ::msgcat::mcset ja "Blue"    "\u9752"
    ::msgcat::mcset ja "Color"   "\u80CC\u666F\u8272"
    ::msgcat::mcset ja "Delete"  "\u6D88\u53BB"
    ::msgcat::mcset ja "Error"   "\u30A8\u30E9\u30FC"
    ::msgcat::mcset ja "Exit"    "\u7D42\u4E86"
    ::msgcat::mcset ja "Green"   "\u7DD1"
    ::msgcat::mcset ja "Red"     "\u8D64"
    ::msgcat::mcset ja "blue"    "\u9752"
    ::msgcat::mcset ja "green"   "\u7DD1"
    ::msgcat::mcset ja "red"     "\u8D64"
}
