--TEST--
Test all CURLE constants are present and are accepted by curl_strerror()
--EXTENSIONS--
curl
--FILE--
<?php
$consts = [
    'CURLE_OK',
    'CURLE_UNSUPPORTED_PROTOCOL',
    'CURLE_FAILED_INIT',
    'CURLE_URL_MALFORMAT',
    'CURLE_NOT_BUILT_IN',
    'CURLE_COULDNT_RESOLVE_PROXY',
    'CURLE_COULDNT_RESOLVE_HOST',
    'CURLE_COULDNT_CONNECT',
    'CURLE_WEIRD_SERVER_REPLY',
    'CURLE_REMOTE_ACCESS_DENIED',
    'CURLE_FTP_ACCEPT_FAILED',
    'CURLE_FTP_WEIRD_PASS_REPLY',
    'CURLE_FTP_ACCEPT_TIMEOUT',
    'CURLE_FTP_WEIRD_PASV_REPLY',
    'CURLE_FTP_WEIRD_227_FORMAT',
    'CURLE_FTP_CANT_GET_HOST',
    'CURLE_HTTP2',
    'CURLE_FTP_COULDNT_SET_TYPE',
    'CURLE_PARTIAL_FILE',
    'CURLE_FTP_COULDNT_RETR_FILE',
    'CURLE_QUOTE_ERROR',
    'CURLE_HTTP_RETURNED_ERROR',
    'CURLE_WRITE_ERROR',
    'CURLE_UPLOAD_FAILED',
    'CURLE_READ_ERROR',
    'CURLE_OUT_OF_MEMORY',
    'CURLE_OPERATION_TIMEDOUT',
    'CURLE_FTP_PORT_FAILED',
    'CURLE_FTP_COULDNT_USE_REST',
    'CURLE_RANGE_ERROR',
    'CURLE_HTTP_POST_ERROR',
    'CURLE_SSL_CONNECT_ERROR',
    'CURLE_BAD_DOWNLOAD_RESUME',
    'CURLE_FILE_COULDNT_READ_FILE',
    'CURLE_LDAP_CANNOT_BIND',
    'CURLE_LDAP_SEARCH_FAILED',
    'CURLE_FUNCTION_NOT_FOUND',
    'CURLE_ABORTED_BY_CALLBACK',
    'CURLE_BAD_FUNCTION_ARGUMENT',
    'CURLE_INTERFACE_FAILED',
    'CURLE_TOO_MANY_REDIRECTS',
    'CURLE_UNKNOWN_OPTION',
    'CURLE_SETOPT_OPTION_SYNTAX',
    'CURLE_GOT_NOTHING',
    'CURLE_SSL_ENGINE_NOTFOUND',
    'CURLE_SSL_ENGINE_SETFAILED',
    'CURLE_SEND_ERROR',
    'CURLE_RECV_ERROR',
    'CURLE_SSL_CERTPROBLEM',
    'CURLE_SSL_CIPHER',
    'CURLE_PEER_FAILED_VERIFICATION',
    'CURLE_BAD_CONTENT_ENCODING',
    'CURLE_FILESIZE_EXCEEDED',
    'CURLE_USE_SSL_FAILED',
    'CURLE_SEND_FAIL_REWIND',
    'CURLE_SSL_ENGINE_INITFAILED',
    'CURLE_LOGIN_DENIED',
    'CURLE_TFTP_NOTFOUND',
    'CURLE_TFTP_PERM',
    'CURLE_REMOTE_DISK_FULL',
    'CURLE_TFTP_ILLEGAL',
    'CURLE_TFTP_UNKNOWNID',
    'CURLE_REMOTE_FILE_EXISTS',
    'CURLE_TFTP_NOSUCHUSER',
    'CURLE_SSL_CACERT_BADFILE',
    'CURLE_REMOTE_FILE_NOT_FOUND',
    'CURLE_SSH',
    'CURLE_SSL_SHUTDOWN_FAILED',
    'CURLE_SSL_CRL_BADFILE',
    'CURLE_SSL_ISSUER_ERROR',
    'CURLE_FTP_PRET_FAILED',
    'CURLE_RTSP_CSEQ_ERROR',
    'CURLE_RTSP_SESSION_ERROR',
    'CURLE_FTP_BAD_FILE_LIST',
    'CURLE_CHUNK_FAILED',
    'CURLE_SSL_PINNEDPUBKEYNOTMATCH',
    'CURLE_SSL_INVALIDCERTSTATUS',
    'CURLE_HTTP2_STREAM',
    'CURLE_RECURSIVE_API_CALL',
    'CURLE_AUTH_ERROR',
    'CURLE_HTTP3',
    'CURLE_QUIC_CONNECT_ERROR',
    'CURLE_PROXY',
    'CURLE_SSL_CLIENTCERT',
    'CURLE_UNRECOVERABLE_POLL',
    'CURLE_TOO_LARGE',
];

$curlVersion = curl_version()['version'];

foreach ($consts as $const) {
    if (!defined($const)) {
        echo $const . ' - ' . $curlVersion . PHP_EOL;
        continue;
    }
    echo $const . ' (' . constant($const) . ')' . PHP_EOL;
	if (curl_strerror(constant($const)) === 'Unknown error') {
        throw new Exception('Error number invalid');
    }
}
?>
--EXPECTF--
CURLE_OK (0)
CURLE_UNSUPPORTED_PROTOCOL (1)
CURLE_FAILED_INIT (2)
CURLE_URL_MALFORMAT (3)
CURLE_NOT_BUILT_IN (4)
CURLE_COULDNT_RESOLVE_PROXY (5)
CURLE_COULDNT_RESOLVE_HOST (6)
CURLE_COULDNT_CONNECT (7)
CURLE_WEIRD_SERVER_REPLY (8)
CURLE_REMOTE_ACCESS_DENIED (9)
CURLE_FTP_ACCEPT_FAILED (10)
CURLE_FTP_WEIRD_PASS_REPLY (11)
CURLE_FTP_ACCEPT_TIMEOUT (12)
CURLE_FTP_WEIRD_PASV_REPLY (13)
CURLE_FTP_WEIRD_227_FORMAT (14)
CURLE_FTP_CANT_GET_HOST (15)
CURLE_HTTP2 (16)
CURLE_FTP_COULDNT_SET_TYPE (17)
CURLE_PARTIAL_FILE (18)
CURLE_FTP_COULDNT_RETR_FILE (19)
CURLE_QUOTE_ERROR (21)
CURLE_HTTP_RETURNED_ERROR (22)
CURLE_WRITE_ERROR (23)
CURLE_UPLOAD_FAILED (25)
CURLE_READ_ERROR (26)
CURLE_OUT_OF_MEMORY (27)
CURLE_OPERATION_TIMEDOUT (28)
CURLE_FTP_PORT_FAILED (30)
CURLE_FTP_COULDNT_USE_REST (31)
CURLE_RANGE_ERROR (33)
CURLE_HTTP_POST_ERROR (34)
CURLE_SSL_CONNECT_ERROR (35)
CURLE_BAD_DOWNLOAD_RESUME (36)
CURLE_FILE_COULDNT_READ_FILE (37)
CURLE_LDAP_CANNOT_BIND (38)
CURLE_LDAP_SEARCH_FAILED (39)
CURLE_FUNCTION_NOT_FOUND (41)
CURLE_ABORTED_BY_CALLBACK (42)
CURLE_BAD_FUNCTION_ARGUMENT (43)
CURLE_INTERFACE_FAILED (45)
CURLE_TOO_MANY_REDIRECTS (47)
CURLE_UNKNOWN_OPTION (48)
CURLE_SETOPT_OPTION_SYNTAX %r\(49\)|- 7\.(6[1-9]|7[0-7])\.\d%r
CURLE_GOT_NOTHING (52)
CURLE_SSL_ENGINE_NOTFOUND (53)
CURLE_SSL_ENGINE_SETFAILED (54)
CURLE_SEND_ERROR (55)
CURLE_RECV_ERROR (56)
CURLE_SSL_CERTPROBLEM (58)
CURLE_SSL_CIPHER (59)
CURLE_PEER_FAILED_VERIFICATION (60)
CURLE_BAD_CONTENT_ENCODING (61)
CURLE_FILESIZE_EXCEEDED (63)
CURLE_USE_SSL_FAILED (64)
CURLE_SEND_FAIL_REWIND (65)
CURLE_SSL_ENGINE_INITFAILED (66)
CURLE_LOGIN_DENIED (67)
CURLE_TFTP_NOTFOUND (68)
CURLE_TFTP_PERM (69)
CURLE_REMOTE_DISK_FULL (70)
CURLE_TFTP_ILLEGAL (71)
CURLE_TFTP_UNKNOWNID (72)
CURLE_REMOTE_FILE_EXISTS (73)
CURLE_TFTP_NOSUCHUSER (74)
CURLE_SSL_CACERT_BADFILE (77)
CURLE_REMOTE_FILE_NOT_FOUND (78)
CURLE_SSH (79)
CURLE_SSL_SHUTDOWN_FAILED (80)
CURLE_SSL_CRL_BADFILE (82)
CURLE_SSL_ISSUER_ERROR (83)
CURLE_FTP_PRET_FAILED (84)
CURLE_RTSP_CSEQ_ERROR (85)
CURLE_RTSP_SESSION_ERROR (86)
CURLE_FTP_BAD_FILE_LIST (87)
CURLE_CHUNK_FAILED (88)
CURLE_SSL_PINNEDPUBKEYNOTMATCH (90)
CURLE_SSL_INVALIDCERTSTATUS (91)
CURLE_HTTP2_STREAM (92)
CURLE_RECURSIVE_API_CALL (93)
CURLE_AUTH_ERROR %r\(94\)|- 7\.(6[1-6])\.\d%r
CURLE_HTTP3 %r\(95\)|- 7\.(6[1-8])\.\d%r
CURLE_QUIC_CONNECT_ERROR %r\(96\)|- 7\.(6[1-9])\.\d%r
CURLE_PROXY %r\(97\)|- 7\.(6[1-9]|7[0-3])\.\d%r
CURLE_SSL_CLIENTCERT %r\(98\)|- 7\.(6[1-9]|7[0-7])\.\d%r
CURLE_UNRECOVERABLE_POLL %r\(99\)|- 7\.(6[1-9]|7[\d]|8[0-4])\.\d%r
CURLE_TOO_LARGE %r\(100\)|- (7\.(6[1-9]|[789][\d])|8\.[0-5])\.\d%r
