#define HAVE_STDIO_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDDEF_H 1
#define HAVE_ASSERT_H 1
#define HAVE_MEMORY_H 1
/* #undef HAVE_STRINGS_H */
#define HAVE_STRING_H 1
/* #undef HAVE_STRCASECMP */
#define HAVE_STRICMP 1
#define HAVE_WIN32_NATIVE_THREAD 1
#define USE_WIN32_NATIVE_THREAD 1
#define ENABLE_THREADS 1
