#!/bin/sh
function cvsclean_sub() {
  prev_pwd=`pwd`	
  cd $1
  cat .cvsignore | while read fname; do
  rm -r -f $fname
  done
  cd "$prev_pwd"
}

cvsclean_sub .
cvsclean_sub mbfl
cvsclean_sub filters
cvsclean_sub nls
