#!/bin/sh -eu

cd "${0%/*}/../.."

./buildconf

./configure \
  --enable-debug \
  --enable-fpm \
  --with-fpm-systemd \
  --enable-phpdbg \
  --enable-phpdbg-webhelper \
  --enable-phpdbg-readline \
  --with-openssl \
  --with-kerberos \
  --with-system-ciphers \
  --with-pcre-jit \
  --with-zlib \
  --enable-bcmath \
  --with-bz2 \
  --enable-calendar \
  --with-curl \
  --enable-dba \
  --with-lmdb  \
  --with-qdbm \
  --with-tcadb \
  --with-enchant \
  --enable-exif \
  --with-ffi \
  --enable-ftp \
  --enable-gd \
  --with-webp \
  --with-jpeg \
  --with-xpm \
  --with-freetype \
  --with-gettext \
  --with-gmp \
  --with-mhash \
  --with-imap \
  --with-kerberos \
  --with-imap-ssl \
  --enable-intl \
  --with-ldap \
  --with-ldap-sasl \
  --enable-mbstring \
  --with-mysqli \
  --enable-pcntl \
  --with-pdo-mysql \
  --with-pdo-pgsql \
  --with-pgsql \
  --with-pspell \
  --with-libedit \
  --with-readline \
  --enable-shmop \
  --with-snmp \
  --enable-soap \
  --enable-sockets \
  --with-sodium \
  --with-password-argon2 \
  --enable-sysvmsg \
  --enable-sysvsem \
  --enable-sysvshm \
  --with-tidy \
  --with-xsl \
  --with-zip \
  --enable-mysqlnd \
  --with-pear \
  --enable-werror \
  --enable-phar \
  --enable-zend-test=shared \
  "$@"

