name: ./configure
inputs:
  configurationParameters:
    default: ''
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        ./buildconf --force
        ./configure \
          --enable-option-checking=fatal \
          --prefix=/usr \
          --enable-phpdbg \
          --enable-fpm \
          --enable-intl \
          --without-pear \
          --with-zlib \
          --with-zlib-dir=/usr \
          --enable-mbstring \
          --with-curl \
          --with-gettext \
          --enable-sockets \
          --with-openssl \
          --with-gmp \
          --enable-bcmath \
          --enable-calendar \
          --enable-ftp \
          --enable-dl-test=shared \
          --with-mhash \
          --with-sodium \
          --with-config-file-path=/etc \
          --with-config-file-scan-dir=/etc/php.d \
          --enable-werror \
          ${{ inputs.configurationParameters }}
