name: verify-templating
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        scripts/dev/genfiles
        Zend/zend_vm_gen.php
        build/gen_stub.php -f
        git add . -N && git diff --exit-code
