name: Nightly results
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'php/php-src' && github.event.workflow_run.event == 'schedule' && github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - env:
          RUN_URL: ${{ github.event.workflow_run.html_url }}
          SLACK_WEBHOOK: ${{ secrets.ACTION_MONITORING_SLACK }}
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y curl
          curl -X POST -H 'Content-type: application/json' --data "$(printf '{"attachments": [{"text": "Job(s) in *nightly* failed", "footer": "<%s|View Run>", "color": "danger", "mrkdwn_in": ["text"]}]}' "$RUN_URL")" "$SLACK_WEBHOOK"
