name: Remove needs feedback label

on:
  issue_comment:
    types:
      - created

permissions:
  contents: read

jobs:
  build:
    if: "github.repository == 'php/php-src' && contains(github.event.issue.labels.*.name, 'Status: Needs Feedback') && github.event.issue.user.login == github.event.sender.login"
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions-ecosystem/action-remove-labels@f27b608878404679385c85cfa523b85ccb86e213 # v1
        with:
          labels: "Status: Needs Feedback"
      - uses: actions-ecosystem/action-add-labels@e79a6962e0d4c0c17b229090214935d2e33f8354 # v1
        with:
          labels: "Status: Needs Triage"
