name: Remove needs feedback label

on:
  issue_comment:
    types:
      - created

jobs:
  build:
    if: "github.repository_owner == 'php' && contains(github.event.issue.labels.*.name, 'Status: Needs Feedback') && github.event.issue.user.login == github.event.sender.login"
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "Status: Needs Feedback"
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "Status: Needs Triage"
