name: Verify Bundled Files

on:
  push:
    paths: &paths
      - '.github/scripts/download-bundled/**'
      - 'Zend/asm/**'
      - 'Zend/zend_simd.h'
      - 'ext/date/lib/**'
      - 'ext/hash/xxhash/**'
      - 'ext/opcache/jit/ir/**'
      - 'ext/pcre/pcre2lib/**'
      - 'ext/uri/uriparser/**'
  pull_request:
    paths: *paths
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch: ~

permissions:
  contents: read

jobs:
  VERIFY_BUNDLED_FILES:
    name: Verify Bundled Files
    runs-on: ubuntu-24.04
    steps:
      - name: git checkout
        uses: actions/checkout@v6

      - name: Detect changed files
        if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            'boost-context':
              - '.github/scripts/download-bundled/boost-context.*'
              - 'Zend/asm/**'
            xsse:
              - '.github/scripts/download-bundled/xsse.*'
              - 'Zend/zend_simd.h'
            timelib:
              - '.github/scripts/download-bundled/timelib.*'
              - 'ext/date/lib/**'
            xxhash:
              - '.github/scripts/download-bundled/xxhash.*'
              - 'ext/hash/xxhash/**'
            ir:
              - '.github/scripts/download-bundled/ir.*'
              - 'ext/opcache/jit/ir/**'
            pcre2:
              - '.github/scripts/download-bundled/pcre2.*'
              - 'ext/pcre/pcre2lib/**'
            uriparser:
              - '.github/scripts/download-bundled/uriparser.*'
              - 'ext/uri/uriparser/**'

      - name: 'boost.context'
        if: ${{ !cancelled() && (steps.changes.outputs.pcre2 == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') }}
        run: |
          echo "::group::Download"
          .github/scripts/download-bundled/boost-context.sh
          echo "::endgroup::"
          echo "::group::Verify files"
          .github/scripts/test-directory-unchanged.sh 'Zend/asm'
          echo "::endgroup::"
      - name: XSSE
        if: ${{ !cancelled() && (steps.changes.outputs.pcre2 == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') }}
        run: |
          echo "::group::Download"
          .github/scripts/download-bundled/xsse.sh
          echo "::endgroup::"
          echo "::group::Verify files"
          .github/scripts/test-directory-unchanged.sh 'Zend/zend_simd.h'
          echo "::endgroup::"
      - name: timelib
        if: ${{ !cancelled() && (steps.changes.outputs.pcre2 == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') }}
        run: |
          echo "::group::Download"
          .github/scripts/download-bundled/timelib.sh
          echo "::endgroup::"
          echo "::group::Verify files"
          .github/scripts/test-directory-unchanged.sh 'ext/date/lib'
          echo "::endgroup::"
      - name: xxHash
        if: ${{ !cancelled() && (steps.changes.outputs.pcre2 == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') }}
        run: |
          echo "::group::Download"
          .github/scripts/download-bundled/xxhash.sh
          echo "::endgroup::"
          echo "::group::Verify files"
          .github/scripts/test-directory-unchanged.sh 'ext/hash/xxhash'
          echo "::endgroup::"
      - name: IR
        if: ${{ !cancelled() && (steps.changes.outputs.pcre2 == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') }}
        run: |
          echo "::group::Download"
          .github/scripts/download-bundled/ir.sh
          echo "::endgroup::"
          echo "::group::Verify files"
          .github/scripts/test-directory-unchanged.sh 'ext/opcache/jit/ir'
          echo "::endgroup::"
      - name: PCRE2
        if: ${{ !cancelled() && (steps.changes.outputs.pcre2 == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') }}
        run: |
          echo "::group::Download"
          .github/scripts/download-bundled/pcre2.sh
          echo "::endgroup::"
          echo "::group::Verify files"
          .github/scripts/test-directory-unchanged.sh 'ext/pcre/pcre2lib'
          echo "::endgroup::"
      - name: uriparser
        if: ${{ !cancelled() && (steps.changes.outputs.pcre2 == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') }}
        run: |
          echo "::group::Download"
          .github/scripts/download-bundled/uriparser.sh
          echo "::endgroup::"
          echo "::group::Verify files"
          .github/scripts/test-directory-unchanged.sh 'ext/uri/uriparser'
          echo "::endgroup::"
